//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBWallpaperObserver.h"
#import "_SBFakeBlur.h"

@class NSString;

@interface _SBAccessibilityTintView : UIView <_SBFakeBlur, SBWallpaperObserver>
{
    int _variant;
    BOOL _fullscreen;
    BOOL _transformIgnoresRotation;
    id <_SBFakeBlurObserver> _observer;
}

@property(nonatomic) __weak id <_SBFakeBlurObserver> observer; // @synthesize observer=_observer;
@property(nonatomic) BOOL transformIgnoresRotation; // @synthesize transformIgnoresRotation=_transformIgnoresRotation;
@property(nonatomic) BOOL fullscreen; // @synthesize fullscreen=_fullscreen;
- (void).cxx_destruct;
- (void)_updateBackgroundColor;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(int)arg2;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (int)effectiveStyle;
- (void)requestStyle:(int)arg1;
- (void)dealloc;
- (id)initWithVariant:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

