//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBestAppSuggestion.h"

@class NSUUID, _DECAppItem, _DECResult;

@interface _SBExpertAppSuggestion : SBBestAppSuggestion
{
    _DECAppItem *_appSuggestion;
    _DECResult *_result;
}

@property(readonly, nonatomic) _DECResult *result; // @synthesize result=_result;
@property(readonly, nonatomic) _DECAppItem *appSuggestion; // @synthesize appSuggestion=_appSuggestion;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isArrivedAtHomePrediction;
- (BOOL)isArrivedAtWorkPrediction;
- (BOOL)isFirstWakePrediction;
- (BOOL)isCarPlayPrediction;
- (BOOL)isBluetoothAudioPrediction;
- (BOOL)isBluetoothPrediction;
- (BOOL)isHeadphonesPrediction;
- (BOOL)isPrediction;
- (BOOL)isLocallyGeneratedSuggestion;
- (id)originatingDeviceName;
- (BOOL)isLocationBasedSuggestion;
- (id)bundleIdentifier;
@property(readonly, nonatomic) NSUUID *resultUUID;
- (id)initWithAppSuggestion:(id)arg1 result:(id)arg2;

@end

