//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BSAuditToken, FBSDataResetRequest, FBSystemService, FBSystemServiceOpenApplicationRequest, NSDictionary, NSSet, NSString, NSURL;

@protocol FBSystemServiceDelegate <NSObject>

@optional
- (void)systemServicePrepareForShutdown:(FBSystemService *)arg1 andReboot:(BOOL)arg2;
- (void)systemService:(FBSystemService *)arg1 dataReset:(FBSDataResetRequest *)arg2 completion:(void (^)(BOOL))arg3;
- (void)systemServicePrepareForExit:(FBSystemService *)arg1 andRelaunch:(BOOL)arg2;
- (void)systemServicePrepareForShutdown:(FBSystemService *)arg1 withOptions:(unsigned int)arg2;
- (void)systemService:(FBSystemService *)arg1 handleActions:(NSSet *)arg2 origin:(BSAuditToken *)arg3 withResult:(void (^)(int))arg4;
- (void)systemService:(FBSystemService *)arg1 isPasscodeLockedOrBlockedWithResult:(void (^)(BOOL))arg2;
- (void)systemService:(FBSystemService *)arg1 handleOpenURLRequest:(NSURL *)arg2 application:(NSString *)arg3 options:(NSDictionary *)arg4 origin:(BSAuditToken *)arg5 withResult:(void (^)(int))arg6;
- (void)systemService:(FBSystemService *)arg1 handleOpenApplicationRequest:(NSString *)arg2 options:(NSDictionary *)arg3 origin:(BSAuditToken *)arg4 withResult:(void (^)(int))arg5;
- (void)systemService:(FBSystemService *)arg1 handleOpenApplicationRequest:(FBSystemServiceOpenApplicationRequest *)arg2 withCompletion:(void (^)(NSError *))arg3;
- (void)systemService:(FBSystemService *)arg1 canActivateApplication:(NSString *)arg2 withResult:(void (^)(int))arg3;
@end

