//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (SBAdditions)
- (BOOL)sb_containsEmoji;
- (id)_adjustedFontForScripts:(int)arg1 forFont:(id)arg2 withPointAdjustment:(float)arg3 ignoringContent:(BOOL)arg4;
- (BOOL)_isInScript:(int)arg1 useLocaleOnly:(BOOL)arg2;
- (id)_adjustedFontForScripts:(int)arg1 forFont:(id)arg2 ignoringContent:(BOOL)arg3;
- (id)_adjustedFontForScripts:(int)arg1 forFont:(id)arg2 withPointAdjustment:(float)arg3;
- (id)_adjustedFontForScripts:(int)arg1 forFont:(id)arg2;
- (BOOL)_isEntirelyCommon;
- (BOOL)_isEntirelyCharactersInScript:(int)arg1;
- (BOOL)sb_isEntirelyCharactersInSet:(struct USet *)arg1;
@end

