//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBToAppsWorkspaceTransaction.h"

@class NSObject<OS_dispatch_group>, SBAutoPiPWorkspaceTransaction, SBUIAnimationController, UIView;

@interface SBAppToAppWorkspaceTransaction : SBToAppsWorkspaceTransaction
{
    SBAutoPiPWorkspaceTransaction *_autoPiPTransaction;
    SBUIAnimationController *_animation;
    BOOL _animatedActivation;
    BOOL _animatedDeactivation;
    BOOL _deactivatingAppFromAppToAppGesture;
    BOOL _appQuitFromSwitcher;
    unsigned int _autoPIPTransitionOrder;
    NSObject<OS_dispatch_group> *_pipDuringSwitchTransitionTasksGroup;
    BOOL _performingDosidoWithPinnedSideSwitcherVisible;
    UIView *_homeScreenSnapshot;
    BOOL _preventWhitePointAdaptationStrengthUpdateOnComplete;
}

@property(nonatomic) BOOL preventWhitePointAdaptationStrengthUpdateOnComplete; // @synthesize preventWhitePointAdaptationStrengthUpdateOnComplete=_preventWhitePointAdaptationStrengthUpdateOnComplete;
- (void).cxx_destruct;
- (BOOL)_fromAppWantsLiveContentForDosido;
- (id)_setupAnimationFrom:(id)arg1 to:(id)arg2;
- (void)_cleanUpAfterAnimation;
- (void)_clearAnimation;
- (void)_animationDidFinish;
- (void)_animationDidRevealApplication;
- (void)_animationWillBegin:(BOOL)arg1;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)arg1;
- (void)_handleApplicationDidNotChange:(id)arg1;
- (void)_performPostAnimationTasksWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)_hasPostAnimationTasks;
- (void)_performPreAnimationTasksWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)_hasPreAnimationTasks;
- (id)_setupAnimation;
- (unsigned int)_serialOverlayPreDismissalOptions;
- (BOOL)_transitionWasCancelled;
- (void)_beginTransition;
- (void)_synchronizeWithSceneUpdates;
- (BOOL)shouldAnimateOrientationChangeOnCompletion;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)shouldRestoreSpringBoardContentOnCleanup;
- (void)performAdditionalTransition:(id)arg1;
- (void)cancelAdditionalTransition:(id)arg1;
- (void)prepareToPerformAdditionalTransition:(id)arg1;
- (BOOL)canPerformAdditionalTransition:(id)arg1;
- (void)_didComplete;
- (BOOL)_canBeInterrupted;
- (void)_begin;
- (id)debugDescription;
- (void)dealloc;

@end

