//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBAnimationSettings;

@interface SBAppSwitcherSettings : SBUISettings
{
    BOOL _clipStatusBarArea;
    BOOL _useTitleOpacityPrototypeSettings;
    BOOL _useOrbGesture;
    BOOL _forceDrivesInitialProgress;
    BOOL _playInitialHaptic;
    BOOL _playCommitHaptic;
    BOOL _canPop;
    int _switcherStyle;
    int _deckSwitcherForegroundWallpaperStyle;
    int _deckSwitcherBackgroundWallpaperStyle;
    float _deckSwitcherForegroundDarkeningFactor;
    float _deckSwitcherBackgroundDarkeningFactor;
    float _deckSwitcherForegroundSaturationDeltaFactor;
    float _deckSwitcherBackgroundSaturationDeltaFactor;
    float _deckSwitcherForegroundBlurRadius;
    float _deckSwitcherBackgroundBlurRadius;
    float _insertMass;
    float _insertStiffness;
    float _insertDamping;
    float _translateProgress;
    float _minTranslation;
    float _maxPopTranslation;
    float _commitToNextAppTranslation;
    float _nextAppPopScale;
    float _orbGestureRegionMax;
    float _panHysteresis;
    float _dismissAnimationMass;
    float _dismissAnimationStiffness;
    float _dismissAnimationDamping;
    float _dismissAnimationEpsilon;
    float _presentAnimationMass;
    float _presentAnimationStiffness;
    float _presentAnimationDamping;
    float _additionalThrowDisplacement;
    int _simplicityOptions;
    SBAnimationSettings *_dosidoAnimationSettings;
    double _aExpLayoutCoeff;
    double _bExpLayoutCoeff;
    double _depthPadding;
    double _titleOpacityACoeff;
    double _titleOpacityBCoeff;
    double _titleOpacityCCoeff;
    double _titleOpacityDCoeff;
}

+ (id)settingsControllerModule;
@property(retain) SBAnimationSettings *dosidoAnimationSettings; // @synthesize dosidoAnimationSettings=_dosidoAnimationSettings;
@property int simplicityOptions; // @synthesize simplicityOptions=_simplicityOptions;
@property float additionalThrowDisplacement; // @synthesize additionalThrowDisplacement=_additionalThrowDisplacement;
@property float presentAnimationDamping; // @synthesize presentAnimationDamping=_presentAnimationDamping;
@property float presentAnimationStiffness; // @synthesize presentAnimationStiffness=_presentAnimationStiffness;
@property float presentAnimationMass; // @synthesize presentAnimationMass=_presentAnimationMass;
@property float dismissAnimationEpsilon; // @synthesize dismissAnimationEpsilon=_dismissAnimationEpsilon;
@property float dismissAnimationDamping; // @synthesize dismissAnimationDamping=_dismissAnimationDamping;
@property float dismissAnimationStiffness; // @synthesize dismissAnimationStiffness=_dismissAnimationStiffness;
@property float dismissAnimationMass; // @synthesize dismissAnimationMass=_dismissAnimationMass;
@property BOOL canPop; // @synthesize canPop=_canPop;
@property BOOL playCommitHaptic; // @synthesize playCommitHaptic=_playCommitHaptic;
@property BOOL playInitialHaptic; // @synthesize playInitialHaptic=_playInitialHaptic;
@property float panHysteresis; // @synthesize panHysteresis=_panHysteresis;
@property BOOL forceDrivesInitialProgress; // @synthesize forceDrivesInitialProgress=_forceDrivesInitialProgress;
@property float orbGestureRegionMax; // @synthesize orbGestureRegionMax=_orbGestureRegionMax;
@property float nextAppPopScale; // @synthesize nextAppPopScale=_nextAppPopScale;
@property float commitToNextAppTranslation; // @synthesize commitToNextAppTranslation=_commitToNextAppTranslation;
@property float maxPopTranslation; // @synthesize maxPopTranslation=_maxPopTranslation;
@property float minTranslation; // @synthesize minTranslation=_minTranslation;
@property float translateProgress; // @synthesize translateProgress=_translateProgress;
@property BOOL useOrbGesture; // @synthesize useOrbGesture=_useOrbGesture;
@property float insertDamping; // @synthesize insertDamping=_insertDamping;
@property float insertStiffness; // @synthesize insertStiffness=_insertStiffness;
@property float insertMass; // @synthesize insertMass=_insertMass;
@property double titleOpacityDCoeff; // @synthesize titleOpacityDCoeff=_titleOpacityDCoeff;
@property double titleOpacityCCoeff; // @synthesize titleOpacityCCoeff=_titleOpacityCCoeff;
@property double titleOpacityBCoeff; // @synthesize titleOpacityBCoeff=_titleOpacityBCoeff;
@property double titleOpacityACoeff; // @synthesize titleOpacityACoeff=_titleOpacityACoeff;
@property BOOL useTitleOpacityPrototypeSettings; // @synthesize useTitleOpacityPrototypeSettings=_useTitleOpacityPrototypeSettings;
@property double depthPadding; // @synthesize depthPadding=_depthPadding;
@property double bExpLayoutCoeff; // @synthesize bExpLayoutCoeff=_bExpLayoutCoeff;
@property double aExpLayoutCoeff; // @synthesize aExpLayoutCoeff=_aExpLayoutCoeff;
@property BOOL clipStatusBarArea; // @synthesize clipStatusBarArea=_clipStatusBarArea;
@property float deckSwitcherBackgroundBlurRadius; // @synthesize deckSwitcherBackgroundBlurRadius=_deckSwitcherBackgroundBlurRadius;
@property float deckSwitcherForegroundBlurRadius; // @synthesize deckSwitcherForegroundBlurRadius=_deckSwitcherForegroundBlurRadius;
@property float deckSwitcherBackgroundSaturationDeltaFactor; // @synthesize deckSwitcherBackgroundSaturationDeltaFactor=_deckSwitcherBackgroundSaturationDeltaFactor;
@property float deckSwitcherForegroundSaturationDeltaFactor; // @synthesize deckSwitcherForegroundSaturationDeltaFactor=_deckSwitcherForegroundSaturationDeltaFactor;
@property float deckSwitcherBackgroundDarkeningFactor; // @synthesize deckSwitcherBackgroundDarkeningFactor=_deckSwitcherBackgroundDarkeningFactor;
@property float deckSwitcherForegroundDarkeningFactor; // @synthesize deckSwitcherForegroundDarkeningFactor=_deckSwitcherForegroundDarkeningFactor;
@property int deckSwitcherBackgroundWallpaperStyle; // @synthesize deckSwitcherBackgroundWallpaperStyle=_deckSwitcherBackgroundWallpaperStyle;
@property int deckSwitcherForegroundWallpaperStyle; // @synthesize deckSwitcherForegroundWallpaperStyle=_deckSwitcherForegroundWallpaperStyle;
@property int switcherStyle; // @synthesize switcherStyle=_switcherStyle;
- (void).cxx_destruct;
- (BOOL)shouldSimplifyForOptions:(int)arg1;
- (void)setDefaultValues;

@end

