//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UABestAppSuggestionManagerDelegate.h"

@class NSString, SBBestAppSuggestion, UABestAppSuggestion, UABestAppSuggestionManager, _DECConsumer, _DECResult;

@interface SBAppSuggestionManager : NSObject <UABestAppSuggestionManagerDelegate>
{
    UABestAppSuggestionManager *_continuitySuggestionManager;
    UABestAppSuggestion *_continuityCurrentBestSuggestion;
    _DECConsumer *_expertCenterSuggestionMonitor;
    _DECResult *_currentExpertBestSuggestion;
    SBBestAppSuggestion *_currentBestSuggestion;
    BOOL _isListeningForContinuitySuggestion;
    BOOL _isListeningForExpertCenterSuggestion;
    BOOL _screenOnDueToUserEvent;
    BOOL _screenOnAndLookingForEvent;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (unsigned int)_supportedExpertCenterCategories;
- (void)expertCenterSuggestionChanged:(id)arg1;
- (void)bestAppSuggestionChanged:(id)arg1;
- (void)_calculateBestSuggestionAndNotifyListeners;
- (void)noteNotActivatingForAppSuggestion:(id)arg1 fromSource:(int)arg2;
- (void)noteActivatingForAppSuggestion:(id)arg1 fromSource:(int)arg2;
- (void)_setContinuitySuggestionUpdatesEnabled:(BOOL)arg1 expertCenterSuggestionUpdatesEnabled:(BOOL)arg2;
- (void)_evaluateSuggestionUpdates:(id)arg1;
- (void)_handleInitialSpringBoardLaunch;
- (void)_nextUserEventOccured:(id)arg1;
- (void)_screenDidUndim:(id)arg1;
- (void)_screenDidDim:(id)arg1;
- (void)startFetchingPayloadForAppSuggestion:(id)arg1;
- (void)performWithCurrentSuggestedAppAndApplication:(CDUnknownBlockType)arg1;
- (id)currentSuggestedApp;
- (void)_stopListeningForNotifications;
- (void)_listenForNotifications;
- (void)_destroySuggestionSources;
- (void)_createSuggestionSources;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

