//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLayoutElementContainerView.h"

@class SBAppView;

@interface SBAppContainerView : SBLayoutElementContainerView
{
    SBAppView *_appView;
}

- (void).cxx_destruct;
- (id)snapshotView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)prepareForReuse;
- (void)setLayoutElementViewAlpha:(float)arg1;
- (unsigned int)_supportedOrientations;
@property(retain, nonatomic) SBAppView *appView;
- (void)setDisplayMode:(int)arg1;
- (int)displayMode;

@end

