//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSHashTable, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSPointerArray, NSString, SBAppStatusBarSettings;

@interface SBAppStatusBarManager : NSObject <BSDescriptionProviding>
{
    NSHashTable *_disableAlphaChangeAssertions;
    NSHashTable *_disableUserInteractionChangeAssertions;
    NSMutableOrderedSet *_windowLevelOverrideReasons;
    NSMutableDictionary *_windowLevelOverrideMap;
    NSPointerArray *_statusBarSettingsAssertionsByLevel[10];
    SBAppStatusBarSettings *_currentStatusBarSettings;
    NSMutableDictionary *_edgeInsetsDictionary;
    NSMutableSet *_activeLayoutLayers;
    float _defaultWindowLevel;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)_applyEdgeInsetsToStatusBar;
- (void)_updateWindowLevel;
- (void)_setStatusBarValueForPropertyWithAssertions:(id)arg1 setter:(CDUnknownBlockType)arg2;
- (id)_descriptionForPropertyWithAssertions:(id)arg1;
- (void)_evaluateSettings;
- (void)_cleanUpAllStatusBarSettingsAssertions;
- (void)_didTransitionFromSpringBoard;
- (void)_willTransitionToSpringBoard;
- (void)_modifiedStatusBarSettingsAssertion:(id)arg1;
- (void)_removeStatusBarSettingsAssertion:(id)arg1;
- (void)_addStatusBarSettingsAssertion:(id)arg1;
- (void)_removeDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1;
- (void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) struct UIEdgeInsets statusBarEdgeInsets;
- (void)setStatusBarEdgeInsets:(struct UIEdgeInsets)arg1 forLayoutLayer:(unsigned int)arg2;
- (void)removeActiveLayoutLayer:(unsigned int)arg1;
- (void)addActiveLayoutLayer:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int topmostActiveLayoutLayer;
- (void)removeWindowLevelOverrideReason:(id)arg1;
- (void)setWindowLevel:(float)arg1 forOverrideReason:(id)arg2;
- (void)setDefaultWindowLevel:(float)arg1;
- (BOOL)isStatusBarUserInteractionEnabled;
- (void)setStatusBarUserInteractionEnabled:(BOOL)arg1;
- (BOOL)isStatusBarHidden;
- (void)setStatusBarAlpha:(float)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

