//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseSoftwareUpdateAlertItem.h"

@interface SBBaseSoftwareUpdateInstallFailureAlertItem : SBBaseSoftwareUpdateAlertItem
{
    BOOL _actionTaken;
}

@property(nonatomic) BOOL actionTaken; // @synthesize actionTaken=_actionTaken;
- (BOOL)allowInSetup;
- (void)willDeactivateForReason:(int)arg1;

@end

