//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class SBSoftwareUpdateController, SUDescriptor;

@interface SBBaseSoftwareUpdateAlertItem : SBAlertItem
{
    SUDescriptor *_descriptor;
    SBSoftwareUpdateController *_controller;
}

@property(readonly, nonatomic) SBSoftwareUpdateController *softwareUpdateController; // @synthesize softwareUpdateController=_controller;
@property(readonly, nonatomic) SUDescriptor *descriptor; // @synthesize descriptor=_descriptor;
- (void).cxx_destruct;
- (void)willDeactivateForReason:(int)arg1;
- (BOOL)dismissOnLock;
- (BOOL)undimsScreen;
- (BOOL)unlocksScreen;
- (BOOL)shouldShowInLockScreen;
- (BOOL)forcesModalAlertAppearance;
- (void)activateDisplayWithURL:(id)arg1;
- (void)activateSoftwareUpdateSettingsDisplay;
- (id)updateName;
- (id)initWithDescriptor:(id)arg1 softwareUpdateController:(id)arg2;

@end

