//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBBatteryWidgetVisibilityController : NSObject
{
}

+ (id)sharedInstance;
- (void)_makeVisible;
- (BOOL)_isVisible;
- (BOOL)_isAlwaysVisible;
- (void)_setVisibleIfNecessary:(BOOL)arg1;
- (void)_setHasContent:(BOOL)arg1;
- (BOOL)_containsExternalBattery;
- (void)_connectedDevicesDidChange;
- (id)init;

@end

