//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCUIControlCenterSystemAgent.h"

@class NSString;

@interface SBControlCenterSystemAgent : NSObject <CCUIControlCenterSystemAgent>
{
}

- (BOOL)isUILocked;
- (id)materialBackgroundView;
- (id)frontmostApplicationDisplayID;
- (id)getFGSceneIdentifiers;
- (BOOL)wifiIsPowered;
- (BOOL)wifiDevicePresent;
- (void)setWifiPowered:(BOOL)arg1;
- (void)updateWifiDevicePresence;
- (BOOL)isInAirplaneMode;
- (BOOL)isOrientationLocked;
- (void)unlockOrientation;
- (void)lockOrientation;
- (BOOL)wirelessDisplayRouteIsPicked;
- (id)nameOfPickedRoute;
- (BOOL)handsetRouteIsSelected;
- (void)setRingerMuted:(BOOL)arg1;
- (BOOL)isRingerMuted;
- (void)activateAppWithDisplayID:(id)arg1 url:(id)arg2;
- (void)dismissAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (id)prototypeSettings;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

