//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "UICoordinateSpace.h"

@class NSString;

@interface SBDashBoardRegion : NSObject <NSCopying, UICoordinateSpace>
{
    BOOL _hidden;
    NSString *_identifier;
    int _role;
    id <UICoordinateSpace> _coordinateSpace;
    id <UICoordinateSpace> _identity;
    id _provider;
    struct CGRect _extent;
}

+ (id)regionForCoordinateSpace:(id)arg1 withExtent:(struct CGRect)arg2;
+ (id)regionForCoordinateSpace:(id)arg1;
@property(nonatomic) __weak id provider; // @synthesize provider=_provider;
@property(nonatomic) __weak id <UICoordinateSpace> identity; // @synthesize identity=_identity;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> coordinateSpace; // @synthesize coordinateSpace=_coordinateSpace;
@property(nonatomic, getter=isHidden) BOOL hidden; // @synthesize hidden=_hidden;
@property(nonatomic) int role; // @synthesize role=_role;
@property(readonly, nonatomic) struct CGRect extent; // @synthesize extent=_extent;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (struct CGRect)convertRect:(struct CGRect)arg1 fromCoordinateSpace:(id)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 toCoordinateSpace:(id)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromCoordinateSpace:(id)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 toCoordinateSpace:(id)arg2;
@property(readonly, nonatomic) struct CGRect bounds;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)intersectsCoordinateSpace:(id)arg1;
- (id)role:(int)arg1;
- (id)regionForCoordinateSpace:(id)arg1;
- (id)initWithCoordinateSpace:(id)arg1 withExtent:(struct CGRect)arg2 role:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

