//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "FBSceneMonitorDelegate.h"
#import "SBAppViewHostRequester.h"
#import "SBApplicationHosting.h"

@class FBSceneMonitor, NSMutableSet, NSString, SBActivationSettings, SBAppView, SBApplication, SBFAuthenticationAssertion, SBOrientationTransformWrapperView;

@interface SBDashBoardHostedAppViewController : SBDashBoardViewControllerBase <SBAppViewHostRequester, FBSceneMonitorDelegate, SBApplicationHosting>
{
    SBApplication *_hostedApp;
    SBAppView *_hostedAppView;
    SBActivationSettings *_activationSettings;
    NSMutableSet *_activeTransitions;
    FBSceneMonitor *_sceneMonitor;
    SBFAuthenticationAssertion *_authenticationAssertion;
    BOOL _automatesLifecycle;
    NSString *_bundleIdentifier;
    unsigned int _options;
    int _mode;
    SBOrientationTransformWrapperView *_orientationWrapperView;
}

@property(retain, nonatomic) SBOrientationTransformWrapperView *orientationWrapperView; // @synthesize orientationWrapperView=_orientationWrapperView;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(nonatomic) BOOL automatesLifecycle; // @synthesize automatesLifecycle=_automatesLifecycle;
@property(readonly, nonatomic) SBAppView *appView; // @synthesize appView=_hostedAppView;
@property(nonatomic) unsigned int options; // @synthesize options=_options;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;
- (void)_deactivateHostedApp;
- (void)_reallyActivateApp;
- (void)_activateApp;
- (void)_destroyAppView;
- (void)_createAppView;
- (void)sceneMonitor:(id)arg1 sceneSettingsDidChangeWithDiff:(id)arg2 previousSettings:(id)arg3;
- (void)sceneMonitor:(id)arg1 sceneWasDestroyed:(id)arg2;
- (int)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
- (void)hostedAppWillRotateToInterfaceOrientation:(int)arg1;
- (id)hostedApp;
- (BOOL)isHostingAnApp;
- (BOOL)canHostAnApp;
- (int)presentationPriority;
- (int)presentationType;
- (int)presentationStyle;
- (void)configureDisplayLayoutElement:(id)arg1;
- (id)displayLayoutElementIdentifier;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)updateWithApplication:(id)arg1;
- (void)dealloc;
- (id)initWithApplication:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

