//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertView.h"

#import "BSUIScrollViewDelegate.h"
#import "SBDashBoardBackgroundStyleTransitioning.h"
#import "SBDashBoardViewTransitionSource.h"

@class NSString, SBDashBoardBackgroundView, SBDashBoardPageControl, SBFLockScreenDateView, SBHorizontalScrollFailureRecognizer, SBPagedScrollView, SBWallpaperEffectView, UIGestureRecognizer, UIView, UIVisualEffectView, _UILegibilitySettings;

@interface SBDashBoardView : SBAlertView <BSUIScrollViewDelegate, SBDashBoardBackgroundStyleTransitioning, SBDashBoardViewTransitionSource>
{
    SBDashBoardBackgroundView *_backgroundView;
    SBPagedScrollView *_scrollView;
    UIView *_dateTimeClippingView;
    UIView *_authIndicator;
    UIView *_slideableContentView;
    UIVisualEffectView *_dateEffectView;
    CDStruct_6b1f2d91 _transitionContext;
    unsigned int _currentPage;
    float _scrollViewStartingXOffset;
    BOOL _changingScrollViewLayout;
    SBHorizontalScrollFailureRecognizer *_horizontalScrollFailureRecognizer;
    BOOL _preventHorizontalScrollFailureGestureRemoval;
    BOOL _forceDateViewCentered;
    BOOL _dateViewIsVibrant;
    BOOL _legibilitySettingsOverrideVibrancy;
    BOOL _statusBarLegibilityEnabled;
    UIView *_bottomPage;
    id <SBDashBoardViewDelegate> _delegate;
    UIView *_mainPageView;
    SBDashBoardPageControl *_pageControl;
    SBFLockScreenDateView *_dateView;
    int _dateViewPageAlignment;
    UIView *_fakeStatusBarView;
    UIGestureRecognizer *_irisGestureRecognizer;
    UIView *_modalPresentationView;
    SBWallpaperEffectView *_wallpaperEffectView;
    UIView *_tintingView;
    _UILegibilitySettings *_legibilitySettings;
    struct CGPoint _dateViewOffset;
    struct CGPoint _foregroundViewPositionOffset;
}

@property(nonatomic) BOOL statusBarLegibilityEnabled; // @synthesize statusBarLegibilityEnabled=_statusBarLegibilityEnabled;
@property(nonatomic) BOOL legibilitySettingsOverrideVibrancy; // @synthesize legibilitySettingsOverrideVibrancy=_legibilitySettingsOverrideVibrancy;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) struct CGPoint foregroundViewPositionOffset; // @synthesize foregroundViewPositionOffset=_foregroundViewPositionOffset;
@property(retain, nonatomic) SBDashBoardBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *tintingView; // @synthesize tintingView=_tintingView;
@property(retain, nonatomic) SBWallpaperEffectView *wallpaperEffectView; // @synthesize wallpaperEffectView=_wallpaperEffectView;
@property(retain, nonatomic) UIView *modalPresentationView; // @synthesize modalPresentationView=_modalPresentationView;
@property(readonly, nonatomic) UIView *slideableContentView; // @synthesize slideableContentView=_slideableContentView;
@property(retain, nonatomic) UIGestureRecognizer *irisGestureRecognizer; // @synthesize irisGestureRecognizer=_irisGestureRecognizer;
@property(retain, nonatomic) UIView *fakeStatusBarView; // @synthesize fakeStatusBarView=_fakeStatusBarView;
@property(nonatomic) BOOL dateViewIsVibrant; // @synthesize dateViewIsVibrant=_dateViewIsVibrant;
@property(nonatomic) BOOL forceDateViewCentered; // @synthesize forceDateViewCentered=_forceDateViewCentered;
@property(nonatomic) int dateViewPageAlignment; // @synthesize dateViewPageAlignment=_dateViewPageAlignment;
@property(nonatomic) struct CGPoint dateViewOffset; // @synthesize dateViewOffset=_dateViewOffset;
@property(retain, nonatomic) SBFLockScreenDateView *dateView; // @synthesize dateView=_dateView;
@property(retain, nonatomic) SBDashBoardPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIView *mainPageView; // @synthesize mainPageView=_mainPageView;
@property(retain, nonatomic) SBPagedScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <SBDashBoardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *bottomPage; // @synthesize bottomPage=_bottomPage;
- (void).cxx_destruct;
- (void)_horizontalScrollFailureGestureRecognizerChanged:(id)arg1;
- (void)_installHorizontalScrollFailureGesture:(BOOL)arg1;
- (void)_updateLegibility;
- (unsigned int)_indexOfMainPage;
- (CDStruct_6b1f2d91)_transitionContextForScrollContext:(CDStruct_4c17c720 *)arg1;
- (void)_addTintingView;
- (void)_addAuthIndicator;
- (void)_addDateTimeContainer;
- (void)_addPageControl;
- (void)_addScrollView;
- (void)_addSlideableContentView;
- (void)_orderSubviews;
- (void)_layoutSlideableContentView;
- (void)_layoutBottomPage;
- (void)_layoutAuthIndicator;
- (void)_layoutPageControl;
- (void)_layoutFakeStatusBarView;
- (void)_computeDateViewOffsetAdjustments:(struct CGPoint *)arg1 outAlignmentPercent:(float *)arg2;
- (void)_layoutDateView;
- (void)_layoutTintingView;
- (void)_layoutWallpaperEffectView;
- (void)_layoutDateTimeViewClippingView;
- (struct CGRect)_overlayClippingFrame;
- (void)_layoutScrollView;
- (void)_layoutBackgroundView;
- (void)_setDateView:(id)arg1 forTesting:(BOOL)arg2;
- (void)completeTransitionToBackgroundStyle:(int)arg1;
- (void)updateBackgroundStyleTransitionProgress:(float)arg1;
- (void)beginTransitionToBackgroundStyle:(int)arg1;
@property(nonatomic) int backgroundStyle;
@property(readonly, nonatomic, getter=isTransitioningBackgroundStyle) BOOL transitioningBackgroundStyle;
@property(readonly, nonatomic) CDStruct_6b1f2d91 transitionContext;
@property(readonly, nonatomic, getter=isTransitioning) BOOL transitioning;
@property(readonly, nonatomic) int participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1 withContext:(CDStruct_4c17c720)arg2;
- (void)scrollViewWillBeginScrolling:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)layoutSubviews;
- (void)didAddSubview:(id)arg1;
- (void)invalidate;
- (void)updateUIForAuthenticated:(BOOL)arg1;
- (void)updatePageControl;
- (BOOL)resetContentOffsetToCurrentPage;
- (BOOL)scrollToPageAtIndex:(unsigned int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)resetScrollViewToMainPageAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

