//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardPresentationViewController.h"

#import "SBDashBoardPageViewControllerProtocol.h"

@class NSArray, NSSet, NSString, SBDashBoardAppearance, SBDashBoardBehavior, UIColor, _UILegibilitySettings;

@interface SBDashBoardPageViewController : SBDashBoardPresentationViewController <SBDashBoardPageViewControllerProtocol>
{
    id <SBDashBoardViewControllerProtocol> _dashBoardViewController;
    BOOL _transitioning;
    BOOL _authenticated;
}

+ (unsigned int)requiredCapabilities;
+ (BOOL)isAvailableForConfiguration;
+ (Class)viewClass;
@property(readonly, nonatomic) BOOL authenticated; // @synthesize authenticated=_authenticated;
@property(nonatomic, getter=isTransitioning) BOOL transitioning; // @synthesize transitioning=_transitioning;
@property(nonatomic) __weak id <SBDashBoardViewControllerProtocol> dashBoardViewController; // @synthesize dashBoardViewController=_dashBoardViewController;
- (void).cxx_destruct;
- (void)hostedAppWillRotateToInterfaceOrientation:(int)arg1;
- (id)hostedApp;
- (BOOL)isHostingAnApp;
- (BOOL)canHostAnApp;
- (void)handleAction:(id)arg1 fromSender:(id)arg2;
@property(readonly, nonatomic) int presentationAltitude;
@property(readonly, nonatomic) int participantState;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewDidLoad;
- (void)didTransitionToVisible:(BOOL)arg1;
- (void)updateTransitionToVisible:(BOOL)arg1 progress:(float)arg2 mode:(int)arg3;
- (void)willTransitionToVisible:(BOOL)arg1;
- (id)pageView;
- (id)view;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy, nonatomic) SBDashBoardAppearance *activeAppearance;
@property(readonly, copy, nonatomic) SBDashBoardBehavior *activeBehavior;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) int backgroundStyle;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) int idleTimerDuration;
@property(readonly, nonatomic) int idleTimerMode;
@property(readonly, nonatomic) int idleWarnMode;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, nonatomic) int notificationBehavior;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
@property(readonly, nonatomic) int presentationPriority;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, nonatomic) int presentationStyle;
@property(readonly, nonatomic) int presentationTransition;
@property(readonly, nonatomic) int presentationType;
@property(nonatomic) __weak id <SBDashBoardViewPresenting> presenter;
@property(readonly, nonatomic) unsigned int restrictedCapabilities;
@property(readonly, nonatomic) int scrollingMode;
@property(readonly) Class superclass;

@end

