//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBDashBoardBackgroundStyleTransitioning.h"
#import "SBDashBoardWallpaperOverlay.h"

@class NSString, SBBackdropView;

@interface SBDashBoardBackgroundView : UIView <SBDashBoardBackgroundStyleTransitioning, SBDashBoardWallpaperOverlay>
{
    int _style;
    int _transitionStyle;
    BOOL _transitioning;
    float _progress;
    SBBackdropView *_backdropView;
    UIView *_sourceOverView;
    UIView *_darkenSourceOverView;
    UIView *_tintView;
}

@property(readonly, nonatomic, getter=isTransitioningBackgroundStyle) BOOL transitioningBackgroundStyle; // @synthesize transitioningBackgroundStyle=_transitioning;
@property(nonatomic) int backgroundStyle; // @synthesize backgroundStyle=_style;
- (void).cxx_destruct;
- (void)_tintWithProgress:(float)arg1;
- (void)_darkenWithProgress:(float)arg1;
- (BOOL)_styleDarkens:(int)arg1;
- (id)_backgroundColorForDarkenAlpha:(float)arg1 andProgress:(float)arg2;
- (void)completeTransitionToBackgroundStyle:(int)arg1;
- (void)updateBackgroundStyleTransitionProgress:(float)arg1;
- (void)beginTransitionToBackgroundStyle:(int)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

