//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIChevronView.h"

#import "SBUILegibility.h"

@class NSString, SBWallpaperEffectView, _UILegibilitySettings;

@interface SBDashBoardVibrantWallpaperChevronView : SBUIChevronView <SBUILegibility>
{
    float _legibilityStrength;
    _UILegibilitySettings *_legibilitySettings;
    SBWallpaperEffectView *_effectView;
}

@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) float strength; // @synthesize strength=_legibilityStrength;
- (void).cxx_destruct;
- (void)_updateVibrancy;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithColor:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

