//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBLockScreenPluginDelegate.h"

@class NSString, SBLockScreenPlugin;

@interface SBDashBoardPluginViewController : SBDashBoardViewControllerBase <SBLockScreenPluginDelegate>
{
    SBLockScreenPlugin *_plugin;
}

@property(readonly, nonatomic) SBLockScreenPlugin *plugin; // @synthesize plugin=_plugin;
- (void).cxx_destruct;
- (BOOL)handleEvent:(id)arg1;
- (void)pluginAppearanceDidChange:(id)arg1;
- (id)appearanceIdentifier;
- (id)dashBoardIdentifier;
- (int)presentationType;
- (int)presentationPriority;
- (int)presentationTransition;
- (int)presentationStyle;
- (id)displayLayoutElementIdentifier;
- (void)updateForPresentation:(id)arg1;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)performCustomTransitionToVisible:(BOOL)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithLockScreenPlugin:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

