//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "SBDashBoardIdleBehaviorProviding.h"

@protocol SBDashBoardBehaviorProviding <NSObject, SBDashBoardIdleBehaviorProviding>
@property(readonly, nonatomic) unsigned int restrictedCapabilities;
@property(readonly, nonatomic) int notificationBehavior;
@property(readonly, nonatomic) int scrollingMode;
@end

