//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "NSCopying.h"
#import "SBDashBoardAppearanceProviding.h"

@class NSMutableSet, NSSet, NSString, UIColor, _UILegibilitySettings;

@interface SBDashBoardAppearance : NSObject <BSDescriptionProviding, SBDashBoardAppearanceProviding, NSCopying>
{
    NSMutableSet *_components;
    BOOL _transitional;
    NSString *_identifier;
    int _backgroundStyle;
    _UILegibilitySettings *_legibilitySettings;
    UIColor *_backgroundColor;
}

+ (id)appearanceForProvider:(id)arg1;
+ (id)appearanceWithIdentifier:(id)arg1;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(copy, nonatomic) NSSet *components; // @synthesize components=_components;
@property(nonatomic) int backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
@property(nonatomic, getter=isTransitional) BOOL transitional; // @synthesize transitional=_transitional;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
- (void)removeAllComponentsWithIdentifier:(id)arg1;
- (void)removeComponent:(id)arg1;
- (void)addComponent:(id)arg1;
- (int)flagForComponentType:(int)arg1;
- (id)componentForType:(int)arg1 property:(unsigned int)arg2;
- (id)componentForType:(int)arg1 identifier:(id)arg2;
- (BOOL)isEqualToAppearance:(id)arg1;
- (void)unionAppearance:(id)arg1;
- (void)reset;
- (id)initWithIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

