//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBDashBoardVibrancyUtility : NSObject
{
}

+ (id)_averageWallpaperColorForFrame:(struct CGRect)arg1;
+ (void)updateVibrantView:(id)arg1 screenRect:(struct CGRect)arg2 backgroundView:(id)arg3;
+ (BOOL)supportsVibrancy;

@end

