//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSearchEtceteraMultiplexingViewController.h"

#import "SBDashBoardAppearanceProviding.h"
#import "SBDashBoardBehaviorProviding.h"
#import "SBDashBoardEventHandling.h"
#import "SPUISearchViewControllerDelegate.h"

@class NSMutableSet, NSSet, NSString, SBDashBoardComponent, SBDashBoardPageViewController, UIColor, _UILegibilitySettings;

@interface SBDashBoardTodayViewController : SBSearchEtceteraMultiplexingViewController <SPUISearchViewControllerDelegate, SBDashBoardAppearanceProviding, SBDashBoardBehaviorProviding, SBDashBoardEventHandling>
{
    BOOL _isAuthenticated;
    BOOL _isDragging;
    SBDashBoardComponent *_dateViewComponent;
    float _reachabilityYOffset;
    id <SBDashBoardTodayViewControllerDelegate> _todayViewControllerDelegate;
    BOOL _showingMultiColumnLayout;
    BOOL _disableScrollingForModalPresentation;
    NSSet *_contentViews;
    NSMutableSet *_scrollingDisabledReasons;
    SBDashBoardPageViewController *_pageController;
}

@property(nonatomic) __weak SBDashBoardPageViewController *pageController; // @synthesize pageController=_pageController;
@property(nonatomic) __weak id <SBDashBoardTodayViewControllerDelegate> todayViewControllerDelegate; // @synthesize todayViewControllerDelegate=_todayViewControllerDelegate;
- (void).cxx_destruct;
- (id)_dateMovingScrollView;
- (float)_maxClippingOffset;
- (id)_searchNavigationBar;
- (id)_contentView;
- (id)_todayViewController;
- (BOOL)_shouldHideDateTimeForZeroWidgetDisplay;
- (void)_updateAppearanceForScrollView:(id)arg1;
- (struct CGPoint)_offsetForScrollView:(id)arg1;
- (void)_updateAppearance;
- (void)_updateBehavior;
- (void)_evaluateContentViews;
- (void)_hitCancelButtonWithCompletion:(CDUnknownBlockType)arg1;
- (void)changeToMode:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)_focusSearchFieldWithCompletion:(CDUnknownBlockType)arg1;
- (int)requestedWallpaperVariantForWidgetBackgroundViews;
- (id)requestedLegibilitySettings;
- (void)_changeSpotlightVisible:(BOOL)arg1 animationBegan:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_changeSpotlightVisible:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setReachabilityYOffset:(float)arg1;
- (void)reachabilityWillDisable;
- (void)reachabilityWillEnableWithOffset:(struct CGPoint)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)dismissSearchViewWithReason:(unsigned int)arg1;
- (void)searchFieldDidFocus;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, nonatomic) unsigned int restrictedCapabilities;
@property(readonly, nonatomic) int notificationBehavior;
@property(readonly, nonatomic) int scrollingMode;
@property(readonly, nonatomic) int idleWarnMode;
@property(readonly, nonatomic) int idleTimerMode;
@property(readonly, nonatomic) int idleTimerDuration;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) int backgroundStyle;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
- (BOOL)wouldHandleButtonEvent:(id)arg1;
- (BOOL)handleEvent:(id)arg1;
- (void)didChangeToMode:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)willChangeToMode:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)presentationControllerDidEndDismissing:(id)arg1;
- (void)presentationControllerDidEndPresenting:(id)arg1;
- (void)_setDashBoardScrollingDisabled:(BOOL)arg1 forReason:(id)arg2;
- (BOOL)_isDashBoardScrollingDisabled;
- (void)willDeactivateHosting;
- (void)willActivateHosting;
- (unsigned int)initialPresentationMode;
- (unsigned int)defaultSearchViewDismissalReason;
- (unsigned int)defaultSearchViewPresentationSource;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

