//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardModalViewControllerBase.h"

#import "SBLockScreenEmergencyDialerDelegate.h"

@class NSString, SBLockScreenEmergencyDialerController;

@interface SBDashBoardEmergencyDialerViewController : SBDashBoardModalViewControllerBase <SBLockScreenEmergencyDialerDelegate>
{
    SBLockScreenEmergencyDialerController *_controller;
}

- (void).cxx_destruct;
- (void)emergencyDialer:(id)arg1 willDeactivateWithError:(id)arg2;
- (int)presentationPriority;
- (int)presentationType;
- (void)aggregateBehavior:(id)arg1;
- (BOOL)handleEvent:(id)arg1;
- (void)_loadEmergencyDialerView;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

