//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardNowPlayingViewController.h"

@class MPULockScreenMediaControlsViewController;

@interface SBDashBoardMediaControlsViewController : SBDashBoardNowPlayingViewController
{
    MPULockScreenMediaControlsViewController *_mediaControlsViewController;
}

+ (Class)viewClass;
- (void).cxx_destruct;
- (void)_updatePersistentUpdateStateForBacklightValue:(float)arg1;
- (void)_layoutMediaControls;
- (BOOL)handleEvent:(id)arg1;
- (int)presentationPriority;
- (int)presentationType;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithMediaControlsViewController:(id)arg1;

@end

