//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPageControl.h"

@class SBIconPageIndicatorImageSetCache, SBIconPageIndicatorImageSetResult;

@interface SBDashBoardPageControl : UIPageControl
{
    BOOL _cameraPageEnabled;
    BOOL __legibilityEnabled;
    BOOL __initializedLegibility;
    SBIconPageIndicatorImageSetCache *_imageSetCache;
    float __cachedDefaultHeight;
    SBIconPageIndicatorImageSetResult *__pageIndicatorImageSets;
    SBIconPageIndicatorImageSetResult *__cameraIndicatorImageSets;
}

+ (struct CGSize)defaultSize;
@property(retain, nonatomic, getter=_cameraIndicatorImageSets, setter=_setCameraIndicatorImageSets:) SBIconPageIndicatorImageSetResult *_cameraIndicatorImageSets; // @synthesize _cameraIndicatorImageSets=__cameraIndicatorImageSets;
@property(retain, nonatomic, getter=_pageIndicatorImageSets, setter=_setPageIndicatorImageSets:) SBIconPageIndicatorImageSetResult *_pageIndicatorImageSets; // @synthesize _pageIndicatorImageSets=__pageIndicatorImageSets;
@property(nonatomic, getter=_cachedDefaultHeight, setter=_setCachedDefaultHeight:) float _cachedDefaultHeight; // @synthesize _cachedDefaultHeight=__cachedDefaultHeight;
@property(nonatomic, getter=_hasInitializedLegibility, setter=_setHasInitializedLegibility:) BOOL _initializedLegibility; // @synthesize _initializedLegibility=__initializedLegibility;
@property(nonatomic, getter=_legibilityEnabled, setter=_setLegibilityEnabled:) BOOL _legibilityEnabled; // @synthesize _legibilityEnabled=__legibilityEnabled;
@property(retain, nonatomic) SBIconPageIndicatorImageSetCache *imageSetCache; // @synthesize imageSetCache=_imageSetCache;
@property(nonatomic, getter=isCameraPageEnabled) BOOL cameraPageEnabled; // @synthesize cameraPageEnabled=_cameraPageEnabled;
- (void).cxx_destruct;
- (float)_indicatorSpacing;
- (struct CGRect)_modernBounds;
- (void)_transitionIndicator:(id)arg1 toEnabled:(BOOL)arg2 index:(int)arg3;
- (void)_invalidateIndicators;
- (id)_indicatorViewEnabled:(BOOL)arg1 index:(int)arg2;
- (id)_createModernIndicatorImageFromView:(id)arg1;
- (struct CGSize)_modernTallPageIndicatorSize;
- (id)_pageIndicatorImage:(BOOL)arg1;
- (id)_cameraIndicatorImage:(BOOL)arg1;
- (void)_setIndicatorImage:(id)arg1 toEnabled:(BOOL)arg2 index:(int)arg3;
- (void)setLegibilitySettings:(id)arg1;
- (float)defaultHeight;
- (struct CGSize)sizeForNumberOfPages:(int)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

