//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSTransactionObserver.h"
#import "SBAppViewHostRequester.h"
#import "SBDashBoardAppearanceProviding.h"
#import "SBDashBoardPasscodeViewControllerDelegate.h"
#import "SBDashBoardViewTransitionSource.h"
#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class NSMutableArray, NSSet, NSString, NSURL, SBAppSuggestionManager, SBApplication, SBBestAppSuggestion, SBBounceSettings, SBDashBoardPasscodeViewController, SBLockScreenSettings, SBMainWorkspaceTransaction, SBNotificationCenterBounceAnimator, UIColor, UIPanGestureRecognizer, UIView, _UILegibilitySettings;

@interface SBDashBoardSlideUpToAppController : NSObject <UIGestureRecognizerDelegate, BSTransactionObserver, SBAppViewHostRequester, SBDashBoardPasscodeViewControllerDelegate, _UISettingsKeyObserver, SBDashBoardViewTransitionSource, SBDashBoardAppearanceProviding>
{
    SBLockScreenSettings *_testSettings;
    NSMutableArray *_deferredAppUpdateBlocks;
    BOOL _executingDeferredAppUpdateBlocks;
    float _currentYOffset;
    SBApplication *_targetApp;
    SBBestAppSuggestion *_targetAppInfo;
    NSURL *_targetURL;
    SBMainWorkspaceTransaction *_launchAppTransaction;
    UIView *_clippingView;
    UIView *_appDefaultImageView;
    UIView *_appBackgroundView;
    SBDashBoardPasscodeViewController *_passcodeViewController;
    UIPanGestureRecognizer *_slideUpToAppGestureRecognizer;
    SBBounceSettings *_bounceSettings;
    SBNotificationCenterBounceAnimator *_slideDownBounceAnimator;
    SBAppSuggestionManager *_appSuggestionManager;
    UIPanGestureRecognizer *_panGestureRecognizer;
    id <SBDashBoardSlideUpToAppControllerDelegate><SBDashBoardViewPresenting> _delegate;
    UIView *_containerView;
    unsigned int _state;
}

@property(nonatomic, getter=_state, setter=_setState:) unsigned int state; // @synthesize state=_state;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <SBDashBoardSlideUpToAppControllerDelegate><SBDashBoardViewPresenting> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
- (void).cxx_destruct;
- (void)_updateSlideUpToAppControllerWithCurrentSuggestedApp;
- (void)_suggestedAppDidChange:(id)arg1;
- (void)_deviceBlockedStateChanged:(id)arg1;
- (void)_passcodeLockStateChanged;
- (BOOL)_isPasscodeRequired;
- (void)_dismissPasscodeView;
- (void)_addOrRemovePasscodeViewIfNecessary;
- (void)_translateSlidingViewByY:(float)arg1;
- (void)_prepareForSlideUpAnimation;
- (void)_resetToInitialState;
- (void)_finishSlideDownGesture;
- (void)_finishSlideUpGesture;
- (id)_instantiateDynamicAnimationForTargetValue:(double)arg1 withInitialVelocity:(double)arg2;
- (void)_animateSlideUpWithVelocity:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_animateSlideDownWithVelocity:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_endSlideWithYTranslation:(float)arg1 velocty:(struct CGPoint)arg2 cancelled:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_updateSlideWithYTranslation:(float)arg1;
- (void)_beginSlideWithYTranslation:(float)arg1;
- (void)_slideUpToAppRecognizerDidPan:(id)arg1;
- (struct CGRect)_slideUpToAppGrabberZoneForGrabber:(id)arg1;
- (void)_setSlideUpToAppGestureRecognizer:(id)arg1;
- (void)_setupSlideUpToAppGesture;
- (void)_activateApp:(id)arg1 withAppInfo:(id)arg2 andURL:(id)arg3 animated:(BOOL)arg4;
- (void)_activateTargetAppAnimated:(BOOL)arg1;
- (void)_executeDeferredAppUpdateBlocks;
- (void)_setTargetApp:(id)arg1 withAppSuggestion:(id)arg2;
- (void)_setupSubviews;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (int)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
@property(readonly, nonatomic) CDStruct_6b1f2d91 transitionContext;
@property(readonly, nonatomic, getter=isTransitioning) BOOL transitioning;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) int backgroundStyle;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, nonatomic) int participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)passcodeViewController:(id)arg1 didCompletePasscodeEntry:(BOOL)arg2;
- (void)passcodeViewControllerDidCancelPasscodeEntry:(id)arg1;
- (void)passcodeViewControllerDidBeginPasscodeEntry:(id)arg1;
- (void)transactionDidComplete:(id)arg1;
- (void)transactionDidBegin:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

