//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBDashBoardPowerChangeObserver : NSObject
{
    BOOL _connectedToPower;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic, getter=isConnectedToPower) BOOL connectedToPower; // @synthesize connectedToPower=_connectedToPower;
- (void).cxx_destruct;
- (void)setIsConnectedToPower:(BOOL)arg1;
- (void)update;
- (id)initWithBlock:(CDUnknownBlockType)arg1;

@end

