//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSString, SBAppSwitcherSettings, SBDeckSwitcherIconImageContainerView, SBDeckSwitcherPageView, SBDisplayItem, UILabel, UILongPressGestureRecognizer, UIScrollView, UITapGestureRecognizer;

@interface SBDeckSwitcherItemContainer : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    SBDeckSwitcherPageView *_pageView;
    SBDisplayItem *_displayItem;
    id <SBDeckSwitcherItemContainerDelegate> _delegate;
    UIScrollView *_verticalScrollView;
    UIView *_iconAndLabelContainer;
    SBDeckSwitcherIconImageContainerView *_iconImageView;
    UILabel *_iconTitle;
    float _killVelocity;
    float _contentCornerRadiusProgress;
    float _contentBlurRadiusProgress;
    float _contentPageViewScale;
    float _titleOpacity;
    float _titleAndIconOpacity;
    UILongPressGestureRecognizer *_pressDownGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    SBAppSwitcherSettings *_settings;
    BOOL _disableBlurInputBoundsUpdatesForDismissal;
    BOOL _blurEnabled;
    float _lastBlurRadius;
    struct CGRect _lastBlurFrame;
    float _unobscuredMargin;
}

+ (float)iconSize;
+ (float)spacingBetweenEdgeAndIcon;
+ (float)spacingBetweenSnapshotAndIcon;
+ (float)spacingBetweenIconAndLabel;
+ (float)preferredRestingVisibleMarginForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) BOOL blurEnabled; // @synthesize blurEnabled=_blurEnabled;
@property(nonatomic) float unobscuredMargin; // @synthesize unobscuredMargin=_unobscuredMargin;
@property(nonatomic) float contentPageViewScale; // @synthesize contentPageViewScale=_contentPageViewScale;
@property(nonatomic) float titleAndIconOpacity; // @synthesize titleAndIconOpacity=_titleAndIconOpacity;
@property(nonatomic) float titleOpacity; // @synthesize titleOpacity=_titleOpacity;
@property(nonatomic) float contentBlurRadiusProgress; // @synthesize contentBlurRadiusProgress=_contentBlurRadiusProgress;
@property(nonatomic) float contentCornerRadiusProgress; // @synthesize contentCornerRadiusProgress=_contentCornerRadiusProgress;
@property(retain, nonatomic) SBDeckSwitcherPageView *pageView; // @synthesize pageView=_pageView;
@property(readonly, nonatomic) __weak id <SBDeckSwitcherItemContainerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
- (void).cxx_destruct;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)_handlePageViewPressDown:(id)arg1;
- (void)_handlePageViewTap:(id)arg1;
- (struct CGRect)_blurFrame;
- (void)_updateBlur;
- (void)_removeIconSubview;
- (void)_addIconSubview;
- (float)_scaleTransformFactor;
- (float)_inverseScaleTransformFactor;
- (void)_applyVisualStyleToSubviews;
- (float)_effectiveTitleAndIconOpacityConsideringKillProgress;
- (struct CGRect)_frameForIconTitle:(id)arg1;
- (struct CGRect)_frameForIconView;
- (struct CGRect)_frameForIconTitleViewContainer;
- (struct CGRect)_frameForPageView;
- (struct CGRect)_frameForScrollView;
- (struct CGAffineTransform)_transformForIconTitleViewContainer;
- (void)_ensureSubviewOrder;
- (void)layoutSubviews;
- (void)respondToBecomingInvisibleIfNecessary;
- (void)prepareToBecomeVisibleIfNecessary;
- (void)transitionDidEnd:(BOOL)arg1 forPresentation:(BOOL)arg2;
- (void)interactionDidEnd:(BOOL)arg1;
- (void)updateTransitionProgress:(float)arg1;
- (void)viewDismissing:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(float)arg3 forTransitionRequest:(id)arg4;
- (void)viewPresenting:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(float)arg3 forTransitionRequest:(id)arg4;
@property(nonatomic) struct CGRect shadowClippingFrame;
@property(nonatomic) BOOL shouldClipShadow;
@property(readonly, nonatomic) float killingProgress;
@property(nonatomic) float killGestureHysteresis;
@property(nonatomic) float darkeningAlpha;
- (id)_createScrollView;
- (id)initWithFrame:(struct CGRect)arg1 displayItem:(id)arg2 delegate:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

