//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSObject<OS_dispatch_semaphore>, SBIcon;

@interface SBDeleteIconAlertItem : SBAlertItem
{
    SBIcon *_icon;
    BOOL _checkedDocumentsInCloudState;
    BOOL _appHasDocumentsInCloud;
    BOOL _appHasDocumentsWithPendingUpdates;
    BOOL _askedUserAboutDocumentsInCloud;
    BOOL _askedUserAboutDocumentsWithPendingUpdates;
    BOOL _checkedForRelatedData;
    BOOL _finishedCheckingForRelatedData;
    BOOL _appHasHealthKitData;
    BOOL _appHasGameKitData;
    NSObject<OS_dispatch_semaphore> *_healthKitResponseSem;
}

- (void).cxx_destruct;
- (BOOL)_hasRelatedData;
- (void)_waitForRelatedDataResponsesIfNeeded;
- (void)_startCheckingForRelatedExternalDataIfNeeded;
- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)_checkDocumentsInCloudStateIfNeeded;
- (id)icon;
- (void)dealloc;
- (id)initWithIcon:(id)arg1;

@end

