//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBAppSwitcherPageViewDelegate.h"
#import "SBAppViewHostRequester.h"
#import "SBSwitcherAppViewWrapperPageContentViewDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SBDeckSwitcherPageView;

@interface SBDeckSwitcherPageViewProvider : NSObject <SBAppSwitcherPageViewDelegate, SBSwitcherAppViewWrapperPageContentViewDelegate, SBAppViewHostRequester>
{
    id <SBDeckSwitcherPageViewProviderDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_snapshotQueue;
    struct _NSRange _lastVisibleRange;
    SBDeckSwitcherPageView *_homeScreenPageView;
    NSMutableDictionary *_hostedApps;
    NSMutableDictionary *_appSnapshots;
    NSMutableDictionary *_switcherServiceViewControllerMap;
}

+ (BOOL)_useSnapshotsWhenPossible;
@property(nonatomic) __weak id <SBDeckSwitcherPageViewProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (int)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
- (struct CGSize)sizeForAppView:(id)arg1 representing:(id)arg2;
- (struct CGAffineTransform)contentViewTransformForPageView:(id)arg1;
- (int)resizingPolicyForPageView:(id)arg1;
- (id)_viewForRemoteAlert:(id)arg1 placeholder:(BOOL)arg2 displayItem:(id)arg3;
- (id)_viewForService:(id)arg1 displayItem:(id)arg2;
- (id)_snapshotViewForDisplayItem:(id)arg1 preferringDownscaledSnapshot:(BOOL)arg2 synchronously:(BOOL)arg3;
- (BOOL)_shouldHostAppDisplayItem:(id)arg1;
- (id)_contextHostingAppViewForDisplayItem:(id)arg1;
- (id)_homePageContentView;
- (void)_updateCachedPageViewsWithVisibleItemRange:(struct _NSRange)arg1 scrollDirection:(BOOL)arg2 allItems:(id)arg3;
- (unsigned int)_totalItemsForWhichToKeepAroundSnapshots;
- (BOOL)_isSnapshotDisplayItem:(id)arg1;
- (id)_containerViewController;
- (id)_initialLayoutState;
- (id)_initialDisplayItem;
- (struct CGSize)_contentSizeForDisplayItem:(id)arg1;
- (struct CGSize)_pageViewSizeForDisplayItem:(id)arg1;
- (int)_interfaceOrientation;
- (id)currentlyHostedDisplayItems;
- (void)updateCachedPageViewsWithVisibleItemRange:(struct _NSRange)arg1 scrollDirection:(BOOL)arg2 allItems:(id)arg3;
- (void)purgePageViewForDisplayItem:(id)arg1;
- (id)pageViewForDisplayItem:(id)arg1 synchronously:(BOOL)arg2;
- (id)init;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

