//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBProximitySensorManager, SBSceneManager;

@interface SBFaceContactExpectationManager : NSObject
{
    SBSceneManager *_sceneManager;
    SBProximitySensorManager *_proximitySensorManager;
    BOOL _faceExpected;
}

@property(nonatomic, setter=_setFaceExpected:) BOOL faceExpected; // @synthesize faceExpected=_faceExpected;
- (void).cxx_destruct;
- (id)_proximitySensorClientID;
- (BOOL)_frontmostSceneExpectsFaceContact;
- (void)updateFaceContactExpectation;
- (id)description;
- (id)initWithSceneManager:(id)arg1 proximitySensorManager:(id)arg2;
- (id)initWithSceneManager:(id)arg1;

@end

