//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBTreeNodeViewController.h"

#import "SBFolderControllerDelegate.h"
#import "SBFolderObserver.h"
#import "SBFolderViewDelegate.h"

@class NSArray, NSMapTable, NSString, NSTimer, SBFolder, SBFolderContainerView, SBFolderContext, SBFolderControllerAnimationContext, SBFolderControllerBackgroundView, SBFolderView, SBIcon, SBIconAnimator, SBIconViewMap, SBWindowSelfHostWrapper, _UILegibilitySettings;

@interface SBFolderController : SBTreeNodeViewController <SBFolderControllerDelegate, SBFolderObserver, SBFolderViewDelegate>
{
    SBIconViewMap *_viewMap;
    SBFolderContainerView *_containerView;
    SBFolderView *_contentView;
    SBFolderControllerBackgroundView *_backgroundView;
    SBWindowSelfHostWrapper *_statusBarWindowHostWrapper;
    BOOL _didAutoScroll;
    NSTimer *_autoScrollTimer;
    struct CGPoint _dragPausePoint;
    NSTimer *_dragPauseTimer;
    NSTimer *_closeFolderTimer;
    BOOL _grabbedIconHasEverEnteredFolderView;
    int _dropDestinationPageIndex;
    NSMapTable *_editingContextsByFolder;
    SBIconAnimator *_iconAnimator;
    BOOL _isOpen;
    BOOL _isEditing;
    BOOL _isAnimating;
    BOOL _active;
    BOOL _rotating;
    BOOL _wasExpandedAfterLastSizeTransition;
    id <SBFolderControllerDelegate> _folderDelegate;
    SBFolder *_folder;
    int _orientation;
    _UILegibilitySettings *_legibilitySettings;
    SBIcon *_grabbedIcon;
    SBFolderContext *_lastContext;
    SBFolderControllerAnimationContext *_animationContext;
}

+ (Class)listViewClass;
@property(retain, nonatomic) SBFolderControllerAnimationContext *animationContext; // @synthesize animationContext=_animationContext;
@property(retain, nonatomic) SBFolderContext *lastContext; // @synthesize lastContext=_lastContext;
@property(retain, nonatomic) SBIcon *grabbedIcon; // @synthesize grabbedIcon=_grabbedIcon;
@property(nonatomic) BOOL wasExpandedAfterLastSizeTransition; // @synthesize wasExpandedAfterLastSizeTransition=_wasExpandedAfterLastSizeTransition;
@property(nonatomic, getter=isRotating) BOOL rotating; // @synthesize rotating=_rotating;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
@property(readonly, nonatomic) SBFolderView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(readonly, nonatomic) SBIconViewMap *viewMap; // @synthesize viewMap=_viewMap;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) SBFolder *folder; // @synthesize folder=_folder;
@property(nonatomic) __weak id <SBFolderControllerDelegate> folderDelegate; // @synthesize folderDelegate=_folderDelegate;
@property(nonatomic) int dropDestinationPageIndex; // @synthesize dropDestinationPageIndex=_dropDestinationPageIndex;
@property(nonatomic, getter=isAnimating) BOOL animating; // @synthesize animating=_isAnimating;
@property(readonly, nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_isEditing;
@property(nonatomic, getter=isOpen) BOOL open; // @synthesize open=_isOpen;
- (void).cxx_destruct;
- (void)handleReachabilityActivated:(BOOL)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)folderControllerDidReceiveCancelReachabilityAction:(id)arg1;
- (void)folderViewDidReceiveCancelReachabilityAction:(id)arg1;
- (void)folder:(id)arg1 didRemoveLists:(id)arg2 atIndexes:(id)arg3;
- (void)folder:(id)arg1 didAddList:(id)arg2;
- (void)_noteFolderListsDidChange;
- (void)folderViewShouldBeginEditing:(id)arg1;
- (void)folderViewShouldClose:(id)arg1 withPinchGesture:(id)arg2;
- (void)folderViewDidEndScrolling:(id)arg1;
- (void)folderViewWillBeginScrolling:(id)arg1;
- (void)folderView:(id)arg1 currentPageIndexDidChange:(int)arg2;
- (Class)iconListViewClassForFolderView:(id)arg1;
- (void)folderControllerDidEndScrolling:(id)arg1;
- (void)folderControllerShouldBeginEditing:(id)arg1;
- (void)folderControllerShouldClose:(id)arg1 withPinchGesture:(id)arg2;
- (void)folderController:(id)arg1 draggedIconShouldDropFromListView:(id)arg2;
- (BOOL)folderController:(id)arg1 draggedIconMightDropFromListView:(id)arg2;
- (BOOL)folderController:(id)arg1 draggedIconDidMoveFromListView:(id)arg2 toListView:(id)arg3;
- (BOOL)folderController:(id)arg1 draggedIconDidPauseAtLocation:(struct CGPoint)arg2 inListView:(id)arg3;
- (Class)controllerClassForFolder:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (struct UIEdgeInsets)statusBarInsetsForOrientation:(int)arg1;
- (void)prepareToLaunchTappedIcon:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)currentIndexPath;
- (void)restoreExpandedIndexPath:(id)arg1;
- (BOOL)shouldOpenFolderIcon:(id)arg1 atIndexPath:(id)arg2;
- (void)popFolderAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)pushFolderIcon:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)prepareToClose;
- (void)prepareToOpen;
- (BOOL)_iconAppearsOnCurrentPage:(id)arg1;
- (BOOL)_listIndexIsVisible:(unsigned int)arg1;
- (unsigned int)_depth;
- (id)_newAnimatorForZoomUp:(BOOL)arg1;
- (void)_clearIconAnimator;
- (void)unscatterAnimated:(BOOL)arg1 afterDelay:(double)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)noteGrabbedIcon:(id)arg1 locationDidChangeWithTouch:(id)arg2;
- (void)noteGrabbedIconDidChange:(id)arg1;
- (void)noteUserIsInteractingWithIcons;
- (void)_updateAutoScrollForTouch:(id)arg1;
@property(readonly, nonatomic) struct CGRect _autoscrollExclusionRegion;
- (void)_cancelAutoScroll;
- (void)_doAutoScrollByPageCount:(int)arg1;
- (void)_scrollRight:(id)arg1;
- (void)_scrollLeft:(id)arg1;
- (void)_updateDragPauseForTouch:(id)arg1;
- (void)_dragPauseTimerFired:(id)arg1;
- (BOOL)_canDropIconInListView:(id)arg1;
- (void)_resetDragPauseTimerForPoint:(struct CGPoint)arg1 inIconListView:(id)arg2;
- (void)_cancelDragPauseTimer;
- (void)_updateDropDestinationForTouch:(id)arg1;
- (void)_updateCloseFolderForTouch:(id)arg1;
- (void)_setCloseFolderTimerIfNecessary;
- (void)_closeFolderTimerFired;
- (void)_cancelCloseFolderTimer;
- (void)_cancelAllInteractionTimers;
- (BOOL)_allowUserInteraction;
- (unsigned int)_indexOfIconListForIcon:(id)arg1;
- (void)_compactFolder;
- (id)_addEmptyListForce:(BOOL)arg1;
- (id)addEmptyListView;
- (void)layoutIconLists:(double)arg1 domino:(BOOL)arg2 forceRelayout:(BOOL)arg3;
- (void)_resetIconLists;
- (void)prepareToTearDown;
- (id)_expandedIndexPathForCurrentPageIndex;
- (void)_updateStateOfAssociatedController:(id)arg1 animated:(BOOL)arg2;
- (void)_updateAssociatedControllerStateAnimated:(BOOL)arg1;
- (void)fadeContentForMinificationFraction:(float)arg1;
- (void)fadeContentForMagnificationFraction:(float)arg1;
- (void)setDockVerticalStretch:(float)arg1;
- (void)setDockOffscreenFraction:(float)arg1;
- (id)dockListView;
- (BOOL)hasDock;
- (id)targetIconViewForExpandUnexpandTransitionOfFolderWithIcon:(id)arg1;
- (BOOL)isDisplayingIcon:(id)arg1;
- (id)iconListViewContainingIcon:(id)arg1;
- (id)iconListViewForTouch:(id)arg1;
- (id)iconListViewAtIndex:(unsigned int)arg1;
- (BOOL)doesPageContainIconListView:(int)arg1;
- (id)currentIconListView;
@property(readonly, nonatomic) unsigned int iconListViewCount;
@property(readonly, copy, nonatomic) NSArray *iconListViews;
- (BOOL)_restoreFromContext:(id)arg1;
- (id)_createContext;
- (id)folderControllerForFolder:(id)arg1;
- (id)deepestFolderController;
@property(readonly, nonatomic) __weak SBFolderController *outerFolderController;
@property(readonly, nonatomic) SBFolderController *innerFolderController;
- (void)_configureForInnerFolderController:(id)arg1;
- (void)setCurrentPageIndexToListContainingIcon:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setCurrentPageIndexToListContainingIcon:(id)arg1 animated:(BOOL)arg2;
- (BOOL)setCurrentPageIndex:(int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)setCurrentPageIndex:(int)arg1 animated:(BOOL)arg2;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
@property(readonly, nonatomic) int currentPageIndex;
@property(readonly, nonatomic, getter=isScrolling) BOOL scrolling;
- (id)_iconPageIndicatorImageSetCache;
- (Class)_contentViewClass;
- (void)_endHostingStatusBarWindow;
- (void)_beginHostingStatusBarWindow;
- (void)removeViewFromHierarchyForChildTreeNodeViewController:(id)arg1;
- (void)addViewToHierarchyForChildTreeNodeViewController:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withContainingExpandedIndexPath:(id)arg2 transitionCoordinator:(id)arg3;
- (void)treeNodeViewController:(id)arg1 willPerformOperation:(int)arg2 fromViewController:(id)arg3 fromIndexPath:(id)arg4 toViewController:(id)arg5 toIndexPath:(id)arg6 withTransitionCoordinator:(id)arg7;
- (id)treeNodeViewController:(id)arg1 destinationExpandedIndexPathForTargetIndexPath:(id)arg2;
- (id)treeNodeViewController:(id)arg1 targetExpandedIndexPathForProposedIndexPath:(id)arg2;
- (id)effectiveExpandedIndexPath;
- (id)treeNodeViewController:(id)arg1 viewControllerForChildTreeNode:(id)arg2 atIndexPath:(id)arg3;
- (void)loadView;
- (id)view;
- (void)invalidate;
- (void)_invalidate;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3 context:(id)arg4;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

