//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBFolderView;

@interface SBFolderContainerView : UIView
{
    float _statusBarHeight;
    SBFolderView *_folderView;
    SBFolderContainerView *_childFolderContainerView;
    UIView *_backgroundView;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) SBFolderView *folderView; // @synthesize folderView=_folderView;
@property(nonatomic) float statusBarHeight; // @synthesize statusBarHeight=_statusBarHeight;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGRect)_frameForFolderView:(id)arg1;
@property(retain, nonatomic) SBFolderContainerView *childFolderContainerView;
- (id)initWithFolderView:(id)arg1 statusBarHeight:(float)arg2;

@end

