//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBClient;

@interface SBHarmonyController : NSObject
{
    CBClient *_client;
    BOOL _supportsWhitePointAdaptation;
    BOOL _supportsBlueLightReduction;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) BOOL supportsBlueLightReduction; // @synthesize supportsBlueLightReduction=_supportsBlueLightReduction;
@property(readonly, nonatomic) BOOL supportsWhitePointAdaptation; // @synthesize supportsWhitePointAdaptation=_supportsWhitePointAdaptation;
- (void).cxx_destruct;
- (void)transitionFromWhitePointAdaptivityStyleWithStyles:(id)arg1 toWhitePointAdaptivityStyleWithStyles:(id)arg2 fromPercentage:(double)arg3 toPercentage:(double)arg4 animationSettings:(id)arg5;
- (void)setWhitePointAdaptivityStyleWithStyles:(id)arg1 animationSettings:(id)arg2;
- (void)setWhitePointAdaptivityStyle:(int)arg1 animationSettings:(id)arg2;
@property(nonatomic) int whitePointAdaptivityStyle;
@property(nonatomic, getter=isWhitePointAdaptationEnabled) BOOL whitePointAdaptationEnabled;
- (id)init;
- (void)setWhitePointAdaptationStrength:(float)arg1 forWhitePointAdaptivityStyle:(int)arg2;
- (float)whitePointAdaptationStrengthForWhitePointAdaptivityStyle:(int)arg1;

@end

