//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBViewControllerInteractiveTransitioning.h"
#import "UIInteractionProgressObserver.h"

@class NSString, UIInteractionProgress;

@interface SBHintInteractor : NSObject <UIInteractionProgressObserver, SBViewControllerInteractiveTransitioning>
{
    id <SBViewControllerContextTransitioning> _transitionContext;
    CDStruct_33193670 _hintInterval;
    float _smoothedPercentComplete;
    UIInteractionProgress *_interactionProgress;
}

@property(readonly, nonatomic) UIInteractionProgress *interactionProgress; // @synthesize interactionProgress=_interactionProgress;
- (void).cxx_destruct;
- (void)_updateInteractionPercentComplete:(float)arg1;
- (void)interactionProgress:(id)arg1 didEnd:(BOOL)arg2;
- (void)interactionProgressDidUpdate:(id)arg1;
- (BOOL)supportsRestarting;
- (void)finishInteractiveTransition;
- (void)cancelTransition;
- (void)updateTransition:(float)arg1;
- (void)startInteractiveTransition:(id)arg1;
@property(readonly, nonatomic) float maxHintProgress;
- (id)initWithInteractionProgress:(id)arg1 maxHintProgress:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) BOOL wantsInteractiveStart;

@end

