//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBIconAnimatorDelegate.h"
#import "SBViewControllerInteractiveAnimatedTransitioning.h"

@class NSString, SBFolderController, SBIconAnimationSettings, SBIconAnimator, SBTreeNodeViewController;

@interface SBHomeScreenIconTransitionAnimator : NSObject <SBIconAnimatorDelegate, SBViewControllerInteractiveAnimatedTransitioning>
{
    id <SBViewControllerContextTransitioning> _transitionContext;
    unsigned int _transitionToken;
    SBIconAnimationSettings *_currentSettings;
    unsigned int _currentOperation;
    BOOL _receivedFirstInteractiveUpdate;
    BOOL _needsTransitionTokenIncrementOnNextUpdate;
    SBIconAnimator *_iconAnimator;
    SBFolderController *_folderController;
    SBTreeNodeViewController *_childViewController;
    unsigned int _operation;
    id <SBHomeScreenIconTransitionAnimatorDelegate> _delegate;
    double _initialDelay;
}

@property(nonatomic) __weak id <SBHomeScreenIconTransitionAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double initialDelay; // @synthesize initialDelay=_initialDelay;
@property(readonly, nonatomic) unsigned int operation; // @synthesize operation=_operation;
@property(readonly, nonatomic) SBTreeNodeViewController *childViewController; // @synthesize childViewController=_childViewController;
@property(readonly, nonatomic) SBFolderController *folderController; // @synthesize folderController=_folderController;
@property(readonly, nonatomic) SBIconAnimator *iconAnimator; // @synthesize iconAnimator=_iconAnimator;
- (void).cxx_destruct;
@property(readonly, nonatomic) SBIconAnimationSettings *currentSettings;
- (void)iconAnimatorWasInvalidated:(id)arg1;
- (void)animationEnded:(BOOL)arg1;
- (BOOL)supportsRestarting;
- (float)percentComplete;
- (void)finishInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)updateTransition:(id)arg1 withPercentComplete:(float)arg2;
- (void)cancelTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)animateTransition:(id)arg1;
- (id)transitionAnimationFactory:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)reverse;
- (void)restart;
- (void)cancel;
@property(readonly, nonatomic) unsigned int currentOperation;
@property(readonly, nonatomic, getter=wasRestarted) BOOL restarted;
@property(readonly, nonatomic, getter=isCancelled) BOOL cancelled;
- (id)initWithIconAnimator:(id)arg1 folderController:(id)arg2 childViewController:(id)arg3 operation:(unsigned int)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

