//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, SBFolderController, SBFolderControllerAnimationContext, SBIconAnimationSettings, SBValueConvergenceAnimator, UIView;

@interface SBIconAnimator : NSObject
{
    float _fraction;
    float _hintFraction;
    BOOL _startAnimationAfterRotationEnds;
    BOOL _windowIsRotating;
    BOOL _cleanedUp;
    BOOL _animating;
    NSMutableArray *_pendedAnimationContexts;
    SBFolderControllerAnimationContext *_animationContext;
    NSString *_instanceIdentifier;
    BOOL _invalidated;
    id <SBIconAnimatorDelegate> _delegate;
    SBIconAnimationSettings *_settings;
    SBValueConvergenceAnimator *_hintAnimator;
    UIView *_backgroundDarkeningView;
    SBFolderController *_folderController;
}

@property(readonly, nonatomic) SBFolderControllerAnimationContext *animationContext; // @synthesize animationContext=_animationContext;
@property(readonly, nonatomic) SBFolderController *folderController; // @synthesize folderController=_folderController;
@property(retain, nonatomic) UIView *backgroundDarkeningView; // @synthesize backgroundDarkeningView=_backgroundDarkeningView;
@property(retain, nonatomic) SBValueConvergenceAnimator *hintAnimator; // @synthesize hintAnimator=_hintAnimator;
@property(nonatomic) float hintFraction; // @synthesize hintFraction=_hintFraction;
@property(nonatomic) BOOL invalidated; // @synthesize invalidated=_invalidated;
@property(retain, nonatomic) SBIconAnimationSettings *settings; // @synthesize settings=_settings;
@property(nonatomic) __weak id <SBIconAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_windowFinishedRotating;
- (void)_invalidateCompletions;
- (void)_allowRotationOnMainWindowIfNecessary:(BOOL)arg1;
- (void)_animateToFraction:(float)arg1 afterDelay:(double)arg2 withSharedCompletion:(CDUnknownBlockType)arg3;
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)arg1;
- (void)_prepareAnimation;
- (BOOL)_isDelayedForRotation;
- (void)_animateToFractionFromContext:(id)arg1;
- (void)_animateToFractionFromPendingContexts;
- (void)cleanup;
- (void)animateToFraction:(float)arg1 afterDelay:(double)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)hintToFraction:(float)arg1;
@property(readonly, nonatomic, getter=isAnimating) BOOL animating;
@property(nonatomic) float fraction;
- (void)prepare;
- (id)centralAnimationFactory;
@property(readonly, nonatomic) UIView *referenceView;
@property(readonly, nonatomic, getter=isPastPointOfNoReturn) BOOL pastPointOfNoReturn;
- (void)dealloc;
- (id)initWithFolderController:(id)arg1;

@end

