//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderContainerView.h"

@interface SBIconContentView : SBFolderContainerView
{
    int _orientation;
}

@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
- (void)didAddSubview:(id)arg1;
- (id)initWithOrientation:(int)arg1 statusBarHeight:(float)arg2;

@end

