//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBIdleTimerDelegate.h"

@class NSMutableSet, NSString, SBDashBoardIdleTimerFactory;

@interface SBIdleTimerEventPublisher : NSObject <SBIdleTimerDelegate>
{
    id <SBDashBoardEventHandling> _eventHandler;
    SBDashBoardIdleTimerFactory *_idleTimerFactory;
    id <SBIdleTimer> _idleTimer;
    NSMutableSet *_disabledAssertions;
}

- (void).cxx_destruct;
- (void)idleTimerDidWarn:(id)arg1;
- (void)idleTimerDidReceiveUserEvent:(id)arg1;
- (void)idleTimerDidExpire:(id)arg1;
- (void)idleTimerDidRefresh:(id)arg1;
- (BOOL)isEnabled;
- (BOOL)isDisabledAssertionActiveForReason:(id)arg1;
- (void)removeDisabledAssertionReason:(id)arg1;
- (void)addDisabledAssertionReason:(id)arg1;
- (void)updateWithIdleDimProvider:(id)arg1 reason:(id)arg2;
- (void)reset;
- (id)initWithEventHandler:(id)arg1 idleTimerFactory:(id)arg2;
- (id)initWithEventHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

