//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSString, SBBootDefaults, UMUser;

@interface SBInitialRestartState : NSObject <BSDescriptionProviding>
{
    BOOL _isAuthenticated;
    BOOL _isInLostMode;
    BOOL _isBlocked;
    BOOL _hasPasscodeSet;
    BOOL _requiresSetup;
    BOOL _shouldNeverLock;
    UMUser *_currentUser;
    SBBootDefaults *_bootDefaults;
}

@property(retain, nonatomic) SBBootDefaults *bootDefaults; // @synthesize bootDefaults=_bootDefaults;
@property(retain, nonatomic) UMUser *currentUser; // @synthesize currentUser=_currentUser;
@property(nonatomic) BOOL shouldNeverLock; // @synthesize shouldNeverLock=_shouldNeverLock;
@property(nonatomic) BOOL hasPasscodeSet; // @synthesize hasPasscodeSet=_hasPasscodeSet;
@property(nonatomic) BOOL requiresSetup; // @synthesize requiresSetup=_requiresSetup;
@property(nonatomic, getter=isBlocked) BOOL blocked; // @synthesize blocked=_isBlocked;
@property(nonatomic, getter=isInLostMode) BOOL inLostMode; // @synthesize inLostMode=_isInLostMode;
@property(nonatomic, getter=isAuthenticated) BOOL authenticated; // @synthesize authenticated=_isAuthenticated;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

