//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBLegibilitySettings : SBUISettings
{
    float _slideToUnlockDarkShadowStrength;
    float _slideToUnlockLightShadowStrength;
    float _appIconGrabberDarkShadowStrength;
    float _appIconGrabberLightShadowStrength;
    float _timeDarkShadowStrength;
    float _timeLightShadowStrength;
    float _dateDarkShadowStrength;
    float _dateLightShadowStrength;
    float _statusTextDarkShadowStrength;
    float _statusTextLightShadowStrength;
    float _iconLabelDarkShadowStrength;
    float _iconLabelLightShadowStrength;
    float _folderTitleDarkShadowStrength;
    float _folderTitleLightShadowStrength;
    float _timerTextDarkShadowStrength;
    float _timerTextLightShadowStrength;
    float _timerDialDarkShadowStrength;
    float _timerDialLightShadowStrength;
    float _logoutButtonGlyphDarkShadowStrength;
    float _logoutButtonGlyphLightShadowStrength;
    float _logoutButtonTextDarkShadowStrength;
    float _logoutButtonTextLightShadowStrength;
    float _userPictureDarkShadowStrength;
    float _userPictureLightShadowStrength;
}

+ (id)settingsControllerModule;
@property float userPictureLightShadowStrength; // @synthesize userPictureLightShadowStrength=_userPictureLightShadowStrength;
@property float userPictureDarkShadowStrength; // @synthesize userPictureDarkShadowStrength=_userPictureDarkShadowStrength;
@property float logoutButtonTextLightShadowStrength; // @synthesize logoutButtonTextLightShadowStrength=_logoutButtonTextLightShadowStrength;
@property float logoutButtonTextDarkShadowStrength; // @synthesize logoutButtonTextDarkShadowStrength=_logoutButtonTextDarkShadowStrength;
@property float logoutButtonGlyphLightShadowStrength; // @synthesize logoutButtonGlyphLightShadowStrength=_logoutButtonGlyphLightShadowStrength;
@property float logoutButtonGlyphDarkShadowStrength; // @synthesize logoutButtonGlyphDarkShadowStrength=_logoutButtonGlyphDarkShadowStrength;
@property float timerDialLightShadowStrength; // @synthesize timerDialLightShadowStrength=_timerDialLightShadowStrength;
@property float timerDialDarkShadowStrength; // @synthesize timerDialDarkShadowStrength=_timerDialDarkShadowStrength;
@property float timerTextLightShadowStrength; // @synthesize timerTextLightShadowStrength=_timerTextLightShadowStrength;
@property float timerTextDarkShadowStrength; // @synthesize timerTextDarkShadowStrength=_timerTextDarkShadowStrength;
@property float folderTitleLightShadowStrength; // @synthesize folderTitleLightShadowStrength=_folderTitleLightShadowStrength;
@property float folderTitleDarkShadowStrength; // @synthesize folderTitleDarkShadowStrength=_folderTitleDarkShadowStrength;
@property float iconLabelLightShadowStrength; // @synthesize iconLabelLightShadowStrength=_iconLabelLightShadowStrength;
@property float iconLabelDarkShadowStrength; // @synthesize iconLabelDarkShadowStrength=_iconLabelDarkShadowStrength;
@property float statusTextLightShadowStrength; // @synthesize statusTextLightShadowStrength=_statusTextLightShadowStrength;
@property float statusTextDarkShadowStrength; // @synthesize statusTextDarkShadowStrength=_statusTextDarkShadowStrength;
@property float dateLightShadowStrength; // @synthesize dateLightShadowStrength=_dateLightShadowStrength;
@property float dateDarkShadowStrength; // @synthesize dateDarkShadowStrength=_dateDarkShadowStrength;
@property float timeLightShadowStrength; // @synthesize timeLightShadowStrength=_timeLightShadowStrength;
@property float timeDarkShadowStrength; // @synthesize timeDarkShadowStrength=_timeDarkShadowStrength;
@property float appIconGrabberLightShadowStrength; // @synthesize appIconGrabberLightShadowStrength=_appIconGrabberLightShadowStrength;
@property float appIconGrabberDarkShadowStrength; // @synthesize appIconGrabberDarkShadowStrength=_appIconGrabberDarkShadowStrength;
@property float slideToUnlockLightShadowStrength; // @synthesize slideToUnlockLightShadowStrength=_slideToUnlockLightShadowStrength;
@property float slideToUnlockDarkShadowStrength; // @synthesize slideToUnlockDarkShadowStrength=_slideToUnlockDarkShadowStrength;
- (float)userPictureStrengthForStyle:(int)arg1;
- (float)logoutButtonTextStrengthForStyle:(int)arg1;
- (float)logoutButtonGlyphStrengthForStyle:(int)arg1;
- (float)timerDialStrengthForStyle:(int)arg1;
- (float)timerTextStrengthForStyle:(int)arg1;
- (float)folderTitleStrengthForStyle:(int)arg1;
- (float)iconLabelStrengthForStyle:(int)arg1;
- (float)statusTextStrengthForStyle:(int)arg1;
- (float)dateStrengthForStyle:(int)arg1;
- (float)timeStrengthForStyle:(int)arg1;
- (float)appIconGrabberStrengthForStyle:(int)arg1;
- (float)slideToUnlockStrengthForStyle:(int)arg1;
- (void)setDefaultValues;

@end

