//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertToAppsWorkspaceTransaction.h"

@class SBFAuthenticationAssertion, SBLockScreenViewControllerBase;

@interface SBLockScreenToAppsWorkspaceTransaction : SBAlertToAppsWorkspaceTransaction
{
    SBFAuthenticationAssertion *_siriAuthenticationAssertion;
    SBLockScreenViewControllerBase *_lockScreenViewController;
    BOOL _hidKeyboardForTransition;
    BOOL _updateStatusBarForLockTeardown;
}

- (void).cxx_destruct;
- (id)_animationToApplications;
- (id)_animationToSpringBoard;
- (BOOL)_shouldAnimateTransition;
- (void)_prepareApplicationsForActivationAnimated:(BOOL)arg1;
- (BOOL)_shouldUpdateUnderLockStateForForegroundScenes;
- (void)_performPreAnimationTasksWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)_hasPreAnimationTasks;
- (unsigned int)_serialOverlayPreDismissalOptions;
- (void)_beginTransition;
- (void)_didComplete;
- (void)_begin;
- (id)debugDescription;
- (id)initWithTransitionRequest:(id)arg1;

@end

