//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLockOverlayContext.h"

@interface SBLockScreenPluginOverlayContext : SBLockOverlayContext
{
    int _overlayStyle;
    BOOL _disabledMesaMatching;
}

@property(nonatomic) BOOL disabledMesaMatching; // @synthesize disabledMesaMatching=_disabledMesaMatching;
- (id)initWithPlugin:(id)arg1 lockScreenViewController:(id)arg2;

@end

