//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

@class SBLogoutDebugBlockingViewController, SBLogoutProgressAlertView, SBMultiUserDefaults, SBPlatformController, UMUser;

@interface SBLogoutProgressAlertViewController : SBAlert
{
    SBPlatformController *_platformController;
    SBMultiUserDefaults *_multiUserDefaults;
    id <SBLogoutProgressDataSource> _dataSource;
    UMUser *_user;
    SBLogoutProgressAlertView *_progressView;
    SBLogoutDebugBlockingViewController *_debugTasksViewController;
}

@property(readonly, nonatomic) UMUser *user; // @synthesize user=_user;
@property(nonatomic) __weak id <SBLogoutProgressDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)_updateData;
- (void)_updateLegibility;
- (id)_legibilitySettings;
- (void)_updateDebugTasksViewControllerSizeFromSize:(struct CGSize)arg1;
- (BOOL)_supportsDebugUI;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)deactivate;
- (void)activate;
- (int)customBackgroundStyle;
- (BOOL)wantsCustomBackgroundStyle;
- (BOOL)hasTranslucentBackground;
- (int)statusBarStyle;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)prepareForRestart;
- (void)refreshData;
- (id)initWithUserAccount:(id)arg1;

@end

