//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSSet, NSString, SBApplication, SBButtonDownGestureRecognizer, SBHomeHardwareButton, SBLockHardwareButtonActions, SBLongPressGestureRecognizer, SBTapGestureRecognizer, UIGestureRecognizer;

@interface SBLockHardwareButton : NSObject <UIGestureRecognizerDelegate>
{
    SBApplication *_lastLockButtonEventRecipient;
    SBLockHardwareButtonActions *_buttonActions;
    NSSet *_gestureRecognizers;
    SBButtonDownGestureRecognizer *_buttonDownGestureRecognizer;
    SBTapGestureRecognizer *_singlePressGestureRecognizer;
    SBLongPressGestureRecognizer *_longPressGestureRecognizer;
    UIGestureRecognizer *_screenshotGestureRecognizer;
    SBHomeHardwareButton *_homeHardwareButton;
}

@property(nonatomic) __weak SBHomeHardwareButton *homeHardwareButton; // @synthesize homeHardwareButton=_homeHardwareButton;
@property(nonatomic) __weak UIGestureRecognizer *screenshotGestureRecognizer; // @synthesize screenshotGestureRecognizer=_screenshotGestureRecognizer;
@property(retain, nonatomic) SBLongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) SBTapGestureRecognizer *singlePressGestureRecognizer; // @synthesize singlePressGestureRecognizer=_singlePressGestureRecognizer;
@property(retain, nonatomic) SBButtonDownGestureRecognizer *buttonDownGestureRecognizer; // @synthesize buttonDownGestureRecognizer=_buttonDownGestureRecognizer;
@property(retain, nonatomic) NSSet *gestureRecognizers; // @synthesize gestureRecognizers=_gestureRecognizers;
@property(retain, nonatomic) SBLockHardwareButtonActions *buttonActions; // @synthesize buttonActions=_buttonActions;
- (void).cxx_destruct;
- (BOOL)_shouldHandleVolumeAndPowerButtonPriorities;
- (void)_sendButtonUpEventToAppForRecognizer:(id)arg1;
- (BOOL)_tryToSendButtonDownEventsToAppForRecognizer:(id)arg1;
- (void)longPress:(id)arg1;
- (void)singlePress:(id)arg1;
- (void)buttonDown:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
@property(readonly, nonatomic) BOOL isButtonDown;
- (void)_createGestureRecognizers;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeHardwareButton:(id)arg2 buttonActions:(id)arg3 createGestures:(BOOL)arg4;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeHardwareButton:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

