//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "_UISettingsKeyObserver.h"

@class NSString, PCPersistentTimer, SBLockScreenSettings, SBMediaController;

@interface SBLockScreenNowPlayingController : NSObject <_UISettingsKeyObserver>
{
    SBMediaController *_mediaController;
    PCPersistentTimer *_disableTimer;
    SBLockScreenSettings *_testSettings;
    BOOL _enabled;
    int _currentState;
    id <SBLockScreenNowPlayingControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBLockScreenNowPlayingControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) int currentState; // @synthesize currentState=_currentState;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)_disableTimerFired;
- (void)_invalidateDisableTimer;
- (void)_startDisableTimer;
- (void)_updateToState:(int)arg1;
- (void)_updateNowPlayingPlugin;
- (void)_removeObservers;
- (void)_addObservers;
- (BOOL)isNowPlayingActive;
- (void)dealloc;
- (id)initWithMediaController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

