//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class NSString;

@interface SBLockScreenTestPluginSettings : SBUISettings
{
    BOOL _enablePlugin;
    BOOL _enableLostModePlugin;
    BOOL _restrictSiri;
    BOOL _restrictCamera;
    BOOL _restrictUnlock;
    BOOL _restrictLogout;
    BOOL _restrictTouchID;
    BOOL _restrictMediaControls;
    BOOL _restrictTodayCenter;
    BOOL _restrictControlCenter;
    BOOL _restrictNotificationCenter;
    BOOL _hideStatusBar;
    BOOL _hideTimeAndDate;
    BOOL _hideSubtitle;
    BOOL _disableOnUnlock;
    int _presentationStyle;
    int _backgroundStyle;
    int _notificationBehavior;
    NSString *_subtitleValue;
}

+ (id)settingsControllerModule;
@property BOOL disableOnUnlock; // @synthesize disableOnUnlock=_disableOnUnlock;
@property(retain) NSString *subtitleValue; // @synthesize subtitleValue=_subtitleValue;
@property BOOL hideSubtitle; // @synthesize hideSubtitle=_hideSubtitle;
@property BOOL hideTimeAndDate; // @synthesize hideTimeAndDate=_hideTimeAndDate;
@property BOOL hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
@property BOOL restrictNotificationCenter; // @synthesize restrictNotificationCenter=_restrictNotificationCenter;
@property BOOL restrictControlCenter; // @synthesize restrictControlCenter=_restrictControlCenter;
@property BOOL restrictTodayCenter; // @synthesize restrictTodayCenter=_restrictTodayCenter;
@property BOOL restrictMediaControls; // @synthesize restrictMediaControls=_restrictMediaControls;
@property BOOL restrictTouchID; // @synthesize restrictTouchID=_restrictTouchID;
@property BOOL restrictLogout; // @synthesize restrictLogout=_restrictLogout;
@property BOOL restrictUnlock; // @synthesize restrictUnlock=_restrictUnlock;
@property BOOL restrictCamera; // @synthesize restrictCamera=_restrictCamera;
@property BOOL restrictSiri; // @synthesize restrictSiri=_restrictSiri;
@property int notificationBehavior; // @synthesize notificationBehavior=_notificationBehavior;
@property int backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
@property int presentationStyle; // @synthesize presentationStyle=_presentationStyle;
@property BOOL enableLostModePlugin; // @synthesize enableLostModePlugin=_enableLostModePlugin;
@property BOOL enablePlugin; // @synthesize enablePlugin=_enablePlugin;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

