//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError, NSString;

@protocol SBLoginAppSceneHosterDelegate
- (void)sceneUpdatedRotationMode:(int)arg1;
- (void)sceneUpdatedStatusBarUserName:(NSString *)arg1;
- (void)sceneUpdatedIdleTimerMode:(int)arg1;
- (void)sceneDeactivatedWithError:(NSError *)arg1;
@end

