//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBLockHardwareButtonActions : NSObject
{
    BOOL _didPlayLockSound;
    BOOL _dontLockOnNextLockUp;
    BOOL _fadeOutInProgressFromLockButtonWhileUnlocked;
    BOOL _undidFadeOutFromLockButton;
    BOOL _useDashBoard;
    BOOL _isButtonDown;
}

@property(readonly, nonatomic) BOOL isButtonDown; // @synthesize isButtonDown=_isButtonDown;
- (void)_playLockSound;
- (void)performSinglePressAction;
- (BOOL)performButtonUpPreActions;
- (void)performLongPressActions;
- (void)performButtonDownActions;
- (BOOL)performButtonDownPreActions;
- (id)init;

@end

