//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSTransactionObserver.h"
#import "SBGrabberTongueDelegate.h"
#import "SBSceneResizeSnakebiteGestureRecognizerDelegate.h"
#import "SBSystemGestureRecognizerDelegate.h"

@class NSMutableDictionary, NSString, NSUUID, SBAppResizeGestureWorkspaceTransaction, SBGrabberTongue, SBMainDisplaySceneLayoutViewController, SBSceneResizeSnakebiteGestureRecognizer, SBSideAppSlideGestureWorkspaceTransaction, UILongPressGestureRecognizer, UIView;

@interface SBMainDisplaySceneLayoutGestureManager : NSObject <SBSystemGestureRecognizerDelegate, SBSceneResizeSnakebiteGestureRecognizerDelegate, BSTransactionObserver, SBGrabberTongueDelegate>
{
    SBMainDisplaySceneLayoutViewController *_sceneViewController;
    SBGrabberTongue *_sideAppGrabberTongue;
    SBGrabberTongue *_sideSwitcherGrabberTongue;
    UIView *_adornmentView;
    BOOL _sideAppRevealGestureIsActive;
    BOOL _sideSwitcherRevealGestureIsActive;
    BOOL _sideSwitcherRevealGestureAsOverlayIsActive;
    struct CGRect _effectiveKeyboardFrame;
    NSUUID *_lastSideAppRevealGestureTransactionRequestUUID;
    NSUUID *_lastSideSwitcherRevealGestureTransactionRequestUUID;
    NSMutableDictionary *_transactionRequestUUIDToRevealGestureSuccess;
    SBSideAppSlideGestureWorkspaceTransaction *_currentSideAppRevealWorkspaceTransaction;
    SBSideAppSlideGestureWorkspaceTransaction *_currentSideSwitcherRevealWorkspaceTransaction;
    SBSceneResizeSnakebiteGestureRecognizer *_resizeGestureRecognizer;
    SBAppResizeGestureWorkspaceTransaction *_resizeGestureTransaction;
    UILongPressGestureRecognizer *_sideSwitcherPressGestureRecognizer;
}

@property(readonly, nonatomic) UILongPressGestureRecognizer *sideSwitcherPressGestureRecognizer; // @synthesize sideSwitcherPressGestureRecognizer=_sideSwitcherPressGestureRecognizer;
@property(retain, nonatomic) SBAppResizeGestureWorkspaceTransaction *resizeGestureTransaction; // @synthesize resizeGestureTransaction=_resizeGestureTransaction;
@property(readonly, nonatomic) SBSceneResizeSnakebiteGestureRecognizer *resizeGestureRecognizer; // @synthesize resizeGestureRecognizer=_resizeGestureRecognizer;
@property(readonly, nonatomic) SBMainDisplaySceneLayoutViewController *sceneViewController; // @synthesize sceneViewController=_sceneViewController;
- (void).cxx_destruct;
- (void)_keyboardFrameDidChange:(id)arg1;
- (BOOL)sceneResizeGestureRecognizerShouldOnlyRecognizeForSingleTouch:(id)arg1;
- (BOOL)sceneResizeGestureRecognizer:(id)arg1 shouldWaitForInvalidSingleTouchToBecomeValidWithDistanceFromDivider:(float)arg2;
- (float)verticalCenterOfSingleTouchRegionForSceneResizeGestureRecognizer:(id)arg1;
- (float)minimumDistanceForSingleTouchForSceneResizeGestureRecognizer:(id)arg1;
- (double)minimumDurationForSingleTouchForSceneResizeGestureRecognizer:(id)arg1;
- (int)interfaceOrientationForSceneResizeGestureRecognizer:(id)arg1;
- (float)heightOfPinningAreaInDividerForSceneResizeGestureRecognizer:(id)arg1;
- (float)heightOfSingleTapAreaInDividerForSceneResizeGestureRecognizer:(id)arg1;
- (float)sceneResizeGestureRecognizer:(id)arg1 viewOffsetForLocation:(float)arg2;
- (float)sceneResizeGestureRecognizer:(id)arg1 locationForViewOffset:(float)arg2;
- (float)locationOfDividerForSceneResizeGestureRecognizer:(id)arg1;
- (void)_startResizeTransactionWithLabel:(id)arg1 checkGestureStatus:(BOOL)arg2;
- (void)_resizeGestureBegan;
- (void)_resizeGestureDidUpdate:(id)arg1;
- (void)transactionDidComplete:(id)arg1;
- (void)transactionDidBegin:(id)arg1;
- (void)_setLastSideAppRevealGestureTransactionRequestUUID:(id)arg1;
- (void)_setLastSideSwitcherRevealGestureTransactionRequestUUID:(id)arg1;
- (void)_setCurrentSideSwitcherRevealTransaction:(id)arg1;
- (void)_setCurrentSideAppRevealTransaction:(id)arg1;
- (int)_sidePullGestureSucceededForRequestID:(id)arg1;
- (void)_sideSwitcherLongPress:(id)arg1;
- (void)_sideSwitcherRevealGestureUpdatedWithDistance:(float)arg1;
- (void)_sideSwitcherRevealGestureBegan;
- (double)_effectiveValue:(double)arg1;
- (void)_finishSideSwitcherRevealGestureWithVelocity:(float)arg1 distance:(float)arg2;
- (void)_activateSideSwitcherViewWithInitialDistance:(float)arg1;
- (float)_progressForSideAppTransitionWithNewDistance:(float)arg1;
- (void)_sideAppRevealGestureUpdatedWithDistance:(float)arg1;
- (void)_sideAppRevealGestureBeganForActivation:(BOOL)arg1 ofSideSwitcher:(BOOL)arg2;
- (void)_finishSideAppRevealGestureWithVelocity:(float)arg1 distance:(float)arg2 forActivation:(BOOL)arg3;
- (void)_activateSideAppViewWithInitialPosition:(float)arg1 forActivation:(BOOL)arg2;
- (void)grabberTongueWillPresent:(id)arg1;
- (void)grabberTongueCanceledPulling:(id)arg1 withDistance:(float)arg2 andVelocity:(float)arg3;
- (void)grabberTongueEndedPulling:(id)arg1 withDistance:(float)arg2 andVelocity:(float)arg3;
- (void)grabberTongueUpdatedPulling:(id)arg1 withDistance:(float)arg2 andVelocity:(float)arg3;
- (void)grabberTongueBeganPulling:(id)arg1 withDistance:(float)arg2 andVelocity:(float)arg3;
- (BOOL)grabberTongueRequiredForWholeEdge:(id)arg1;
- (BOOL)grabberTongueRequiredOutsideGrabberFreeRegion:(id)arg1;
- (BOOL)grabberTongueOrPullEnabled:(id)arg1;
- (float)grabberTongueWidthOfActiveEdge:(id)arg1;
- (float)grabberTongueWidthOfGrabberFreeRegion:(id)arg1;
- (float)grabberTongueCenterOnEdge:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)_disableGestureWithTypeForCommonReasons:(unsigned int)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (id)viewForSystemGestureRecognizer:(id)arg1;
- (BOOL)sideSwitcherRevealGestureActive;
- (BOOL)anyLayoutGestureWaitingToComplete;
- (BOOL)anyLayoutGestureActive;
- (id)sideSwitcherRevealGesture;
- (BOOL)dismissGrabbersWithStyle:(int)arg1 animated:(BOOL)arg2;
- (void)installAccessoriesInView:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithSceneLayoutViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

