//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SBBestAppSuggestion, SBDisplayItem, SBMainDisplayLayoutState, SBWorkspaceTransitionRequest;

@protocol SBMainAppSwitcherContentViewControlling <NSObject>
+ (float)snapshotScale;
@property(retain, nonatomic) SBBestAppSuggestion *bestAppSuggestion;
@property(nonatomic) id <SBMainAppSwitcherContentViewControllerDelegate> delegate;
@property(copy, nonatomic) NSArray *displayItems;
@property(retain, nonatomic, setter=_setInitialLayoutState:) SBMainDisplayLayoutState *_initialLayoutState;
@property(copy, nonatomic, setter=_setInitialDisplayItem:) SBDisplayItem *_initialDisplayItem;
@property(copy, nonatomic, setter=_setReturnToSideDisplayItem:) SBDisplayItem *_returnToSideDisplayItem;
@property(copy, nonatomic, setter=_setReturnToDisplayItem:) SBDisplayItem *_returnToDisplayItem;
- (void)replaceDisplayItem:(SBDisplayItem *)arg1 withDisplayItem:(SBDisplayItem *)arg2 completion:(void (^)(BOOL, SBDisplayItem *, SBDisplayItem *))arg3;
- (void)removeDisplayItem:(SBDisplayItem *)arg1 forReason:(int)arg2 completion:(void (^)(BOOL, SBDisplayItem *, SBDisplayItem *))arg3;
- (void)insertDisplayItem:(SBDisplayItem *)arg1 atIndex:(unsigned int)arg2 completion:(void (^)(BOOL, SBDisplayItem *, SBDisplayItem *))arg3;
- (void)animateDismissalToDisplayItem:(SBDisplayItem *)arg1 forTransitionRequest:(SBWorkspaceTransitionRequest *)arg2 withCompletion:(void (^)(void))arg3;
- (void)animatePresentationForTransitionRequest:(SBWorkspaceTransitionRequest *)arg1 withCompletion:(void (^)(void))arg2;
- (void)endTransitionWithSuccess:(BOOL)arg1 completion:(void (^)(BOOL))arg2;
- (SBDisplayItem *)nextDisplayItem;
- (void)setTransitionParameters:(CDStruct_3ee5880e)arg1;
- (void)endInteractionWithCommitment:(BOOL)arg1;
- (void)startInteractiveTransition:(BOOL)arg1 presenting:(BOOL)arg2 withRequest:(SBWorkspaceTransitionRequest *)arg3;
- (BOOL)hasInteractiveContentAtBottomOfScreen;
- (void)invalidate;
@end

