//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class NSString;

@interface SBMedusaSettings : SBUISettings
{
    BOOL _enableSideApps;
    BOOL _enableBreadcrumbs;
    BOOL _enablePinningSideApps;
    BOOL _debugSceneColors;
    BOOL _debugRotationCenter;
    BOOL _debugColorRotationRegions;
    BOOL _clipRotationRegions;
    BOOL _fencesRotation;
    NSString *_desiredBundleIdentifier;
    float _zoomOutRotationFactor;
    float _rotationSlowdownFactor;
    float _spaceAroundSideGrabberToAllowPullIn;
    float _slideOffResizeThreshold;
    float _gapSwipeBuffer;
    unsigned long long _millisecondsBetweenResizeSteps;
}

+ (id)settingsControllerModule;
@property(nonatomic) float gapSwipeBuffer; // @synthesize gapSwipeBuffer=_gapSwipeBuffer;
@property(nonatomic) float slideOffResizeThreshold; // @synthesize slideOffResizeThreshold=_slideOffResizeThreshold;
@property(nonatomic) unsigned long long millisecondsBetweenResizeSteps; // @synthesize millisecondsBetweenResizeSteps=_millisecondsBetweenResizeSteps;
@property(nonatomic) BOOL fencesRotation; // @synthesize fencesRotation=_fencesRotation;
@property(nonatomic) float spaceAroundSideGrabberToAllowPullIn; // @synthesize spaceAroundSideGrabberToAllowPullIn=_spaceAroundSideGrabberToAllowPullIn;
@property(nonatomic) float rotationSlowdownFactor; // @synthesize rotationSlowdownFactor=_rotationSlowdownFactor;
@property(nonatomic) float zoomOutRotationFactor; // @synthesize zoomOutRotationFactor=_zoomOutRotationFactor;
@property(nonatomic) BOOL clipRotationRegions; // @synthesize clipRotationRegions=_clipRotationRegions;
@property(nonatomic) BOOL debugColorRotationRegions; // @synthesize debugColorRotationRegions=_debugColorRotationRegions;
@property(nonatomic) BOOL debugRotationCenter; // @synthesize debugRotationCenter=_debugRotationCenter;
@property(nonatomic) BOOL debugSceneColors; // @synthesize debugSceneColors=_debugSceneColors;
@property(copy, nonatomic) NSString *desiredBundleIdentifier; // @synthesize desiredBundleIdentifier=_desiredBundleIdentifier;
@property(nonatomic) BOOL enablePinningSideApps; // @synthesize enablePinningSideApps=_enablePinningSideApps;
@property(nonatomic) BOOL enableBreadcrumbs; // @synthesize enableBreadcrumbs=_enableBreadcrumbs;
@property(nonatomic) BOOL enableSideApps; // @synthesize enableSideApps=_enableSideApps;
- (void).cxx_destruct;
- (BOOL)anyRotationDebuggingEnabled;
- (void)setDefaultValues;

@end

