//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "SBAppViewHostRequester.h"
#import "SBMainAppSwitcherContentViewControlling.h"

@class NSArray, NSMutableArray, NSString, SBAppView, SBBestAppSuggestion, SBDisplayItem, SBMainDisplayLayoutState;

@interface SBMinimumViableSwitcherTableViewController : UITableViewController <SBAppViewHostRequester, SBMainAppSwitcherContentViewControlling>
{
    NSMutableArray *_displayItems;
    id <SBMainAppSwitcherContentViewControllerDelegate> _delegate;
    SBAppView *_temporaryAppView;
    SBAppView *_temporarySideAppView;
    SBDisplayItem *_returnToDisplayItem;
    SBDisplayItem *_initialDisplayItem;
    SBDisplayItem *_returnToSideDisplayItem;
    SBMainDisplayLayoutState *_initialLayoutState;
    SBBestAppSuggestion *_bestAppSuggestion;
    BOOL _invalidated;
}

+ (float)snapshotScale;
@property(retain, nonatomic) SBBestAppSuggestion *bestAppSuggestion; // @synthesize bestAppSuggestion=_bestAppSuggestion;
@property(nonatomic) __weak id <SBMainAppSwitcherContentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *displayItems; // @synthesize displayItems=_displayItems;
@property(retain, nonatomic, setter=_setInitialLayoutState:) SBMainDisplayLayoutState *_initialLayoutState; // @synthesize _initialLayoutState;
@property(copy, nonatomic, setter=_setReturnToSideDisplayItem:) SBDisplayItem *_returnToSideDisplayItem; // @synthesize _returnToSideDisplayItem;
@property(copy, nonatomic, setter=_setInitialDisplayItem:) SBDisplayItem *_initialDisplayItem; // @synthesize _initialDisplayItem;
@property(copy, nonatomic, setter=_setReturnToDisplayItem:) SBDisplayItem *_returnToDisplayItem; // @synthesize _returnToDisplayItem;
- (void).cxx_destruct;
- (int)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)_unhostSideAppToStopHidingThem;
- (void)_hostSideAppToHideThem;
- (void)animateDismissalToDisplayItem:(id)arg1 forTransitionRequest:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)animatePresentationForTransitionRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)endTransitionWithSuccess:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (id)nextDisplayItem;
- (void)setTransitionParameters:(CDStruct_3ee5880e)arg1;
- (void)endInteractionWithCommitment:(BOOL)arg1;
- (void)startInteractiveTransition:(BOOL)arg1 presenting:(BOOL)arg2 withRequest:(id)arg3;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)replaceDisplayItem:(id)arg1 withDisplayItem:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeDisplayItem:(id)arg1 forReason:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)insertDisplayItem:(id)arg1 atIndex:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)hasInteractiveContentAtBottomOfScreen;
- (void)invalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

