//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSceneManagerObserver.h"

@class FBScene, FBSceneManager, NSString, SBModalAlertPresentationCoordinator;

@interface SBModalAlertPresenter : NSObject <FBSceneManagerObserver>
{
    SBModalAlertPresentationCoordinator *_modalAlertPresentationCoordinator;
    FBSceneManager *_sceneManager;
    FBScene *_scene;
    unsigned int _visibleAlertCount;
    BOOL _invalidated;
    BOOL _isSystemPresenter;
}

@property(retain, nonatomic, setter=_setScene:) FBScene *scene; // @synthesize scene=_scene;
- (void).cxx_destruct;
- (BOOL)_areSettingsBackground:(id)arg1;
- (void)sceneManager:(id)arg1 willUpdateScene:(id)arg2 withSettings:(id)arg3 transitionContext:(id)arg4;
- (void)invalidate;
- (void)decrementModalAlertCount;
- (void)incrementModalAlertCount;
@property(readonly, nonatomic, getter=isForeground) BOOL foreground; // @dynamic foreground;
@property(readonly, nonatomic, getter=isShowingModalAlert) BOOL showingModalAlert; // @dynamic showingModalAlert;
- (void)dealloc;
- (id)initWithScene:(id)arg1;
- (id)initForSystemApplication;
- (id)_initWithModalAlertPresentationCoordinator:(id)arg1 sceneManager:(id)arg2 scene:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

