//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBWallpaperEffectView;

@interface SBMultiVariantWallpaperEffectView : UIView
{
    SBWallpaperEffectView *_homeWallpaperEffectView;
    SBWallpaperEffectView *_lockWallpaperEffectView;
    BOOL _transformIgnoresRotation;
    int _variant;
    int _style;
}

@property(nonatomic) BOOL transformIgnoresRotation; // @synthesize transformIgnoresRotation=_transformIgnoresRotation;
@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic) int variant; // @synthesize variant=_variant;
- (void).cxx_destruct;
- (void)_createEffectViewForVariantIfNeeded:(int)arg1;
- (id)_activeEffectView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

