//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAppStatusBarSettings.h"

@class _UILegibilitySettings;

@interface SBMutableAppStatusBarSettings : SBAppStatusBarSettings
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @dynamic legibilitySettings;
@property(nonatomic) int style; // @dynamic style;
@property(nonatomic) float alpha; // @dynamic alpha;
- (id)init;

@end

