//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBSectionInfo, NSArray;

@protocol SBNotificationSectionSettingsObserver <NSObject>

@optional
- (void)updateSectionInfo:(BBSectionInfo *)arg1;
- (void)updateSectionOrder:(NSArray *)arg1;
- (void)updateSectionOrderRule:(int)arg1;
@end

