//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BBObserverDelegate.h"

@class BBObserver, NSArray, NSMutableSet, NSString;

@interface SBNotificationSectionSettings : NSObject <BBObserverDelegate>
{
    int _sectionOrderRule;
    NSArray *_sectionOrder;
    BBObserver *_bbObserver;
    NSMutableSet *_settingsObservers;
}

@property(retain, nonatomic) NSMutableSet *settingsObservers; // @synthesize settingsObservers=_settingsObservers;
@property(retain, nonatomic) BBObserver *bbObserver; // @synthesize bbObserver=_bbObserver;
@property(readonly, copy, nonatomic) NSArray *sectionOrder; // @synthesize sectionOrder=_sectionOrder;
@property(readonly, nonatomic) int sectionOrderRule; // @synthesize sectionOrderRule=_sectionOrderRule;
- (void).cxx_destruct;
- (void)_performOnAllObservers:(CDUnknownBlockType)arg1;
- (void)observer:(id)arg1 noteServerConnectionStateChanged:(BOOL)arg2;
- (void)observer:(id)arg1 updateSectionInfo:(id)arg2;
- (void)observer:(id)arg1 updateSectionOrder:(id)arg2;
- (void)observer:(id)arg1 updateSectionOrderRule:(int)arg2;
- (void)unregisterSettingsObserver:(id)arg1;
- (void)registerSettingsObserver:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

