//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBViewControllerTransitionContext.h"

@interface SBNotificationCenterTransitionContext : SBViewControllerTransitionContext
{
    BOOL _fromCurrentState;
    int _presentationType;
    CDUnknownBlockType _stepper;
    CDUnknownBlockType _presentationBegunHandler;
    CDUnknownBlockType _pendingTransition;
    CDUnknownBlockType _completion;
    struct CGPoint _initialTouchLocation;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(copy, nonatomic) CDUnknownBlockType pendingTransition; // @synthesize pendingTransition=_pendingTransition;
@property(copy, nonatomic) CDUnknownBlockType presentationBegunHandler; // @synthesize presentationBegunHandler=_presentationBegunHandler;
@property(copy, nonatomic) CDUnknownBlockType stepper; // @synthesize stepper=_stepper;
@property(nonatomic) struct CGPoint initialTouchLocation; // @synthesize initialTouchLocation=_initialTouchLocation;
@property(nonatomic, getter=isFromCurrentState) BOOL fromCurrentState; // @synthesize fromCurrentState=_fromCurrentState;
@property(nonatomic) int presentationType; // @synthesize presentationType=_presentationType;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isPresenting) BOOL presenting;

@end

