//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NCNotificationAlertDestination.h"
#import "NCNotificationViewControllerDelegatePrivate.h"
#import "SBNotificationDestinationHomeButtonPressHandler.h"

@class FBUIApplicationSceneDeactivationAssertion, NCNotificationViewController, NSObject<OS_dispatch_source>, NSString, SBAppStatusBarSettingsAssertion, SBLockScreenManager, SBNotificationBannerWindow, SBNotificationCenterController, SBQuietModeStateAggregator, SBSetupManager;

@interface SBNotificationBannerDestination : NSObject <NCNotificationViewControllerDelegatePrivate, NCNotificationAlertDestination, SBNotificationDestinationHomeButtonPressHandler>
{
    id <NCNotificationAlertDestinationDelegate> _delegate;
    SBLockScreenManager *_lockScreenManager;
    SBNotificationCenterController *_notificationCenterController;
    SBQuietModeStateAggregator *_quietModeStateAggregator;
    SBSetupManager *_setupManager;
    NCNotificationViewController *_presentedBanner;
    SBNotificationBannerWindow *_bannerWindow;
    NSObject<OS_dispatch_source> *_presentTimer;
    NSObject<OS_dispatch_source> *_replaceTimer;
    NSObject<OS_dispatch_source> *_dismissTimer;
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
}

@property(retain, nonatomic) SBAppStatusBarSettingsAssertion *statusBarAssertion; // @synthesize statusBarAssertion=_statusBarAssertion;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *resignActiveAssertion; // @synthesize resignActiveAssertion=_resignActiveAssertion;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *dismissTimer; // @synthesize dismissTimer=_dismissTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *replaceTimer; // @synthesize replaceTimer=_replaceTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *presentTimer; // @synthesize presentTimer=_presentTimer;
@property(retain, nonatomic) SBNotificationBannerWindow *bannerWindow; // @synthesize bannerWindow=_bannerWindow;
@property(retain, nonatomic) NCNotificationViewController *presentedBanner; // @synthesize presentedBanner=_presentedBanner;
@property(retain, nonatomic) SBSetupManager *setupManager; // @synthesize setupManager=_setupManager;
@property(retain, nonatomic) SBQuietModeStateAggregator *quietModeStateAggregator; // @synthesize quietModeStateAggregator=_quietModeStateAggregator;
@property(retain, nonatomic) SBNotificationCenterController *notificationCenterController; // @synthesize notificationCenterController=_notificationCenterController;
@property(retain, nonatomic) SBLockScreenManager *lockScreenManager; // @synthesize lockScreenManager=_lockScreenManager;
@property(nonatomic) __weak id <NCNotificationDestinationDelegate> delegate;
- (void).cxx_destruct;
- (void)_dismissBannerForUILocking;
- (void)_dismissNonStickyBanner;
- (void)_dismissBannerCompleted;
- (void)_dismissPresentedBannerAnimated:(BOOL)arg1;
- (void)_setupDismissalNotifications;
- (void)_setupSystemStateChangeNotifications;
- (void)_setupTimers;
- (void)_cancelReplaceAndDismissTimers;
- (void)_cancelDismissTimer;
- (void)_cancelReplaceTimer;
- (void)_startReplaceAndDismissTimersForRequest:(id)arg1;
- (void)_startDismissTimer;
- (void)_startReplaceTimer;
- (void)_resetPresentTimer;
- (id)_presentNotificationViewControllerForRequest:(id)arg1 modal:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_viewControllerForPresentation;
- (id)_notificationViewControllerForRequest:(id)arg1;
- (BOOL)_isQuietModeEnabledAndActive;
- (BOOL)_isNotificationCenterVisible;
- (BOOL)_isInSetupMode;
- (BOOL)_isPresentedBannerBeingDragged;
- (BOOL)_isPresentingBannerInLongLook;
- (BOOL)_isShowingShortLookAtRest;
- (BOOL)_isPresentingStickyBanner;
- (BOOL)_isPresentingBanner;
- (void)_setStatusBarsHidden:(BOOL)arg1 withDuration:(double)arg2;
- (BOOL)_presentedBannerMatchesNotificationRequest:(id)arg1;
- (void)_postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_cleanupRootViewControllerPresentationStack;
- (id)_rootViewController;
- (void)_setReadyForNotificationRequestsCoalescingWith:(id)arg1;
- (void)_setReadyForNotificationRequests;
- (void)_setupModeChanged;
- (void)_lockStateChanged;
- (id)colorInfusingViewForNotificationViewController:(id)arg1;
- (void)notificationViewController:(id)arg1 shouldFinishLongLookTransitionWithCompletionBlock:(CDUnknownBlockType)arg2;
- (id)notificationViewController:(id)arg1 staticContentProviderForNotificationRequest:(id)arg2;
- (BOOL)notificationViewControllerShouldInterpretTapAsDefaultAction:(id)arg1;
- (BOOL)notificationViewControllerShouldPan:(id)arg1;
- (void)notificationViewControllerWillBeginDragging:(id)arg1;
- (void)notificationViewControllerDidEndDragging:(id)arg1;
- (void)notificationViewController:(id)arg1 didCommitToLongLookPresentation:(BOOL)arg2 withCoordinator:(id)arg3;
- (void)notificationViewController:(id)arg1 didCommitToShortLookPresentation:(BOOL)arg2 withCoordinator:(id)arg3;
- (BOOL)notificationViewController:(id)arg1 suggestsDismissingShortLookWithSource:(id)arg2;
- (void)notificationViewController:(id)arg1 didDismissShortLook:(BOOL)arg2;
- (void)notificationViewController:(id)arg1 didDismissLongLook:(BOOL)arg2;
- (void)notificationViewController:(id)arg1 didPresentLongLook:(BOOL)arg2;
- (void)longLookWillPresentForNotificationViewController:(id)arg1;
- (void)notificationViewController:(id)arg1 executeAction:(id)arg2 withParameters:(id)arg3;
- (BOOL)handleHomeButtonPress;
- (void)withdrawNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)modifyNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (BOOL)canReceiveNotificationRequest:(id)arg1;
@property(readonly, nonatomic) NSString *identifier;
- (void)presentModalBannerForNotificationRequest:(id)arg1;
@property(readonly, nonatomic, getter=isPresentingBanner) BOOL presentingBanner;
- (id)init;
- (void)_runBannerPresentationTestWithBeginBlock:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_runLongLookPresentationTestWithBeginBlock:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

