//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBBulletinActionHandler.h"
#import "SBModeViewControllerDelegate.h"

@class NSSet, NSString, SBModeViewController, SBNotificationSeparatorView, SBNotificationsViewController;

@interface SBNotificationCenterLayoutViewController : UIViewController <SBBulletinActionHandler, SBModeViewControllerDelegate>
{
    int _supportedNotificationCenterLayoutModes;
    int _lastPresentedNotificationCenterLayoutMode;
    SBNotificationSeparatorView *_topSeparatorView;
    id <SBBulletinActionHandler> _bulletinActionHandler;
    SBNotificationsViewController *_notificationsViewController;
    SBModeViewController *_modeViewController;
}

@property(readonly, nonatomic) SBModeViewController *modeViewController; // @synthesize modeViewController=_modeViewController;
@property(readonly, nonatomic) SBNotificationsViewController *notificationsViewController; // @synthesize notificationsViewController=_notificationsViewController;
@property(nonatomic) __weak id <SBBulletinActionHandler> bulletinActionHandler; // @synthesize bulletinActionHandler=_bulletinActionHandler;
- (void).cxx_destruct;
- (void)runScrollTest:(id)arg1 iterations:(int)arg2 delta:(int)arg3 useAAGView:(BOOL)arg4;
- (BOOL)handleAction:(id)arg1 forBulletin:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (struct UIEdgeInsets)contentInsetsForModeViewController:(id)arg1;
- (void)_backgroundContrastDidChange:(id)arg1;
@property(readonly, copy, nonatomic) NSSet *visibleContentViewControllers;
- (void)viewWillLayoutSubviews;
- (int)_notificationCenterLayoutModeForCurrentState;
- (void)_layoutModeViewController;
- (int)layoutMode;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)_loadContentViewControllers;
- (BOOL)_needsLayoutAfterLoadingContentViewControllers;
- (BOOL)_areNotificationsViewControllersAvailable;
- (BOOL)_isDeviceMoreThanUILocked;
- (id)_notificationsViewControllerCreateIfNecessary:(BOOL)arg1;
- (void)_setUpColumnViewController:(id)arg1;
- (BOOL)_shouldLayoutInTwoColumnsInActiveLayoutMode;
- (BOOL)_shouldLayoutInTwoColumnsInLayoutMode:(int)arg1;
- (BOOL)_managesTwoColumns;
- (id)_localizableTitleForColumnViewController:(id)arg1;
- (id)initForNotificationCenterLayoutMode:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

