//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCUIControlCenterObserver.h"
#import "PGPictureInPictureControllerDelegate.h"
#import "SBAlertItemsControllerObserver.h"
#import "SBAlertManagerObserver.h"
#import "SBAssistantObserver.h"

@class NSMutableDictionary, NSMutableSet, NSString, PGPictureInPictureController, SBWindow;

@interface SBPIPController : NSObject <PGPictureInPictureControllerDelegate, CCUIControlCenterObserver, SBAlertManagerObserver, SBAlertItemsControllerObserver, SBAssistantObserver>
{
    PGPictureInPictureController *_pictureInPictureController;
    SBWindow *_pictureInPictureWindow;
    struct UIEdgeInsets _pictureInPictureWindowMargin;
    NSMutableSet *_pictureInPictureWindowHiddenReasons;
    NSMutableDictionary *_pictureInPictureInsetsForSource;
}

+ (id)sharedInstance;
+ (BOOL)isAutoPictureInPictureSupported;
+ (BOOL)isPictureInPictureSupported;
- (void).cxx_destruct;
- (void)pictureInPictureController:(id)arg1 willDestroyPictureInPictureViewController:(id)arg2;
- (void)pictureInPictureController:(id)arg1 didCreatePictureInPictureViewController:(id)arg2;
- (void)_setPictureInPictureWindowMargin:(struct UIEdgeInsets)arg1 animationDuration:(double)arg2 animationOptions:(unsigned int)arg3;
- (void)_updatePictureInPictureOverlayInsetsWithDuration:(double)arg1;
- (void)_bulletinWillDismiss:(id)arg1;
- (void)_bulletinWillPresent:(id)arg1;
- (void)_keyboardWillDisappear:(id)arg1;
- (void)_keyboardWillRotate:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_adjustPIPInsetsForKeyboardFrameChangeNotification:(id)arg1;
- (BOOL)_pointInside:(struct CGPoint)arg1;
- (id)_pipWindow;
- (void)_nowPlayingStateChangedForPartialMedusaDevice;
- (void)_appSwitcherWillQuitApp:(id)arg1;
- (void)_lockStateDidChange:(id)arg1;
- (void)_managePictureInPictureWindowLevel;
- (void)_managePictureInPictureWindowVisibilityAnimated:(BOOL)arg1;
- (void)_destroyWindowAndRootViewControllerIfPossible;
- (void)_createWindowAndRootViewControllerIfNeeded;
- (id)_pictureInPictureApplicationForProcessIdentifier:(int)arg1;
- (void)assistant:(id)arg1 viewDidDisappear:(int)arg2;
- (void)assistant:(id)arg1 viewWillAppear:(int)arg2;
- (void)alertItemsController:(id)arg1 didDeactivateAlertItem:(id)arg2 forReason:(int)arg3;
- (void)alertItemsController:(id)arg1 didActivateAlertItem:(id)arg2;
- (void)alertItemsController:(id)arg1 willActivateAlertItem:(id)arg2;
- (void)alertManager:(id)arg1 didTearDownAlertWindow:(id)arg2;
- (void)alertManager:(id)arg1 didCreateAlertWindow:(id)arg2;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)applyPictureInPictureInsets:(struct UIEdgeInsets)arg1 fromSource:(int)arg2 duration:(double)arg3;
- (void)pictureInPictureInterruptionEnded;
- (void)pictureInPictureInterruptionBegan;
- (void)startPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 animated:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (BOOL)shouldStartPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1;
- (BOOL)isPictureInPictureWindowVisible;
- (void)setPictureInPictureWindowHidden:(BOOL)arg1 withReason:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

