//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIInteractionProgress.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIPinchGestureRecognizer;

@interface SBPinchInteractionProgress : UIInteractionProgress <UIGestureRecognizerDelegate>
{
    CDStruct_33193670 _pinchInterval;
    UIPinchGestureRecognizer *_pinchGesture;
}

@property(readonly, nonatomic) UIPinchGestureRecognizer *pinchGesture; // @synthesize pinchGesture=_pinchGesture;
- (void).cxx_destruct;
- (void)_updatePinchScale:(float)arg1;
- (void)_handlePinchGesture:(id)arg1;
@property(readonly, nonatomic) float minPinchScale;
- (id)initWithPinchGesture:(id)arg1 minPinchScale:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

