//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSOrderedSet, NSString;

@interface SBPlatformController : NSObject
{
    long _defaultIconInfoOnce;
    NSDictionary *_defaultStarkIconState;
    NSDictionary *_defaultIconState;
    NSOrderedSet *_defaultIconStateDisplayIdentifiers;
    NSString *_localizedDeviceName;
    BOOL _hasGasGauge;
    BOOL _supportsOpenGLES2;
    BOOL _internalInstall;
    BOOL _carrierInstall;
    BOOL _singleCoreDevice;
    BOOL _isH4Device;
    BOOL _starkDevice;
    BOOL _medusaDevice;
    BOOL _supportsAllMedusaFeatures;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_loadDefaultIconInfoIfNecessary;
- (BOOL)supportsAllMedusaFeatures;
- (BOOL)isMedusaDevice;
- (BOOL)isStarkDevice;
- (BOOL)isH4Device;
- (BOOL)isSingleCoreDevice;
- (BOOL)isDeveloperDevice;
- (BOOL)isCarrierInstall;
- (BOOL)isInternalInstall;
- (BOOL)supportsOpenGLES2;
- (BOOL)hasGasGauge;
- (id)localizedPlatformName;
- (id)defaultIconStateDisplayIdentifiers;
- (id)defaultStarkIconState;
- (id)defaultIconState;
- (id)uniqueDeviceIdentifier;
- (id)deviceClass;
- (id)productType;
- (id)hardwareModel;
- (id)systemBuildVersion;
- (id)init;

@end

