//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBSDisplay, MCProfileConnection, SBDemoDefaults, SBFDeviceLockOutController, SBFUserAuthenticationController, SBLockScreenDefaults, SBRestartManager, SBSetupManager, SBUserSessionController;

@interface SBPolicyAggregator : NSObject
{
    FBSDisplay *_display;
    SBUserSessionController *_lazy_userSessionController;
    MCProfileConnection *_lazy_profileConnection;
    SBSetupManager *_lazy_setupManager;
    SBFUserAuthenticationController *_lazy_authenticationController;
    SBFDeviceLockOutController *_lazy_deviceLockOutController;
    SBLockScreenDefaults *_lazy_lockScreenDefaults;
    struct __CFBoolean *_hasCameraCapability;
    SBRestartManager *_restartManager;
    SBDemoDefaults *_demoDefaults;
    BOOL _storeDemoAppLockEnabled;
}

@property(retain, nonatomic, getter=_lockScreenDefaults, setter=_setLockScreenDefaults:) SBLockScreenDefaults *lockScreenDefaults; // @synthesize lockScreenDefaults=_lazy_lockScreenDefaults;
@property(retain, nonatomic, getter=_deviceLockOutController, setter=_setDeviceLockOutController:) SBFDeviceLockOutController *deviceLockOutController; // @synthesize deviceLockOutController=_lazy_deviceLockOutController;
@property(retain, nonatomic, getter=_authenticationController, setter=_setAuthenticationController:) SBFUserAuthenticationController *authenticationController; // @synthesize authenticationController=_lazy_authenticationController;
@property(retain, nonatomic, getter=_setupManager, setter=_setSetupManager:) SBSetupManager *setupManager; // @synthesize setupManager=_lazy_setupManager;
@property(retain, nonatomic, getter=_profileConnection, setter=_setProfileConnection:) MCProfileConnection *profileConnection; // @synthesize profileConnection=_lazy_profileConnection;
@property(retain, nonatomic, getter=_userSessionController, setter=_setUserSessionController:) SBUserSessionController *userSessionController; // @synthesize userSessionController=_lazy_userSessionController;
- (void).cxx_destruct;
- (BOOL)_allowsCapabilityLiftToWakeWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityTodayViewWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLockScreenTodayViewWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLockScreenNotificationCenterWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLockScreenControlCenterWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityCommandTabWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityScreenshotWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityHomeScreenEditingWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLoginWindowWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLogoutWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityControlCenterWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityNotificationCenterWithExplanation:(id *)arg1;
- (BOOL)_allowsNotificationOrControlCenterWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLockScreenCameraWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLockScreenCameraSupportedWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilitySpotlightWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityVoiceControlWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilitySystemGestureWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilitySendMediaCommandWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityAssistantWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityAssistantEnabledWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityUnlockToPluginSpecifiedApplicationWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilityLockScreenBulletinWithExplanation:(id *)arg1;
- (BOOL)_allowsCapabilitySuggestedApplicationWithExplanation:(id *)arg1;
- (BOOL)_hasFullySetUpUserWithExplanation:(id *)arg1;
- (void)reloadDemoDefaults;
- (BOOL)allowsTransitionRequest:(id)arg1;
- (BOOL)allowsCapability:(int)arg1 explanation:(id *)arg2;
- (BOOL)allowsCapability:(int)arg1;
- (id)initWithDisplay:(id)arg1;
- (id)_initWithDisplay:(id)arg1 demoDefaults:(id)arg2 restartManager:(id)arg3;

@end

