//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class NSString;

@interface SBPrototypeControllerSettings : SBUISettings
{
    BOOL _preventLockover;
    NSString *_testRecipeClassName;
    float _windowAlpha;
}

@property BOOL preventLockover; // @synthesize preventLockover=_preventLockover;
@property float windowAlpha; // @synthesize windowAlpha=_windowAlpha;
@property(retain) NSString *testRecipeClassName; // @synthesize testRecipeClassName=_testRecipeClassName;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

