//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBProcessSettings;

@protocol SBProcessSettings <NSObject>
- (void)clearProcessSettings;
- (void)applyProcessSettings:(SBProcessSettings *)arg1;
- (SBProcessSettings *)copyProcessSettings;
- (id)objectForProcessSetting:(int)arg1;
- (void)setObject:(id)arg1 forProcessSetting:(int)arg2;
- (BOOL)boolForProcessSetting:(int)arg1;
- (int)flagForProcessSetting:(int)arg1;
- (void)setFlag:(int)arg1 forProcessSetting:(int)arg2;
@end

