//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderView.h"

#import "SBFramewiseInteractiveTransitionAnimatorDelegate.h"
#import "SBSearchEtceteraMultiplexingViewControllerAppearanceDelegate.h"
#import "SBSearchGestureObserver.h"
#import "SBViewControllerTransitionContextDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class NSString, SBDockIconListView, SBDockView, SBFParallaxSettings, SBFramewiseInteractiveTransitionAnimator, SBHomeScreenPullDownSearchViewController, SBHomeScreenSearchableTodayViewController, SBPercentPassthroughInteractiveTransition, SBRootFolder, SBSearchBackdropView, SBSearchBlurEffectView, SBViewControllerTransitionContext, UILabel, _SBMinusPageStepper, _SBSearchWrapperView;

@interface SBRootFolderView : SBFolderView <_UISettingsKeyObserver, SBSearchGestureObserver, UIGestureRecognizerDelegate, SBViewControllerTransitionContextDelegate, SBFramewiseInteractiveTransitionAnimatorDelegate, SBSearchEtceteraMultiplexingViewControllerAppearanceDelegate>
{
    SBDockView *_dockView;
    SBDockIconListView *_dockListView;
    BOOL _dockViewBorrowed;
    UILabel *_idleTextView;
    SBFParallaxSettings *_parallaxSettings;
    float _reachabilityYOffset;
    BOOL _layingOutForReachability;
    BOOL _reachabilityIsVisibleOrTransitioning;
    _SBSearchWrapperView *_searchPulldownView;
    _SBSearchWrapperView *_searchPageView;
    SBSearchBlurEffectView *_searchBlurEffectView;
    SBSearchBackdropView *_searchBackdropView;
    _SBMinusPageStepper *_minusPageAnimationStepper;
    float _baseOffsetForDeterminingScrollToSearchThreshold;
    struct CGPoint _contentOffsetWhenScrollToSearchBeganDragging;
    int _currentPageIndexWhenScrollToSearchBeganDragging;
    float _dockListHeightWhenScrollToSearchBeganDragging;
    float _pageWidthWhenScrollToSearchBeganDragging;
    BOOL _retryingAutoScrollToSearchDueToUnexpectedContentOffset;
    BOOL _scrollToSearchIsDraggingOrAnimating;
    BOOL _scrollToSearchIsBeingPresentedOrDismissedAutomatically;
    BOOL _searchWasVisibleWhenScrollToSearchBeganDragging;
    int _targetPageIndexForAutoScrollToSearch;
    float _doNotUseThisDirectlyPlease_dockOffscreenProgress;
    SBHomeScreenPullDownSearchViewController *_pullDownSearchViewController;
    SBHomeScreenSearchableTodayViewController *_todayViewController;
    SBViewControllerTransitionContext *_currentPullDownTransition;
    SBFramewiseInteractiveTransitionAnimator *_currentPullDownAnimator;
    SBPercentPassthroughInteractiveTransition *_currentPullDownInteractor;
    SBViewControllerTransitionContext *_currentSlideOverTransition;
    SBFramewiseInteractiveTransitionAnimator *_currentSlideOverAnimator;
    SBPercentPassthroughInteractiveTransition *_currentSlideOverInteractor;
    BOOL _spotlightTransitioningFromBreadcrumb;
    unsigned int _dockEdge;
}

@property(nonatomic, getter=isDockViewBorrowed) BOOL dockViewBorrowed; // @synthesize dockViewBorrowed=_dockViewBorrowed;
@property(nonatomic) unsigned int dockEdge; // @synthesize dockEdge=_dockEdge;
@property(nonatomic, getter=isSpotlightTransitioningFromBreadcrumb) BOOL spotlightTransitioningFromBreadcrumb; // @synthesize spotlightTransitioningFromBreadcrumb=_spotlightTransitioningFromBreadcrumb;
@property(readonly, nonatomic) SBFParallaxSettings *parallaxSettings; // @synthesize parallaxSettings=_parallaxSettings;
- (void).cxx_destruct;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)_kickoffTransitionWithViewController:(id)arg1 presenting:(BOOL)arg2 animated:(BOOL)arg3;
- (void)transitionDidFinish:(id)arg1;
- (void)transitionWillFinish:(id)arg1;
- (void)transitionContext:(id)arg1 updateTransitionProgress:(float)arg2;
- (void)transitionWillReverse:(id)arg1;
- (void)transitionWillBegin:(id)arg1;
- (void)searchEtceteraViewController:(id)arg1 didChangeToMode:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)searchEtceteraViewController:(id)arg1 willChangeToMode:(unsigned int)arg2 animated:(BOOL)arg3;
- (float)_pullDownSearchVisiblilityProgress;
- (BOOL)isPullDownSearchVisibleOrTransitioning;
- (BOOL)_pullDownSearchIsTransitioning;
- (BOOL)isPullDownSearchVisible;
- (id)_activeVCForPullDownSearch;
- (void)searchGesture:(id)arg1 resetAnimated:(BOOL)arg2;
- (void)searchGesture:(id)arg1 completedShowing:(BOOL)arg2;
- (void)searchGesture:(id)arg1 changedPercentComplete:(float)arg2;
- (void)searchGesture:(id)arg1 startedShowing:(BOOL)arg2;
- (float)_slideOverSearchDockOffscreenProgress;
- (float)_slideOverSearchVisiblilityProgress;
- (BOOL)_slideOverSearchCurrentModeWantsBlur;
- (BOOL)isSlideOverSearchVisibleOrTransitioning;
- (BOOL)_slideOverSearchIsTransitioning;
- (BOOL)isSlideOverSearchVisible;
- (id)_activeVCForSlideOverSearch;
- (void)handleReachabilityModeDeactivated;
- (void)handleReachabilityModeActivated;
- (void)_animateViewsForScrollingToSearchWithPercent:(float)arg1;
- (void)_animateViewsForPullingToSearchWithPercent:(float)arg1;
- (void)_handleReachabilityDectivatedAnimate:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_handleReachabilityActivatedAnimate:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (float)reachabilityYOffset;
- (void)handleReachabilityActivated:(BOOL)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)handleCancelReachabilityGesture:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)_configureParallax;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_resetSearchScrollTrackingState;
- (void)_captureInitialSearchScrollTrackingState;
- (void)_cleanUpAfterScrolling;
- (struct UIEdgeInsets)_searchInsetsForPageControl;
- (void)_updateStatusBarInsetsToPercent:(float)arg1;
- (struct UIEdgeInsets)_statusBarInsetsForDockEdge:(unsigned int)arg1 dockOffscreenPercentage:(float)arg2;
- (float)_offsetForSearchPage;
- (float)_pageWidth;
- (void)setScrolling:(BOOL)arg1;
- (float)_scrollOffsetForPageAtIndex:(int)arg1;
- (void)_currentPageIndexDidChange;
- (BOOL)setCurrentPageIndex:(int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateIconListIndexAndVisibility:(BOOL)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setIdleText:(id)arg1;
- (BOOL)_updatesWallpaperRelativeCenter;
- (void)cleanUpAfterTransition;
- (void)prepareForTransition;
- (void)layoutIconLists:(double)arg1 domino:(BOOL)arg2 forceRelayout:(BOOL)arg3;
- (void)tearDownListViews;
- (void)_updateEditingStateAnimated:(BOOL)arg1;
- (void)resetIconListViews;
- (id)iconListViewAtPoint:(struct CGPoint)arg1;
- (id)iconListViewAtIndex:(unsigned int)arg1;
- (id)todayViewController;
- (id)pullDownSearchViewController;
- (struct UIEdgeInsets)statusBarInsetsForDockEdge:(unsigned int)arg1;
- (void)returnDockView;
- (void)borrowDockView;
- (void)_enableUserInteractionAfterSignificantAnimation;
- (void)_disableUserInteractionBeforeSignificantAnimation;
- (void)setContentAlpha:(float)arg1;
- (void)fadeContentForMinificationFraction:(float)arg1;
- (void)_updateDockViewZOrdering;
- (void)updateDockViewOrientation;
- (void)setDockVerticalStretch:(float)arg1;
- (void)setDockOffscreenFraction:(float)arg1;
- (id)dockView;
- (void)_layoutSubviews;
- (void)layoutDockView;
- (struct CGRect)effectivePageControlFrame;
- (struct CGRect)_scrollViewFrameForDockEdge:(unsigned int)arg1;
- (void)layoutViewsForSearch;
- (void)_layoutSubviewsForSlideOverSearch;
- (void)_layoutSubviewsForPulldownSearch;
- (void)setStatusBarHeight:(float)arg1;
- (unsigned int)_minusPageCount;
- (struct CGRect)effectiveDockFrame;
- (float)effectiveStatusBarHeight;
- (void)setLegibilitySettings:(id)arg1;
- (void)setOrientation:(int)arg1;
- (void)setNeedsLayout;
- (void)returnScalingView;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3 forSnapshot:(BOOL)arg4;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3 context:(id)arg4;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) SBRootFolder *folder; // @dynamic folder;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

