//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconZoomAnimator.h"

@class NSDate, SBIcon, SBIconView, SBScaleZoomSettings, UIView;

@interface SBScaleIconZoomAnimator : SBIconZoomAnimator
{
    struct UIEdgeInsets _iconScootch;
    float _naturalVisualAltitude;
    UIView *_scalingView;
    SBIconView *_targetIconView;
    UIView *_targetIconPositioningView;
    NSDate *_startTime;
    double _currentPhaseTwoDelay;
    SBIcon *_targetIcon;
    unsigned int _crossfadeType;
    struct CGPoint _zoomScaleDimension;
}

@property(nonatomic) unsigned int crossfadeType; // @synthesize crossfadeType=_crossfadeType;
@property(readonly, nonatomic) struct CGPoint zoomScaleDimension; // @synthesize zoomScaleDimension=_zoomScaleDimension;
@property(readonly, nonatomic) SBIcon *targetIcon; // @synthesize targetIcon=_targetIcon;
- (void).cxx_destruct;
- (void)_applyOuterFadeFraction:(float)arg1;
- (void)_applyZoomFraction:(float)arg1;
- (void)_setIconAlpha:(float)arg1;
- (float)_zoomedVisualAltitude;
- (struct CGPoint)_zoomedIconCenter;
- (struct CGRect)_zoomedFrame;
- (void)_performAnimationToFraction:(float)arg1 withCentralAnimationSettings:(id)arg2 delay:(double)arg3 alreadyAnimating:(BOOL)arg4 sharedCompletion:(CDUnknownBlockType)arg5;
- (void)_animateToFraction:(float)arg1 afterDelay:(double)arg2 withSharedCompletion:(CDUnknownBlockType)arg3;
- (void)hintToFraction:(float)arg1;
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)arg1;
- (void)_prepareAnimation;
@property(readonly, nonatomic) SBIconView *referenceIconView;
@property(readonly, nonatomic) SBIconView *targetIconView;
- (void)_setZoomScale:(struct CGPoint)arg1;
- (BOOL)_forceSquareZoomDimension;
@property(readonly, nonatomic) BOOL fadesHomeScreen;
@property(readonly, nonatomic) UIView *targetIconContainerView;
@property(readonly, nonatomic) float maxHomeScreenZoomScale;
@property(readonly, nonatomic) float zoomScale;
- (BOOL)isPastPointOfNoReturn;
- (id)initWithFolderController:(id)arg1 targetIcon:(id)arg2;

// Remaining properties
@property(retain, nonatomic) SBScaleZoomSettings *settings; // @dynamic settings;

@end

