//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScreenEdgePanGestureRecognizer.h"

@interface SBScreenEdgePanGestureRecognizer : UIScreenEdgePanGestureRecognizer
{
    BOOL _shouldUseGrapeFlags;
    float _grabberActiveZoneWidth;
}

@property(nonatomic) BOOL shouldUseGrapeFlags; // @synthesize shouldUseGrapeFlags=_shouldUseGrapeFlags;
@property(nonatomic) float grabberActiveZoneWidth; // @synthesize grabberActiveZoneWidth=_grabberActiveZoneWidth;
- (BOOL)isLocationWithinGrabberActiveZone;
- (BOOL)_shouldUseGrapeFlags;
- (int)_touchInterfaceOrientation;
- (struct CGPoint)_locationForTouch:(id)arg1;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2 type:(int)arg3;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)sb_commonInitScreenEdgePanGestureRecognizer;

// Remaining properties
@property(nonatomic) __weak id <SBSystemGestureRecognizerDelegate> delegate; // @dynamic delegate;

@end

