//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "UINavigationControllerDelegate.h"

@class NSString;

@interface SBSearchEtceteraNavigationController : UINavigationController <UINavigationControllerDelegate>
{
    BOOL _shouldUnderlapNavigationBar;
    BOOL _shouldAllowVisibleSeparator;
}

@property(nonatomic) BOOL shouldAllowVisibleSeparator; // @synthesize shouldAllowVisibleSeparator=_shouldAllowVisibleSeparator;
@property(nonatomic) BOOL shouldUnderlapNavigationBar; // @synthesize shouldUnderlapNavigationBar=_shouldUnderlapNavigationBar;
- (void)_updateEdgesForExtendedLayoutForViewController:(id)arg1 underlapNavBar:(BOOL)arg2;
- (float)_statusBarHeightAdjustmentForCurrentOrientation;
- (void)setBlurProgress:(float)arg1 animated:(BOOL)arg2;
- (void)setSeparatorVisible:(BOOL)arg1 animated:(BOOL)arg2;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (id)initWithRootViewController:(id)arg1;
- (id)initWithNavigationBarClass:(Class)arg1 toolbarClass:(Class)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

