//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSearchEtceteraBlurringTransitionAnimator.h"

@interface SBSearchEtceteraBlurringPushTransitionAnimator : SBSearchEtceteraBlurringTransitionAnimator
{
    unsigned int _operation;
}

- (void)_cleanupAfterAnimating:(BOOL)arg1;
- (void)_finishInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)_cancelInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)updateTransition:(id)arg1 withPercentComplete:(float)arg2;
- (void)_animateIntoSearch:(BOOL)arg1;
- (void)_prepareToAnimate;
- (BOOL)shouldMoveIntoSearchOnCancel;
- (BOOL)shouldMoveIntoSearch;

@end

