//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBSearchEtceteraMetrics : NSObject
{
}

+ (BOOL)_isPortrait;
+ (float)minYofClippableContent;
+ (BOOL)shouldShowWeatherViewForStyle:(unsigned int)arg1;
+ (float)topContentInsetForSearchNavigationBar:(id)arg1;
+ (BOOL)shouldAddNavBarInsetForStyle:(unsigned int)arg1;
+ (BOOL)shouldAddTopInsetForStyle:(unsigned int)arg1;
+ (BOOL)isShowingTwoWidgetColumns;

@end

