//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBSearchEtceteraLayoutViewDelegate.h"
#import "SBViewControllerTransitionContextDelegate.h"
#import "SPUISearchViewControllerDelegate.h"
#import "WGWidgetGroupViewControllerDelegate.h"

@class NCNotificationListContainerViewController, NSArray, NSHashTable, NSString, SBNotificationCenterDestination, SBSearchEtceteraLayoutView, SBViewControllerTransitionContext, SPUISearchViewController, UINavigationItem, WALockscreenWidgetViewController, WGWidgetGroupViewController;

@interface SBSearchEtceteraIsolatedViewController : UIViewController <SBViewControllerTransitionContextDelegate, SBSearchEtceteraLayoutViewDelegate, SPUISearchViewControllerDelegate, WGWidgetGroupViewControllerDelegate>
{
    unsigned int _currentMode;
    unsigned int _supportedModes;
    SBSearchEtceteraLayoutView *_layoutView;
    SPUISearchViewController *_searchViewController;
    WGWidgetGroupViewController *_todayViewController;
    SBNotificationCenterDestination *_notificationCenterDestination;
    NCNotificationListContainerViewController *_notificationListContainerViewController;
    WALockscreenWidgetViewController *_weatherViewController;
    NSArray *_notifiableControllersForCurrentTransition;
    unsigned int _transitioningFromMode;
    unsigned int _transitioningToMode;
    UIViewController *_transitioningFromChildViewController;
    UIViewController *_transitioningToChildViewController;
    unsigned int _searchDismissalReasonForThisTransition;
    unsigned int _lastPresentationSource;
    SBViewControllerTransitionContext *_currentTransition;
    id <SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning> _currentTransitionAnimator;
    BOOL _pullToSearchPossible;
    BOOL _pullToSearchRecognizing;
    BOOL transitionedToSearchInteractively;
    BOOL _scrollViewContentOffsetDirty;
    struct CGPoint _scrollViewLastContentOffset;
    NSHashTable *_widgetEffectViews;
    struct {
        unsigned int runningOnPad:1;
        unsigned int delegateRespondsToWillBeginDragging:1;
        unsigned int delegateRespondsToDidScroll:1;
        unsigned int delegateRespondsToWillEndDragging:1;
        unsigned int delegateRespondsToDidEndDragging:1;
        unsigned int delegateRespondsToDidEndDecelerating:1;
        unsigned int delegateRespondsToDidEndScrollingAnimation:1;
        unsigned int delegateRespondsToNewCustomBackgroundViewForItemInList:1;
    } _isolatedViewControllerFlags;
    BOOL _widgetsUseCustomBackgroundViews;
    unsigned int _currentStyle;
    id <SBSearchEtceteraIsolatedViewControllerAppearanceDelegate> _delegate;
    id <WGWidgetGroupViewControllerDelegate> _widgetGroupDelegate;
    id <SPUISearchViewControllerDelegate> _searchDelegate;
    unsigned int _searchViewPresentationSourceForNextTransition;
    unsigned int _searchViewDismissalReasonForNextTransition;
    unsigned int _defaultMode;
    unsigned int _defaultSearchViewPresentationSource;
    unsigned int _defaultSearchViewDismissalReason;
}

+ (Class)__viewClass;
+ (Class)viewClass;
+ (id)sharedInstance;
@property(nonatomic) BOOL widgetsUseCustomBackgroundViews; // @synthesize widgetsUseCustomBackgroundViews=_widgetsUseCustomBackgroundViews;
@property(nonatomic) unsigned int defaultSearchViewDismissalReason; // @synthesize defaultSearchViewDismissalReason=_defaultSearchViewDismissalReason;
@property(nonatomic) unsigned int defaultSearchViewPresentationSource; // @synthesize defaultSearchViewPresentationSource=_defaultSearchViewPresentationSource;
@property(nonatomic) unsigned int defaultMode; // @synthesize defaultMode=_defaultMode;
@property(nonatomic) unsigned int searchViewDismissalReasonForNextTransition; // @synthesize searchViewDismissalReasonForNextTransition=_searchViewDismissalReasonForNextTransition;
@property(nonatomic) unsigned int searchViewPresentationSourceForNextTransition; // @synthesize searchViewPresentationSourceForNextTransition=_searchViewPresentationSourceForNextTransition;
@property(nonatomic) __weak id <SPUISearchViewControllerDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
@property(nonatomic) __weak id <WGWidgetGroupViewControllerDelegate> widgetGroupDelegate; // @synthesize widgetGroupDelegate=_widgetGroupDelegate;
@property(nonatomic) __weak id <SBSearchEtceteraIsolatedViewControllerAppearanceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int currentStyle; // @synthesize currentStyle=_currentStyle;
@property(retain, nonatomic, getter=_notificationCenterDestination, setter=_setNotificationCenterDestination:) SBNotificationCenterDestination *notificationCenterDestination; // @synthesize notificationCenterDestination=_notificationCenterDestination;
@property(retain, nonatomic, getter=_notificationListContainerViewController, setter=_setNotificationListContainerViewController:) NCNotificationListContainerViewController *notificationListContainerViewController; // @synthesize notificationListContainerViewController=_notificationListContainerViewController;
@property(retain, nonatomic, getter=_searchViewController, setter=_setSearchViewController:) SPUISearchViewController *searchViewController; // @synthesize searchViewController=_searchViewController;
@property(retain, nonatomic, getter=_todayViewController, setter=_setTodayViewController:) WGWidgetGroupViewController *todayViewController; // @synthesize todayViewController=_todayViewController;
- (void).cxx_destruct;
- (void)_postNotificationForSearchVisibilityChanged;
- (unsigned int)_lastPresentationSource;
- (unsigned int)_currentPresentationSource;
- (BOOL)_searchIsVisible;
- (BOOL)_deviceSupportsWeatherDisplay;
- (void)_updateSearchLegibility:(id)arg1;
- (void)_updateWeatherLegibility:(id)arg1;
- (void)_updateAccessoryLegibility;
- (BOOL)isShowingSpotlight;
- (void)_resetAfterAnimatedScroll;
- (void)_scrollToEnterSpotlight;
- (void)_exitSpotlightForReason:(unsigned int)arg1 animated:(BOOL)arg2 animationBegan:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_exitSpotlightForReason:(unsigned int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_exitSpotlightForReason:(unsigned int)arg1;
- (void)_enterSpotlightInteractively;
- (void)_enterSpotlightAnimated:(BOOL)arg1 animationBegan:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_enterSpotlightAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)transitionDidFinish:(id)arg1;
- (void)transitionWillFinish:(id)arg1;
- (void)transitionDidReverse:(id)arg1;
- (void)transitionWillBegin:(id)arg1;
- (void)_setCurrentMode:(unsigned int)arg1 animated:(BOOL)arg2 interactive:(BOOL)arg3 animations:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;
- (BOOL)isTransitioning;
- (void)_performStateChange:(CDUnknownBlockType)arg1 forEligibleContainedViewControllers:(id)arg2;
- (id)_viewControllersToNotifyOfStateChanges;
- (id)viewControllerForMode:(unsigned int)arg1;
- (void)_didChangeToMode:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)_setMode:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)_willChangeToMode:(unsigned int)arg1 animated:(BOOL)arg2;
- (unsigned int)_searchPresentationSourceForThisTransition;
- (unsigned int)_searchDismissalReasonForThisTransition;
- (void)_cleanupTransitionStateTracking;
- (void)_captureTransitionStateTrackingForTransitionToMode:(unsigned int)arg1;
- (unsigned int)_nextModeIfResigningCurrentMode;
- (void)_setWeatherViewController:(id)arg1;
- (void)_setNotificationViewController:(id)arg1;
- (void)searchEtceteraLayoutView:(id)arg1 currentModeDidChange:(unsigned int)arg2;
- (void)handleScrollingEnded:(id)arg1;
- (void)handleDraggingWillEndWithTargetContentOffset:(inout struct CGPoint *)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (BOOL)pullDownSearchGestureDraggingFromTopOfScrollView:(id)arg1;
- (float)pullDownSearchGesturePercentComplete;
- (float)pullDownSearchGestureYOffset;
- (struct UIEdgeInsets)widgetListViewEdgeInsetsIncludingSearchHeader:(BOOL)arg1;
- (id)widgetGroupViewController:(id)arg1 newCustomBackgroundViewForItem:(id)arg2 inScrollView:(id)arg3;
- (void)destination:(id)arg1 requestsClearingNotificationRequests:(id)arg2;
- (void)destination:(id)arg1 executeAction:(id)arg2 forNotificationRequest:(id)arg3 withParameters:(id)arg4;
- (id)notificationSectionSettingsForDestination:(id)arg1 forSectionIdentifier:(id)arg2;
- (id)notificationSectionSettingsForDestination:(id)arg1;
- (void)dismissSearchViewWithReason:(unsigned int)arg1;
- (void)searchFieldDidFocus;
- (void)_createMultiplexedChildViewControllers;
@property(readonly, retain, nonatomic) SBSearchEtceteraLayoutView *contentView;
@property(nonatomic) unsigned int currentMode;
- (unsigned int)supportedModes;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (void)_containedViewController:(id)arg1 didDisappear:(BOOL)arg2;
- (void)_containedViewController:(id)arg1 willDisappear:(BOOL)arg2;
- (void)_containedViewController:(id)arg1 didAppear:(BOOL)arg2;
- (void)_containedViewController:(id)arg1 willAppear:(BOOL)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (struct CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(struct CGSize)arg2;
@property(readonly, nonatomic) UINavigationItem *navigationItem;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

