//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning.h"

@class NSString, SBSearchBackdropView, SBSearchEtceteraLayoutContentView, SBSearchEtceteraLayoutView, UIView;

@interface SBSearchEtceteraBlurringTransitionAnimator : NSObject <SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning>
{
    SBSearchEtceteraLayoutView *_layoutView;
    SBSearchEtceteraLayoutContentView *_outgoingView;
    SBSearchEtceteraLayoutContentView *_incomingView;
    SBSearchEtceteraLayoutContentView *_otherView;
    SBSearchEtceteraLayoutContentView *_searchView;
    UIView *_otherWrapperView;
    SBSearchBackdropView *_backdropView;
    unsigned int _initialMode;
    id <SBViewControllerContextTransitioning> _transitionContext;
    float _percentComplete;
    unsigned int _transitionToken;
    unsigned int _destinationMode;
    unsigned int _transitionStyle;
}

@property(nonatomic) unsigned int transitionStyle; // @synthesize transitionStyle=_transitionStyle;
@property(nonatomic) unsigned int destinationMode; // @synthesize destinationMode=_destinationMode;
- (void).cxx_destruct;
- (BOOL)_shouldAnimateBlurRadiusForStyle;
- (BOOL)_shouldUseDarkTintForStyle;
- (BOOL)_shouldUseLightBlurForStyle;
- (void)_cleanupAfterAnimating:(BOOL)arg1;
- (void)_animateIntoSearch:(BOOL)arg1;
- (void)_prepareToAnimate;
- (BOOL)supportsRestarting;
- (float)percentComplete;
- (void)_finishInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)finishInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)_cancelInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)cancelTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)updateTransition:(id)arg1 withPercentComplete:(float)arg2;
- (void)_animateInteractiveTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (BOOL)shouldMoveIntoSearchOnCancel;
- (BOOL)shouldMoveIntoSearch;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

