//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLayoutElementViewController.h"

#import "SBAppViewHostRequester.h"
#import "SBIconViewDelegate.h"
#import "SBIconViewMapDelegate.h"
#import "SBSideSwitcherPageViewDelegate.h"
#import "SBSideSwitcherScrollingItemViewDelegate.h"

@class FBUIApplicationSceneDeactivationAssertion, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SBDisplayItem, SBIconViewMap, SBSideSwitcherScrollingItemViewController;

@interface SBSideSwitcherViewController : SBLayoutElementViewController <SBSideSwitcherScrollingItemViewDelegate, SBSideSwitcherPageViewDelegate, SBIconViewMapDelegate, SBIconViewDelegate, SBAppViewHostRequester>
{
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    SBSideSwitcherScrollingItemViewController *_itemViewController;
    CDStruct_04b3617e _wallpaperBlurTransitionState;
    NSMutableDictionary *_switcherPageViews;
    NSMutableArray *_displayItems;
    NSMutableSet *_hostedApplicationDisplayItems;
    SBIconViewMap *_iconViewMap;
    SBDisplayItem *_transitioningDisplayItem;
    float _transitionProgress;
    BOOL _transitionPresenting;
    unsigned int _transitionState;
    BOOL _hasActivatedItemWhileVisible;
    BOOL _viewCurrentlyAppeared;
}

+ (BOOL)_supportsHighQualityBlurInOverlayMode;
+ (int)overlayBlendModeForGrabberState:(int)arg1 pressed:(BOOL)arg2;
+ (id)grabberColorForGrabberState:(int)arg1 pressed:(BOOL)arg2;
+ (id)sharedInstance;
@property(nonatomic) BOOL viewCurrentlyAppeared; // @synthesize viewCurrentlyAppeared=_viewCurrentlyAppeared;
@property(nonatomic) float transitionProgress; // @synthesize transitionProgress=_transitionProgress;
@property(nonatomic) unsigned int transitionState; // @synthesize transitionState=_transitionState;
- (void).cxx_destruct;
- (int)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
- (void)_endWallpaperForTransitionWithSuccess:(BOOL)arg1;
- (void)_updateWallpaperForTransition;
- (void)_startUpdatingWallpaperForTransition;
- (void)_configureBackgroundView;
- (struct CGSize)_nativeItemSize;
- (struct CGSize)_itemSize;
- (void)_switcherModelChanged:(id)arg1;
- (BOOL)_sideSwitcherIsPinned;
- (int)_sideSwitcherGrabberStyleForDisplayItem:(id)arg1;
- (id)_initialDisplayItemsList;
- (void)selectedPageView:(id)arg1;
- (BOOL)canSelectPageView:(id)arg1 numberOfTaps:(int)arg2;
- (id)windowForRecycledViewsInViewMap:(id)arg1;
- (unsigned int)viewMap:(id)arg1 maxRecycledViewsOfClass:(Class)arg2;
- (id)iconViewMapForSwitcherPageView:(id)arg1;
- (struct CGAffineTransform)overlayViewTransformForPageView:(id)arg1;
- (struct CGAffineTransform)contentViewTransformForPageView:(id)arg1;
- (struct CGSize)contentViewSizeForPageView:(id)arg1;
- (int)resizingPolicyForPageView:(id)arg1;
- (float)iconLabelWidth;
- (BOOL)iconShouldAllowTap:(id)arg1;
- (int)viewMap:(id)arg1 locationForIcon:(id)arg2;
- (Class)iconViewClassForIcon:(id)arg1 location:(int)arg2;
- (BOOL)sideSwitcherScroller:(id)arg1 displayItemWantsToBeKeptInViewHierarchy:(id)arg2;
- (float)sideSwitcherScrollerDistanceBetweenItems:(id)arg1;
- (struct CGSize)sideSwitcherScrollerItemSize:(id)arg1;
- (void)sideSwitcherScroller:(id)arg1 purgeView:(id)arg2;
- (id)sideSwitcherScroller:(id)arg1 viewForDisplayItem:(id)arg2;
- (BOOL)supportsReuse;
- (void)willBeginTransitionToVisible:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)view;
- (int)displayModeForTransitioningDisplayItem;
- (float)heightFromTopForFinalItemSize;
- (void)endTransitionWithSuccess:(BOOL)arg1;
- (void)prepareToEndTransitionAnimated:(BOOL)arg1;
- (void)startTransitionWithDisplayItem:(id)arg1 presenting:(BOOL)arg2 fromDisplayMode:(int)arg3;
- (void)dealloc;
- (id)_initWithDisplay:(id)arg1;
- (id)initWithDisplay:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

