//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@interface SBSIMLockAlertItem : SBAlertItem
{
    int _status;
}

+ (id)alertTitleForStatus:(int)arg1;
+ (id)alertTitleForStatus:(int)arg1 languageCode:(id)arg2;
- (BOOL)reappearsAfterLock;
- (BOOL)reappearsAfterUnlock;
- (BOOL)pendInSetupIfNotAllowed;
- (BOOL)allowInSetup;
- (BOOL)forcesModalAlertAppearance;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (BOOL)_canShowOKButton:(BOOL)arg1;
- (BOOL)_canShowUnlockButton:(BOOL)arg1;
- (BOOL)_isBricked;
- (BOOL)_inSetup;
- (void)performUnlockAction;
- (void)trySIMUnlock;
- (void)didDeactivateForReason:(int)arg1;
- (int)status;
- (id)alertTextForLanguageCode:(id)arg1;
- (id)alertTitleForLanguageCode:(id)arg1;
- (BOOL)canSIMUnlock;
- (void)dealloc;
- (id)initWithStatus:(int)arg1;

@end

