//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBSoftwareUpdateAlertModel;

@protocol SBSoftwareUpdateAlertModelDelegate <NSObject>
- (void)alertModel:(SBSoftwareUpdateAlertModel *)arg1 alertFlowDidChangeFrom:(unsigned int)arg2 to:(unsigned int)arg3;
@end

