//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBSoftwareUpdateInstallOptions : NSObject
{
    BOOL _automaticInstallAttempt;
    BOOL _installDark;
}

@property(nonatomic) BOOL installDark; // @synthesize installDark=_installDark;
@property(nonatomic) BOOL automaticInstallAttempt; // @synthesize automaticInstallAttempt=_automaticInstallAttempt;
- (id)description;

@end

