//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, SBSoftwareUpdateStatePersistence, SUDownload;

@interface SBSoftwareUpdateAlertModel : NSObject
{
    id <SBSoftwareUpdateAlertModelDelegate> _delegate;
    SBSoftwareUpdateStatePersistence *_persistence;
    SUDownload *_updateToInstall;
}

@property(nonatomic) __weak id <SBSoftwareUpdateAlertModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setUpdateToInstall:(id)arg1;
- (void)_setDownloadWasQueuedRemotely:(BOOL)arg1;
- (void)_setInstallAlertRepopStrategy:(unsigned int)arg1 withFireDate:(id)arg2;
- (void)_setInstallAlertFlow:(unsigned int)arg1 forReason:(id)arg2;
- (unsigned int)_initialInstallAlertFlowFromDownload;
- (void)_initializeModelWithDownload:(id)arg1 autoInstallOperation:(id)arg2;
- (void)setInstallAlertRepopStrategy:(unsigned int)arg1 withFireDate:(id)arg2;
- (void)willInstallWithType:(unsigned int)arg1;
- (void)didDownloadUpdate:(id)arg1;
- (void)setDownloadWasQueuedRemotely:(BOOL)arg1;
- (void)autoInstallOperationWasCancelledOrExpired;
- (void)userSelectedRemindMeLater;
- (void)reset;
@property(readonly, nonatomic) unsigned int nextAlertRepopStrategy;
@property(readonly, nonatomic) NSDate *nextAlertDate;
@property(readonly, nonatomic) unsigned int alertFlow;
- (id)initWithDownload:(id)arg1 autoInstallOperation:(id)arg2;
- (id)init;

@end

