//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseSoftwareUpdateInstallFailureAlertItem.h"

@interface SBSoftwareUpdateVerificationFailedAlertItem : SBBaseSoftwareUpdateInstallFailureAlertItem
{
}

- (BOOL)allowInSetup;
- (BOOL)dismissOnLock;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)shouldShowInLockScreen;
- (BOOL)reappearsAfterLock;
- (BOOL)forcesModalAlertAppearance;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;

@end

