//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBPasscodeEntryAlertViewController.h"

#import "SBPasscodeEntryAlertViewDelegate.h"
#import "SBUIPasscodeLockViewDelegate.h"

@class NSString, PSSoftwareUpdateTermsManager, SUAutoInstallOperation, SUDownload, UIViewController;

@interface SBSoftwareUpdateAuthenticationAlertViewController : SBPasscodeEntryAlertViewController <SBPasscodeEntryAlertViewDelegate, SBUIPasscodeLockViewDelegate>
{
    CDUnknownBlockType _completionBlock;
    NSString *_passcode;
    SUAutoInstallOperation *_installOperation;
    SUDownload *_download;
    unsigned int _installType;
    UIViewController *_termsAndConditionsController;
    PSSoftwareUpdateTermsManager *_preferencesSUManager;
    BOOL _showingTermsAndConditions;
    id <SBPasscodeEntryAlertViewControllerDelegate> _delegate;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completionBlock;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void).cxx_destruct;
- (void)_termsDisagree;
- (void)_termsAgree;
- (void)_sendCompletionResponse:(BOOL)arg1;
- (void)_dismissSelf:(BOOL)arg1;
- (void)_sendDeactivationResponseFailureIfNecessary;
- (void)_dismissTermsAndConditionsIfNecessaryAnimated:(BOOL)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_presentTermsAndConditionsWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)_shouldShowPasscodeView;
- (BOOL)passcodeAlertViewShouldShowAutomaticallyWhenVisible:(id)arg1;
- (BOOL)suppressesSiri;
- (BOOL)suppressesNotificationCenter;
- (BOOL)suppressesControlCenter;
- (BOOL)suppressesBanners;
- (void)deactivate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)_authenticationSuccess:(id)arg1 fromMesa:(BOOL)arg2;
- (void)_authenticationCancelled;
- (void)_configurePasscodeView:(id)arg1;
- (void)setVisible:(BOOL)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)initWithDownload:(id)arg1 withInstallType:(unsigned int)arg2 withInstallOperation:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

