//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBScreenConnectionHandler.h"
#import "SBStarkScreenControllerDelegate.h"

@class NSHashTable, NSMutableDictionary, NSString, SBFAuthenticationAssertion, SBLockScreenDisableAssertion, SBSStatusBarStyleOverridesAssertion, SBSpuriousScreenUndimmingAssertion, SBStarkScreenController;

@interface SBStarkScreenManager : NSObject <SBScreenConnectionHandler, SBStarkScreenControllerDelegate>
{
    NSMutableDictionary *_displayToControllerMap;
    SBStarkScreenController *_currentScreenController;
    NSHashTable *_observers;
    SBSpuriousScreenUndimmingAssertion *_spuriousScreenUndimmingAssertion;
    SBFAuthenticationAssertion *_deviceLockDisableAssertion;
    SBLockScreenDisableAssertion *_lockScreenDisableAssertion;
    SBFAuthenticationAssertion *_earlyConnectDeviceLockDisableAssertion;
    SBSStatusBarStyleOverridesAssertion *_carPlayStatusBarStyleOverrideAssertion;
    SBSStatusBarStyleOverridesAssertion *_earlyCarPlayStatusBarStyleOverrideAssertion;
    BOOL _hasShownConnectedAlert;
    BOOL _delayShowingConnectedAlert;
    BOOL _geoSupported;
    BOOL _earlyStarkConnection;
    BOOL _delayUpdatingLockOutMode;
}

+ (BOOL)starkScreenIsAttached;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)screenManager:(id)arg1 didTriggerConnectionHandlerEvent:(int)arg2 forScreen:(id)arg3;
- (BOOL)screenManager:(id)arg1 shouldBindConnectionHandlerToScreen:(id)arg2;
- (void)starkScreenControllerWantsRelockUI:(id)arg1;
- (BOOL)starkScreenControllerShouldDelayUpdateLockoutMode:(id)arg1;
- (void)_promptConnectionSteps;
- (void)_clearPromptState;
- (void)_clearEarlyConnectState;
- (void)_clearEarlyConnectStateTimerExpired;
- (void)_unscheduleClearEarlyConnectStateExpirationTimer;
- (void)_scheduleClearEarlyConnectStateExpirationTimer;
- (void)_earlyStarkConnection;
- (void)_pairedVehiclesChanged:(id)arg1;
- (void)_usbStarkConnected;
- (void)_setCurrentController:(id)arg1;
- (void)_updateGeoSupport;
- (BOOL)shouldShowCarPlayStatusBarItem;
- (id)screenControllerForDisplay:(id)arg1;
- (BOOL)promptRelockUIIfAppropriate;
- (BOOL)handleUnlockAttempt;
- (void)prepareToHandleUnlockAttempt;
- (BOOL)isGeoSupported;
- (BOOL)isStarkActive;
- (id)activeScreenController;
- (BOOL)starkScreenIsAttached;
- (id)currentScreenController;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

