//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBStarkSessionConfiguring.h"

@class AVExternalDevice, CRCarPlayAppPolicyEvaluator, CRVehicleInformation, FBSDisplay, NSMutableDictionary, NSSet, NSString, UIScreen, UITraitCollection;

@interface SBStarkSessionConfiguration : NSObject <SBStarkSessionConfiguring>
{
    CRVehicleInformation *_vehicleInformation;
    AVExternalDevice *_device;
    unsigned int _interactionAffordances;
    int _layoutJustification;
    FBSDisplay *_display;
    UIScreen *_screen;
    float _screenScale;
    BOOL _screenSupportsFocus;
    struct CGRect _screenBounds;
    UITraitCollection *_traitCollection;
    BOOL _connectedWirelessly;
    BOOL _knownVehicle;
    BOOL _OEMIconVisible;
    BOOL _pairedVehicle;
    CRCarPlayAppPolicyEvaluator *_appPolicyEvaluator;
    NSMutableDictionary *_appPolicyForBundleID;
    BOOL _acBackSupported;
    NSString *_layoutId;
    NSSet *__simulatedAccessoryProtocols;
}

+ (id)configurationForSettingsLayoutWithId:(id)arg1 onScreen:(id)arg2;
+ (id)configurationForSettingsLayoutWithId:(id)arg1;
@property(retain, nonatomic) NSSet *_simulatedAccessoryProtocols; // @synthesize _simulatedAccessoryProtocols=__simulatedAccessoryProtocols;
@property(retain, nonatomic) NSString *layoutId; // @synthesize layoutId=_layoutId;
@property(nonatomic, getter=isACBackSupported) BOOL acBackSupported; // @synthesize acBackSupported=_acBackSupported;
- (void).cxx_destruct;
- (void)_setSimulatedAccessoryProtocols:(id)arg1;
@property(nonatomic, getter=isPairedVehicle) BOOL pairedVehicle;
@property(nonatomic, getter=isKnownVehicle) BOOL knownVehicle;
@property(nonatomic, getter=isGeoSupported) BOOL geoSupported;
- (id)policyForApp:(id)arg1;
@property(readonly, nonatomic, getter=isOEMIconVisible) BOOL OEMIconVisible;
@property(readonly, nonatomic, getter=isConnectedWirelessly) BOOL connectedWirelessly;
@property(readonly, nonatomic, getter=isAmbientBrightnessNighttime) BOOL ambientBrightnessNighttime;
@property(readonly, copy, nonatomic) UITraitCollection *traitCollection;
@property(readonly, nonatomic) struct CGRect screenBounds;
@property(readonly, nonatomic) float screenScale;
@property(readonly, nonatomic) UIScreen *screen;
@property(readonly, nonatomic) FBSDisplay *display;
@property(readonly, nonatomic) BOOL screenSupportsFocus;
@property(readonly, nonatomic) int layoutJustification;
@property(readonly, nonatomic) unsigned int interactionAffordances;
@property(readonly, nonatomic) AVExternalDevice *device;
- (id)_init;
- (id)initWithVehicleInformation:(id)arg1 device:(id)arg2 screen:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

