//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderController.h"

@interface SBStarkFolderController : SBFolderController
{
    unsigned int _interactionAffordances;
    BOOL _supportsKnobEvents;
    BOOL _supportsTouchEvents;
}

- (void)_configureForInnerFolderController:(id)arg1;
@property(nonatomic) unsigned int interactionAffordances;
- (id)_iconPageIndicatorImageSetCache;
- (Class)_contentViewClass;

@end

