//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SBSwitchAppList : NSObject
{
    NSArray *_list;
}

@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_resetList;
- (id)_findApplicationInDirection:(unsigned int)arg1 startLookingAtIndex:(unsigned int)arg2 inList:(id)arg3;
- (BOOL)_bundleIDShouldBeRepresentedInList:(id)arg1;
- (void)resetList;
- (BOOL)containsBundleID:(id)arg1;
- (id)applicationBundleIDBeforeBundleID:(id)arg1;
- (id)applicationBundleIDAfterBundleID:(id)arg1;
- (id)description;
- (id)init;

@end

