//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBMainAppSwitcherPageContentView.h"

@class NSString, SBOrientationTransformWrapperView, SBWallpaperEffectView;

@interface SBSwitcherWallpaperPageContentView : UIView <SBMainAppSwitcherPageContentView>
{
    int _orientation;
    int _desiredWallpaperOrientation;
    SBOrientationTransformWrapperView *_wallpaperWrapperView;
    SBWallpaperEffectView *_wallpaperEffectView;
    int _wallpaperStyle;
    float _cornerRadius;
}

@property(readonly, nonatomic) SBWallpaperEffectView *wallpaperEffectView; // @synthesize wallpaperEffectView=_wallpaperEffectView;
@property(nonatomic) int wallpaperStyle; // @synthesize wallpaperStyle=_wallpaperStyle;
@property(nonatomic) int desiredWallpaperOrientation; // @synthesize desiredWallpaperOrientation=_desiredWallpaperOrientation;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
- (void).cxx_destruct;
- (void)_updateWallpaperOrientation;
- (void)_updateCornerRadius;
- (void)viewDismissing:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(float)arg3 forTransitionRequest:(id)arg4;
- (void)viewPresenting:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(float)arg3 forTransitionRequest:(id)arg4;
- (void)layoutSubviews;
- (float)cornerRadius;
- (void)setCornerRadius:(float)arg1;
- (void)invalidate;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

