//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBAppSwitcherPageViewDelegate.h"
#import "SBSwitcherAppSuggestionBottomBannerViewDelegate.h"

@class NSObject<OS_dispatch_queue>, NSString, SBBestAppSuggestion, SBDeckSwitcherPageView, SBSwitcherAppSuggestionBottomBannerView, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface SBSwitcherAppSuggestionViewController : UIViewController <SBSwitcherAppSuggestionBottomBannerViewDelegate, SBAppSwitcherPageViewDelegate>
{
    SBBestAppSuggestion *_bestAppSuggestion;
    BOOL _showSuggestions;
    SBSwitcherAppSuggestionBottomBannerView *_currentBottomBanner;
    SBDeckSwitcherPageView *_slideUpPageView;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIPanGestureRecognizer *_panGestureRecognizer;
    BOOL _inInteractivePresentationOrAnimation;
    BOOL _presentingOrDismissingBanner;
    float _progressPresented;
    BOOL _fullyPresented;
    NSObject<OS_dispatch_queue> *_setSuggestionQueue;
    BOOL _suggestionQueueSuspended;
    id <SBSwitcherAppSuggestionViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBSwitcherAppSuggestionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=_isSuggestionQueueSuspended, setter=_setSuggestionQueueSuspended:) BOOL suggestionQueueSuspended; // @synthesize suggestionQueueSuspended=_suggestionQueueSuspended;
@property(nonatomic) BOOL showSuggestions; // @synthesize showSuggestions=_showSuggestions;
@property(retain, nonatomic) SBBestAppSuggestion *bestAppSuggestion; // @synthesize bestAppSuggestion=_bestAppSuggestion;
- (void).cxx_destruct;
- (struct CGAffineTransform)contentViewTransformForPageView:(id)arg1;
- (int)resizingPolicyForPageView:(id)arg1;
- (void)touchesBeganInBottomBannerView:(id)arg1;
- (void)_removeContainerForSlideUp;
- (void)_insertContainerForSlideUp;
- (void)_handleBannerPan:(id)arg1;
- (void)_finishPresentationOrDismissalForProgress:(float)arg1 velocity:(float)arg2;
- (void)_updatedPanGestureWithProgress:(float)arg1;
- (void)_beganPanGesture;
- (id)_newDynamicAnimationForTargetValue:(double)arg1 withStartValue:(double)arg2 withInitialVelocity:(double)arg3;
- (void)_handleBannerTap:(id)arg1;
- (void)_animateOutAndRemoveCurrentBottomBanner;
- (void)_insertAndAnimateInBottomBannerForSuggestion:(id)arg1;
- (unsigned int)_bottomBannerStyle;
- (void)_updateBottomBanner;
- (struct CGRect)_presentedRectForBottomBanner;
- (struct CGRect)_presentedRectForContentView;
- (struct CGRect)_offscreenRectForContentView;
- (struct CGRect)_idleOnscreenRectForBottomBanner;
- (struct CGRect)_offscreenRectForBottomBanner;
- (void)_endInteractivePresentationOrAnimation;
- (void)_beginInteractivePresentationOrAnimation;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)dismissingSuggestionPageView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

