//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSwitcherWallpaperPageContentView.h"

@class SBAppSwitcherSettings, SBAppView, SBDisplayItem, SBFakeStatusBarView, SBLayoutState, SBOrientationTransformWrapperView;

@interface SBSwitcherAppViewWrapperPageContentView : SBSwitcherWallpaperPageContentView
{
    SBAppView *_appView;
    SBOrientationTransformWrapperView *_appTransformView;
    SBDisplayItem *_displayItem;
    SBLayoutState *_layoutState;
    SBFakeStatusBarView *_fakeStatusBar;
    id <SBSwitcherAppViewWrapperPageContentViewDelegate> _delegate;
    SBAppSwitcherSettings *_settings;
    BOOL _presenting;
    BOOL _interactive;
    int _savedStatusBarStyleOverride;
}

@property(retain, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
@property(nonatomic) __weak id <SBSwitcherAppViewWrapperPageContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBAppView *appView; // @synthesize appView=_appView;
- (void).cxx_destruct;
- (void)_createStatusBarIfNeeded;
- (void)_updateBreadcrumbOverrides;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)interactionDidEnd:(BOOL)arg1;
- (void)viewDismissing:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(float)arg3 forTransitionRequest:(id)arg4;
- (void)viewPresenting:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(float)arg3 forTransitionRequest:(id)arg4;
- (void)prepareToBecomeVisibleIfNecessary;
- (void)_layoutFakeStatusBar;
- (void)layoutSubviews;
- (void)setContentMode:(int)arg1;
- (void)invalidate;
- (float)cornerRadius;
- (void)setCornerRadius:(float)arg1;
- (void)setOrientation:(int)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 appView:(id)arg2 displayItem:(id)arg3 layoutState:(id)arg4 delegate:(id)arg5;

@end

