//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSString;

@interface SBTestAlertItem : SBAlertItem
{
    BOOL _shouldShowInLockScreen;
    BOOL _forcesModalAlertAppearance;
    BOOL _behavesSuperModally;
    BOOL _allowMenuButtonDismissal;
    BOOL _allowLockScreenDismissal;
    BOOL _reappearsAfterUnlock;
    BOOL _reappearsAfterLock;
    BOOL __dismissesAutomatically;
    NSString *_title;
}

+ (id)alertItemWithShowInLockScreen:(BOOL)arg1 forcesModal:(BOOL)arg2 superModal:(BOOL)arg3;
@property(nonatomic) BOOL _dismissesAutomatically; // @synthesize _dismissesAutomatically=__dismissesAutomatically;
@property(nonatomic) BOOL reappearsAfterLock; // @synthesize reappearsAfterLock=_reappearsAfterLock;
@property(nonatomic) BOOL reappearsAfterUnlock; // @synthesize reappearsAfterUnlock=_reappearsAfterUnlock;
@property(nonatomic) BOOL allowLockScreenDismissal; // @synthesize allowLockScreenDismissal=_allowLockScreenDismissal;
@property(nonatomic) BOOL allowMenuButtonDismissal; // @synthesize allowMenuButtonDismissal=_allowMenuButtonDismissal;
@property(nonatomic) BOOL behavesSuperModally; // @synthesize behavesSuperModally=_behavesSuperModally;
@property(nonatomic) BOOL forcesModalAlertAppearance; // @synthesize forcesModalAlertAppearance=_forcesModalAlertAppearance;
@property(nonatomic) BOOL shouldShowInLockScreen; // @synthesize shouldShowInLockScreen=_shouldShowInLockScreen;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;

@end

