//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBFThermalBlockProvider.h"
#import "SBThermalWarningAlertItemDelegate.h"
#import "SBThermalWarningSuppressionAssertionDelegate.h"

@class NSDictionary, NSHashTable, NSMutableSet, NSString;

@interface SBThermalController : NSObject <SBThermalWarningSuppressionAssertionDelegate, SBThermalWarningAlertItemDelegate, SBFThermalBlockProvider>
{
    BOOL _sampling;
    double _samplingStartTime;
    NSDictionary *_samplingStartCPUTimesByApp;
    int _sunlightStateToken;
    int _coldTempToken;
    int _warningAssertionToken;
    int _warningResponseToken;
    NSMutableSet *_warningSuppressionAssertions;
    BOOL _warningSuppressionPreference;
    int _level;
    BOOL _inSunlight;
    NSHashTable *_observers;
}

+ (void)logThermalEvent:(id)arg1;
+ (id)sharedInstance;
@property(readonly, nonatomic, getter=isInSunlight) BOOL inSunlight; // @synthesize inSunlight=_inSunlight;
@property(nonatomic) int level; // @synthesize level=_level;
- (void).cxx_destruct;
- (void)_setBrickMode:(BOOL)arg1;
- (BOOL)_brickMode;
- (void)thermalWarningAlert:(id)arg1 didTriggerAction:(int)arg2;
- (void)thermalWarningAssertionExpired:(id)arg1;
- (BOOL)captureWarningSuppressionAssertionWithPort:(unsigned int)arg1 reason:(id)arg2;
- (void)_didReceiveWarningAction:(int)arg1;
- (void)_calculateAppsCPUTimesWithCompletion:(CDUnknownBlockType)arg1;
- (void)_killThermallyActiveApplication;
- (void)_killThermallyActiveApplicationGivenCPUTimes:(id)arg1;
- (void)_beginThermalJetsamCPUSampling;
- (void)respondToCurrentThermalCondition;
- (void)startListeningForThermalEvents;
- (BOOL)_isLevelBlocked:(int)arg1;
- (void)removeThermalObserver:(id)arg1;
- (void)addThermalObserver:(id)arg1;
- (BOOL)isThermalBlocked;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

