//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBPolygon.h"

@interface SBTouchTemplate : SBPolygon
{
}

- (unsigned int)matchesPolygon:(id)arg1 matchTransformsAllowed:(unsigned int)arg2 acceptanceFactor:(float)arg3 outMorphedCandidate:(id *)arg4;

@end

