//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, SBTreeNodeViewController;

@protocol SBTreeNodeViewControllerTransitionObserver <NSObject>

@optional
- (void)treeNodeViewController:(SBTreeNodeViewController *)arg1 willPerformOperation:(int)arg2 fromViewController:(SBTreeNodeViewController *)arg3 fromIndexPath:(NSIndexPath *)arg4 toViewController:(SBTreeNodeViewController *)arg5 toIndexPath:(NSIndexPath *)arg6 withTransitionCoordinator:(id <SBViewControllerTransitionCoordinator>)arg7;
@end

