//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBTreeNodeViewControllerTransitionObserver.h"

@class NSIndexPath, SBTreeNodeViewController;

@protocol SBTreeNodeViewControllerDelegate <SBTreeNodeViewControllerTransitionObserver>
- (SBTreeNodeViewController *)treeNodeViewController:(SBTreeNodeViewController *)arg1 viewControllerForChildTreeNode:(id <SBTreeNode>)arg2 atIndexPath:(NSIndexPath *)arg3;

@optional
- (id <UIViewControllerInteractiveTransitioning>)treeNodeViewController:(SBTreeNodeViewController *)arg1 interactionControllerForAnimationController:(id <UIViewControllerAnimatedTransitioning>)arg2;
- (id <UIViewControllerAnimatedTransitioning>)treeNodeViewController:(SBTreeNodeViewController *)arg1 animationControllerForOperation:(int)arg2 animated:(BOOL)arg3 fromViewController:(SBTreeNodeViewController *)arg4 fromIndexPath:(NSIndexPath *)arg5 toViewController:(SBTreeNodeViewController *)arg6 toIndexPath:(NSIndexPath *)arg7;
- (NSIndexPath *)treeNodeViewController:(SBTreeNodeViewController *)arg1 destinationExpandedIndexPathForTargetIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)treeNodeViewController:(SBTreeNodeViewController *)arg1 targetExpandedIndexPathForProposedIndexPath:(NSIndexPath *)arg2;
- (void)treeNodeViewController:(SBTreeNodeViewController *)arg1 dismissedChildTreeNode:(id <SBTreeNode>)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)treeNodeViewController:(SBTreeNodeViewController *)arg1 selectedChildTreeNode:(id <SBTreeNode>)arg2 atIndexPath:(NSIndexPath *)arg3;
@end

