//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIAnimationZoomApp.h"

#import "SBTreeNodeViewControllerTransitionObserver.h"
#import "SBViewControllerReversibleAnimatedTransitioning.h"

@class NSString, SBAppView, SBLeafIcon;

@interface SBUIAnimationHomeScreenZoomApp : SBUIAnimationZoomApp <SBViewControllerReversibleAnimatedTransitioning, SBTreeNodeViewControllerTransitionObserver>
{
    id <SBViewControllerContextTransitioning> _transitionContext;
    SBLeafIcon *_transitioningIcon;
    SBAppView *_transitioningAppView;
    CDUnknownBlockType _homeScreenTransitionCompletion;
    BOOL _homeScreenTransitionFinishedCancelled;
    BOOL _finishedZooming;
    BOOL _attemptingCrossfade;
    BOOL _finishedCrossfadingToHostView;
    BOOL _finishedActivating;
    BOOL _activationFailed;
}

@property(retain, nonatomic) SBLeafIcon *transitioningIcon; // @synthesize transitioningIcon=_transitioningIcon;
- (void).cxx_destruct;
- (void)_maybeReportAnimationFinished;
- (void)_maybeStartCrossfade;
- (BOOL)_delaysLiveContentUntilZoomFinished;
- (void)_configureAppView:(id)arg1 forZoomDirection:(unsigned int)arg2;
- (void)treeNodeViewController:(id)arg1 willPerformOperation:(int)arg2 fromViewController:(id)arg3 fromIndexPath:(id)arg4 toViewController:(id)arg5 toIndexPath:(id)arg6 withTransitionCoordinator:(id)arg7;
- (void)animationEnded:(BOOL)arg1;
- (BOOL)supportsRestarting;
- (void)cancelTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)animateTransition:(id)arg1;
- (id)transitionAnimationFactory:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (id)_transitionAnimator;
- (void)_prepareAnimation;
- (BOOL)_pastPointOfNoReturn;
- (BOOL)transitionSupportsCancelling;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

