//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@interface SBUIPresentSwitcherAnimationController : SBUIMainScreenAnimationController
{
    BOOL _isInteractive;
}

- (id)animationSettings;
- (void)_startAnimation;
- (id)_getTransitionWindow;
- (void)endTransition:(BOOL)arg1 withSuccess:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)endInteractionWithCommitment:(BOOL)arg1;
- (void)setTransitionParameters:(CDStruct_3ee5880e)arg1;
- (BOOL)canTransitionWithTranslation;
- (id)initWithTransitionContextProvider:(id)arg1 interactive:(BOOL)arg2;

@end

