//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

#import "SBViewControllerInteractiveAnimatedTransitioning.h"

@class BSUIAnimationFactory, NSString, SBSceneLayoutAnimationWrapperView, SBWorkspaceApplicationTransitionContext;

@interface SBUISwitchAppSwipeAnimationController : SBUIMainScreenAnimationController <SBViewControllerInteractiveAnimatedTransitioning>
{
    BSUIAnimationFactory *_animationFactory;
    id <SBDosidoAnimator> _currentAnimator;
    unsigned int _currentDirection;
    SBSceneLayoutAnimationWrapperView *_startingView;
    SBSceneLayoutAnimationWrapperView *_targetView;
    SBWorkspaceApplicationTransitionContext *_startingTransitionContext;
    SBWorkspaceApplicationTransitionContext *_targetTransitionContext;
    SBWorkspaceApplicationTransitionContext *_endingTransitionContext;
    id <SBViewControllerContextTransitioning> _animationTransition;
}

@property(readonly, nonatomic) SBWorkspaceApplicationTransitionContext *endingTransitionContext; // @synthesize endingTransitionContext=_endingTransitionContext;
@property(readonly, nonatomic) SBWorkspaceApplicationTransitionContext *targetTransitionContext; // @synthesize targetTransitionContext=_targetTransitionContext;
@property(readonly, nonatomic) unsigned int currentDirection; // @synthesize currentDirection=_currentDirection;
- (void).cxx_destruct;
- (id)_animationSettings;
- (id)_animationFactory;
- (void)_animator:(id)arg1 finishedAnimating:(BOOL)arg2;
- (void)_startAnimatingInDirection:(unsigned int)arg1;
- (id)_newStretchTransformerForDirection:(unsigned int)arg1;
- (id)_newDosidoAnimatorForDirection:(unsigned int)arg1;
- (id)_newAnimationWrapperViewForLayoutState:(id)arg1 roleMask:(unsigned int)arg2 displayMode:(int)arg3;
- (float)stepPercentage;
- (BOOL)isStepped;
- (float)percentComplete;
- (void)finishInteractiveTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)cancelTransition:(id)arg1 withCompletionSpeed:(float)arg2 completionCurve:(int)arg3;
- (void)updateTransition:(id)arg1 withPercentComplete:(float)arg2;
- (void)animateTransition:(id)arg1;
- (id)transitionAnimationFactory:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)enableSteppingWithAnimationSettings:(id)arg1;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (id)_transitionAnimator;
- (id)animationSettings;
- (id)_customizedDescriptionProperties;
- (void)_didComplete;
- (void)startAnimatingInDirection:(unsigned int)arg1 withContext:(id)arg2;
- (id)initWithTransitionContextProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

