//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class SBAppStatusBarSettingsAssertion, SBDosidoAnimator, SBWindowSelfHostWrapper, UIView;

@interface SBUIAnimationDosidoTransitionController : SBUIMainScreenAnimationController
{
    UIView *_fromView;
    UIView *_toView;
    SBWindowSelfHostWrapper *_homeScreenHostWrapper;
    SBDosidoAnimator *_dosidoAnimator;
    int _fromOrientation;
    BOOL _requiresHostView;
    BOOL _fromAppWantsLiveContent;
    BOOL _dosidoDidComplete;
    BOOL _crossfadeDidComplete;
    BOOL _activationFailed;
    BOOL _finishedActivating;
    unsigned int _direction;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
}

@property(nonatomic) BOOL fromAppWantsLiveContent; // @synthesize fromAppWantsLiveContent=_fromAppWantsLiveContent;
@property(nonatomic) unsigned int direction; // @synthesize direction=_direction;
- (void).cxx_destruct;
- (id)_mainScreenSnapshot;
- (BOOL)_isTransitionToSpotlight;
- (BOOL)_isTransitionFromSpotlight;
- (void)_maybeReportAnimationFinished;
- (void)_performCrossfadeIfNeeded;
- (void)_maybeStartCrossfade;
- (void)_startAnimation;
- (void)__startAnimation;
- (void)_setFromView:(id)arg1;
- (void)captureFlagsForActivatingApp:(id)arg1;
- (id)_animationFactory;
- (void)_invalidateWrapperView:(id)arg1;
- (void)setToView:(id)arg1;
- (int)orientationAtLaunch;
- (void)_evaluateTransparency;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)_setupDisplayModeForDeactivatingAppView:(id)arg1;
- (void)_setupDisplayModeForActivatingAppView:(id)arg1;
- (void)_setupDisplayModeForAppView:(id)arg1 displayMode:(int)arg2;
- (BOOL)isReasonableMomentToInterrupt;
- (void)_applicationDependencyStateChanged;
- (id)_animationProgressDependencies;
- (BOOL)_waitsForApplicationActivationIfNecessary;
- (void)_setHidden:(BOOL)arg1;
- (void)enableSteppingWithAnimationSettings:(id)arg1;
- (id)animationSettings;
- (void)dealloc;
- (id)initWithTransitionContextProvider:(id)arg1;
- (id)_getTransitionWindow;

@end

