//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class BSAnimationSettings, FBSceneHostManager, NSString, SBAppStatusBarSettingsAssertion, UIView;

@interface SBUIAnimationZoomApp : SBUIMainScreenAnimationController
{
    UIView *_contextHostView;
    NSString *_hostRequester;
    FBSceneHostManager *_transitioningSceneHostManager;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
    BSAnimationSettings *_animationSettings;
    BOOL _shouldHideAppStatusBar;
    unsigned int _zoomDirection;
}

@property(readonly, nonatomic) unsigned int zoomDirection; // @synthesize zoomDirection=_zoomDirection;
@property(retain, nonatomic) BSAnimationSettings *animationSettings; // @synthesize animationSettings=_animationSettings;
- (void).cxx_destruct;
- (double)_animationDelay;
- (double)_animationDuration;
- (id)_appStatusBarTransitionInfo;
- (void)_animateFakeStatusBarWithParameters:(id)arg1;
- (void)_animateWallpaperWithFactory:(id)arg1;
- (BOOL)_shouldHideAppStatusBar;
- (BOOL)_prefersSceneSnapshot;
- (BOOL)_requiresLiveHostView;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (id)_viewsForAnimationStepping;
- (BOOL)_waitsForApplicationActivationIfNecessary;
- (id)_animationProgressDependencies;
- (id)initWithTransitionContextProvider:(id)arg1 zoomDirection:(unsigned int)arg2;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

