//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBViewControllerContextTransitioning.h"
#import "SBViewControllerTransitionCoordinator.h"

@class BSUIAnimationFactory, FBDisplayLayoutTransition, NSMapTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, UIView;

@interface SBViewControllerTransitionContext : NSObject <SBViewControllerContextTransitioning, SBViewControllerTransitionCoordinator>
{
    int _presentationStyle;
    struct CGAffineTransform _targetTransform;
    NSMutableDictionary *_viewControllersByKey;
    NSMutableDictionary *_viewsByKey;
    NSMapTable *_initialFramesByViewController;
    NSMapTable *_finalFramesByViewController;
    BOOL _transitionStarted;
    BOOL _animationFinished;
    BOOL _transitionFinished;
    BOOL _transitionIsCancelled;
    BOOL _transitionWasEverCancelled;
    BOOL _transitionBeganInteractively;
    BOOL _transitionWasInteractive;
    BOOL _wantsAnimation;
    BOOL _transitionDidBeginCalled;
    float _transitionPercentComplete;
    unsigned int _transitionAnimationOptions;
    BSUIAnimationFactory *_transitionAnimationFactory;
    id <UIViewControllerAnimatedTransitioning> _animator;
    id <UIViewControllerInteractiveTransitioning> _interactor;
    NSMutableArray *_alongsideAnimations;
    NSMutableArray *_alongsideCompletions;
    NSMutableArray *_alongsideInteractionEndedHandlers;
    NSMutableSet *_alongsideAnimationViews;
    NSMutableArray *_transitionContinuations;
    unsigned int _outstandingClientCompletionCount;
    FBDisplayLayoutTransition *_layoutTransition;
    id <SBViewControllerTransitionContextDelegate> _delegate;
    UIView *_containerView;
}

@property(nonatomic) BOOL wantsAnimation; // @synthesize wantsAnimation=_wantsAnimation;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <SBViewControllerTransitionContextDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGAffineTransform targetTransform; // @synthesize targetTransform=_targetTransform;
@property(nonatomic) int presentationStyle; // @synthesize presentationStyle=_presentationStyle;
- (void).cxx_destruct;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)notifyWhenInteractionChangesUsingBlock:(CDUnknownBlockType)arg1;
- (void)_runInteractionEndedHandlers;
- (void)_runAlongsideAnimationBlocksInEnclosingAnimationContext;
- (void)_runAlongsideAnimationBlocksWithFactory:(id)arg1 options:(unsigned int)arg2;
- (void)_startInteractiveTransition;
- (id)_interactiveAnimator;
- (BOOL)_animatorIsInteractive;
- (BOOL)_objectSupportsRestarting:(id)arg1;
- (BOOL)_interactorSupportsRestarting;
- (BOOL)_animatorSupportsRestarting;
- (id)_reversibleAnimator;
- (BOOL)_animatorIsReversible;
- (void)_updateTransitionAnimationFactoryAndOptions;
- (CDUnknownBlockType)_acquireTransitionCompletion;
- (void)addTransitionContinuation:(CDUnknownBlockType)arg1;
- (void)_completeTransition;
- (void)_completeTransitionIfPossible;
- (BOOL)requiresRestartableAnimations;
- (BOOL)requiresInteractiveAnimations;
- (BOOL)requiresCancellableAnimations;
- (void)notifyWhenInteractionEndsUsingBlock:(CDUnknownBlockType)arg1;
- (BOOL)animateAlongsideTransitionInView:(id)arg1 animation:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)animateAlongsideTransition:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (unsigned int)transitionAnimationOptions;
- (id)transitionAnimationFactory;
- (int)completionCurve;
- (float)completionVelocity;
- (float)percentComplete;
- (double)transitionDuration;
- (BOOL)isCancelled;
- (BOOL)wasPreviousPhaseInteractive;
- (BOOL)initiallyInteractive;
- (BOOL)transitionWasRestarted;
- (void)restartTransition;
- (BOOL)supportsRestarting;
- (BOOL)supportsCancelling;
- (void)cancelTransition;
- (struct CGRect)finalFrameForViewController:(id)arg1;
- (struct CGRect)initialFrameForViewController:(id)arg1;
- (id)viewForKey:(id)arg1;
- (id)viewControllerForKey:(id)arg1;
- (void)completeTransition:(BOOL)arg1;
- (void)pauseInteractiveTransition;
- (void)cancelInteractiveTransition;
- (void)finishInteractiveTransition;
- (void)updateInteractiveTransition:(float)arg1;
- (BOOL)transitionWasCancelled;
@property(readonly, nonatomic) BOOL isInterruptible;
- (BOOL)isInteractive;
- (BOOL)isAnimated;
- (void)startTransition;
@property(readonly, nonatomic) BOOL isTransitioning;
- (void)setFinalFrame:(struct CGRect)arg1 forViewController:(id)arg2;
- (void)setInitialFrame:(struct CGRect)arg1 forViewController:(id)arg2;
- (void)setView:(id)arg1 forKey:(id)arg2;
- (void)setViewController:(id)arg1 forKey:(id)arg2;
@property(retain, nonatomic) id <UIViewControllerInteractiveTransitioning> interactor;
@property(retain, nonatomic) id <UIViewControllerAnimatedTransitioning> animator;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

