//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSString, SBWallpaperEffectView;

@interface SBWallpaperStyleInfo : NSObject <BSDescriptionProviding>
{
    CDStruct_f206ec99 _priorityInfo[14];
    SBWallpaperEffectView *_wallpaperEffectView;
    CDStruct_04b3617e _styleTransitionState;
}

@property(nonatomic) CDStruct_04b3617e styleTransitionState; // @synthesize styleTransitionState=_styleTransitionState;
@property(retain, nonatomic) SBWallpaperEffectView *wallpaperEffectView; // @synthesize wallpaperEffectView=_wallpaperEffectView;
- (void).cxx_destruct;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) int highestValidPriority;
- (void)enumerateValidPrioritiesUsingBlock:(CDUnknownBlockType)arg1;
- (void)removePriorityInfoForPriority:(int)arg1;
- (void)setPriorityInfo:(CDStruct_f206ec99)arg1 forPriority:(int)arg2;
- (CDStruct_f206ec99)priorityInfoForPriority:(int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

