//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "SBDashBoardWallpaperOverlayHosting.h"
#import "SBFLegibilitySettingsProviderDelegate.h"
#import "SBFWallpaperConfigurationManagerDelegate.h"
#import "SBFWallpaperViewInternalObserver.h"
#import "SBUIActiveOrientationObserver.h"
#import "SBWallpaperServerDelegate.h"
#import "UIWindowDelegate.h"
#import "_UISettingsKeyObserver.h"

@class NSHashTable, NSMutableSet, NSString, SBComposedWallpaperSpecification, SBFFileCache, SBFWallpaperConfigurationManager, SBFWallpaperView, SBWallpaperAggdLogger, SBWallpaperControllerCoordinator, SBWallpaperPreviewSnapshotCache, SBWallpaperStyleInfo, UIImage, UIView, UIView<SBDashBoardWallpaperOverlay>, UIWindow;

@interface SBWallpaperController : NSObject <SBFLegibilitySettingsProviderDelegate, SBFWallpaperViewInternalObserver, SBUIActiveOrientationObserver, _UISettingsKeyObserver, SBFWallpaperConfigurationManagerDelegate, BSDescriptionProviding, SBWallpaperServerDelegate, UIWindowDelegate, SBDashBoardWallpaperOverlayHosting>
{
    UIWindow *_wallpaperWindow;
    UIView *_wallpaperContainerView;
    UIView *_wallpaperOverlayContainerView;
    int _orientation;
    SBFWallpaperView *_lockscreenWallpaperView;
    SBFWallpaperView *_homescreenWallpaperView;
    SBFWallpaperView *_sharedWallpaperView;
    NSHashTable *_lockscreenObservers;
    NSHashTable *_homescreenObservers;
    NSMutableSet *_suspendColorSamplingReasons;
    NSMutableSet *_suspendWallpaperAnimationReasons;
    NSMutableSet *_requireWallpaperReasons;
    NSMutableSet *_hideHomescreenWallpaperReasons;
    NSMutableSet *_hideLockscreenWallpaperReasons;
    int _displayedVariant;
    float _lockscreenOnlyWallpaperAlpha;
    NSHashTable *_lockscreenBlurViews;
    NSHashTable *_homescreenBlurViews;
    int _disallowRasterizationBlockCount;
    NSMutableSet *_disallowRasterizationReasonsHomeVariant;
    NSMutableSet *_disallowRasterizationReasonsLockVariant;
    UIImage *_homescreenLightForegroundBlurImage;
    struct CGRect _homescreenLightForegroundBlurImageDisplayRect;
    BOOL _creatingHomescreenLightForegroundBlurImage;
    BOOL _isSuspendingMotionEffectsForBlur;
    SBWallpaperPreviewSnapshotCache *_previewCache;
    int _activeOrientationSource;
    BOOL _coalescingGeometryChanges;
    int _locationsWithCoalescedGeometryChanges;
    SBWallpaperControllerCoordinator *_coordinator;
    NSMutableSet *_homescreenStyleChangeDelayReasons;
    SBFFileCache *_downloadedWallpaperCache;
    SBFWallpaperConfigurationManager *_wallpaperConfigurationManager;
    UIView<SBDashBoardWallpaperOverlay> *_wallpaperOverlay;
    float _homescreenWallpaperScale;
    float _lockscreenWallpaperScale;
    SBComposedWallpaperSpecification *_overriddenComposedWallpaperSpecification;
    SBWallpaperStyleInfo *_homescreenStyleInfo;
    SBWallpaperStyleInfo *_lockscreenStyleInfo;
    SBWallpaperAggdLogger *_wallpaperAggdLogger;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SBWallpaperAggdLogger *wallpaperAggdLogger; // @synthesize wallpaperAggdLogger=_wallpaperAggdLogger;
@property(readonly, nonatomic) SBWallpaperStyleInfo *lockscreenStyleInfo; // @synthesize lockscreenStyleInfo=_lockscreenStyleInfo;
@property(readonly, nonatomic) SBWallpaperStyleInfo *homescreenStyleInfo; // @synthesize homescreenStyleInfo=_homescreenStyleInfo;
@property(retain, nonatomic) SBFWallpaperView *sharedWallpaperView; // @synthesize sharedWallpaperView=_sharedWallpaperView;
@property(retain, nonatomic) SBFWallpaperView *homescreenWallpaperView; // @synthesize homescreenWallpaperView=_homescreenWallpaperView;
@property(retain, nonatomic) SBFWallpaperView *lockscreenWallpaperView; // @synthesize lockscreenWallpaperView=_lockscreenWallpaperView;
@property(copy, nonatomic) SBComposedWallpaperSpecification *overriddenComposedWallpaperSpecification; // @synthesize overriddenComposedWallpaperSpecification=_overriddenComposedWallpaperSpecification;
@property(readonly, nonatomic) int activeOrientationSource; // @synthesize activeOrientationSource=_activeOrientationSource;
@property(nonatomic) float lockscreenWallpaperScale; // @synthesize lockscreenWallpaperScale=_lockscreenWallpaperScale;
@property(nonatomic) float homescreenWallpaperScale; // @synthesize homescreenWallpaperScale=_homescreenWallpaperScale;
- (void).cxx_destruct;
- (id)relinquishHostingOfWallpaperOverlay;
- (void)startHostingWallpaperOverlay:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)wallpaperServer:(id)arg1 fetchThumbnailDataForVariant:(int)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)wallpaperConfigurationManager:(id)arg1 didChangeWallpaperConfigurationForVariants:(int)arg2;
- (void)wallpaperViewDidChangeWantsRasterization:(id)arg1;
- (void)wallpaperView:(id)arg1 didChangeZoomFactor:(float)arg2;
- (void)wallpaperViewDidInvalidateGeometry:(id)arg1;
- (void)wallpaperViewDidInvalidateBlurs:(id)arg1;
- (void)providerLegibilitySettingsChanged:(id)arg1;
- (void)activeInterfaceOrientationDidChangeToOrientation:(int)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(int)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(int)arg1;
- (void)_forceUpdateToSpringBoardInterfaceOrientationWithAnimationDuration:(double)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)orientationSource:(int)arg1 didRotateFromInterfaceOrientation:(int)arg2;
- (void)orientationSource:(int)arg1 willAnimateRotationToInterfaceOrientation:(int)arg2 duration:(double)arg3;
- (void)orientationSource:(int)arg1 willRotateToInterfaceOrientation:(int)arg2 duration:(double)arg3;
- (BOOL)_isAcceptingOrientationChangesFromSource:(int)arg1;
- (void)setActiveOrientationSource:(int)arg1 andUpdateToOrientation:(int)arg2 usingCrossfadeToBlack:(BOOL)arg3;
- (void)_noteSignificantTimeChanged:(id)arg1;
- (void)_saveWallpaperAggdKeysForLocations:(int)arg1 withConfiguration:(id)arg2;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)_updateRasterizationState;
- (void)_endDisallowRasterizationBlock;
- (void)_beginDisallowRasterizationBlock;
- (id)_getImageInRect:(struct CGRect)arg1 withZoomFactor:(float)arg2 forVariant:(int)arg3 style:(inout int *)arg4;
- (id)_newFakeBlurViewForVariant:(int)arg1 style:(int)arg2 transformIgnoresRotation:(BOOL)arg3;
- (void)_createHomescreenLightForegroundBlurImageIfNecessary;
- (void)_updateBlurGeneration;
- (id)_sourceForFakeBlurView:(id)arg1;
- (void)_unregisterFakeBlurView:(id)arg1;
- (void)_registerFakeBlurView:(id)arg1;
- (void)_suspendOrResumeWallpaperAnimation;
- (void)_suspendOrResumeColorSampling;
- (id)_blurViewsForVariant:(int)arg1;
- (id)_observersForVariant:(int)arg1;
- (id)_activeWallpaperView;
- (id)_wallpaperViewForVariant:(int)arg1;
- (void)_updateBlurImagesForVariant:(int)arg1;
- (void)_reconfigureBlurViewsForVariant:(int)arg1;
- (void)_handleWallpaperGeometryChangedForVariant:(int)arg1;
- (void)_handleWallpaperLegibilitySettingsChanged:(id)arg1 forVariant:(int)arg2;
- (void)_handleWallpaperChangedForVariant:(int)arg1;
- (BOOL)_updateEffectViewForVariant:(int)arg1 withFactory:(id)arg2;
- (BOOL)_updateEffectViewForVariant:(int)arg1 oldState:(CDStruct_04b3617e *)arg2 newState:(CDStruct_04b3617e *)arg3 oldEffectView:(id *)arg4 newEffectView:(id *)arg5;
- (void)_updateMotionEffectsForState:(CDStruct_04b3617e)arg1;
- (BOOL)_shouldSuspendMotionEffectsForState:(CDStruct_04b3617e)arg1;
- (void)_endSuspendingMotionEffectsForBlurIfNeeded;
- (void)_beginSuspendingMotionEffectsForBlurIfNeeded;
- (void)_updateScreenBlanked;
- (void)_accessibilityReduceTransparencyChanged:(id)arg1;
- (void)_motionEffectsChanged;
- (id)_newWallpaperEffectViewForVariant:(int)arg1 transitionState:(CDStruct_04b3617e)arg2;
- (void)_clearWallpaperEffectView:(id)arg1;
- (void)_clearWallpaperView:(id)arg1;
- (id)_makeAndInsertWallpaperViewWithConfiguration:(id)arg1 forVariant:(int)arg2 shared:(BOOL)arg3;
- (void)_updateSeparateWallpaper;
- (void)_updateSharedWallpaper;
- (BOOL)_isWallpaperView:(id)arg1 displayingWallpaperWithConfiguration:(id)arg2 forVariant:(int)arg3;
- (void)_updateWallpaperForLocations:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL darkensHomeScreenStaticWallpaperToEnsureLegibility;
- (BOOL)supportsDarkeningWallpaperToEnsureLegibilityForWallpaperType:(int)arg1;
- (BOOL)darkensWallpaperToEnsureLegibilityForVariant:(int)arg1 wallpaperType:(int)arg2;
- (BOOL)_canShareWallpaperViewsForSharedWallpaperType:(int)arg1;
- (BOOL)variantsWouldShareWallpaperIfNotForHomeScreenTreatment;
- (BOOL)variantsShareWallpaper;
@property(readonly, nonatomic) SBFWallpaperConfigurationManager *wallpaperConfigurationManager;
- (void)_checkForComposedWallpapersAtLaunch;
- (void)_background_setWallpaperForLocations:(int)arg1 fromImage:(id)arg2 name:(id)arg3;
- (void)_rebuildComposedWallpapers;
- (id)_homeScreenWallpaperSpecificationFromProfile;
- (id)_lockScreenWallpaperSpecificationFromProfile;
- (void)_updateWallpaperParallax;
- (void)_batterySaverModeChanged:(id)arg1;
- (void)_updateWallpaperHidden;
- (BOOL)_isWallpaperHiddenForVariant:(int)arg1;
- (void)_setWallpaperHidden:(BOOL)arg1 variant:(int)arg2 reason:(id)arg3;
- (BOOL)_setDisallowRasterization:(BOOL)arg1 withReason:(id)arg2 reasons:(id)arg3;
- (BOOL)_isRasterizationDisallowedForCurrentVariant;
- (id)_window;
@property(readonly, nonatomic) SBFFileCache *downloadedWallpaperCache;
- (id)vendWallpaperViewForConfiguration:(id)arg1 forVariant:(int)arg2 shared:(BOOL)arg3;
- (unsigned int)_bestStaticWallpaperViewInitializationOptionsForVariant:(int)arg1 shared:(BOOL)arg2;
- (void)setDisallowsRasterization:(BOOL)arg1 forVariant:(int)arg2 withReason:(id)arg3;
- (id)previewCache;
- (struct CGRect)homescreenLightForegroundBlurImageContentsRectForWallpaperRelativeRect:(struct CGRect)arg1;
- (id)homescreenLightForegroundBlurImage;
- (float)contrastInRect:(struct CGRect)arg1 contrastWithinBoxes:(float *)arg2 contrastBetweenBoxes:(float *)arg3 forVariant:(int)arg4;
- (float)contrastForVariant:(int)arg1;
- (float)contrastInRect:(struct CGRect)arg1 forVariant:(int)arg2;
- (id)averageColorInRect:(struct CGRect)arg1 forVariant:(int)arg2 withSmudgeRadius:(float)arg3;
- (id)averageColorInRect:(struct CGRect)arg1 forVariant:(int)arg2;
- (id)averageColorForVariant:(int)arg1;
- (id)legibilitySettingsForVariant:(int)arg1;
@property(readonly, nonatomic) id <SBFIrisWallpaperView> irisWallpaperView;
- (void)resumeWallpaperAnimationForReason:(id)arg1;
- (void)suspendWallpaperAnimationForReason:(id)arg1;
- (void)resumeColorSamplingForReason:(id)arg1;
- (void)suspendColorSamplingForReason:(id)arg1;
- (void)removeObserver:(id)arg1 forVariant:(int)arg2;
- (void)addObserver:(id)arg1 forVariant:(int)arg2;
- (BOOL)shouldDelayHomescreenStyleUpdates;
- (void)endDelayingHomescreenStyleChangesForReason:(id)arg1 animationFactory:(id)arg2;
- (void)beginDelayingHomescreenStyleChangesForReason:(id)arg1;
- (void)endRequiringWithReason:(id)arg1;
- (void)beginRequiringWithReason:(id)arg1;
- (BOOL)removeWallpaperStyleForPriority:(int)arg1 forVariant:(int)arg2 withAnimationFactory:(id)arg3;
- (BOOL)setWallpaperStyleTransitionState:(CDStruct_04b3617e)arg1 forPriority:(int)arg2 forVariant:(int)arg3 withAnimationFactory:(id)arg4;
- (BOOL)setWallpaperStyle:(int)arg1 forPriority:(int)arg2 forVariant:(int)arg3 withAnimationFactory:(id)arg4;
- (id)wallpaperStyleInfoForVariant:(int)arg1;
@property(readonly, nonatomic) CDStruct_04b3617e currentHomescreenStyleTransitionState;
- (void)setLockscreenOnlyWallpaperAlpha:(float)arg1;
- (void)setLockscreenWallpaperScale:(float)arg1 withAnimationFactory:(id)arg2;
- (void)setHomescreenWallpaperScale:(float)arg1 withAnimationFactory:(id)arg2;
@property(nonatomic) float windowLevel;
- (void)setLockscreenWallpaperContentsRect:(struct CGRect)arg1;
- (void)updateIrisWallpaperForLockedState;
- (BOOL)updateIrisWallpaperForUnlockedState;
- (void)setVariant:(int)arg1 withOutAnimationFactory:(id)arg2 inAnimationFactory:(id)arg3 completion:(CDUnknownBlockType)arg4;
@property(nonatomic) int variant;
- (void)dealloc;
- (id)initWithOrientation:(int)arg1 variant:(int)arg2;
- (BOOL)removeHomescreenStyleForBundleIdentifier:(id)arg1 withPriority:(int)arg2 animationFactory:(id)arg3;
- (BOOL)setHomescreenStyleTransitionState:(CDStruct_04b3617e)arg1 forBundleIdentifier:(id)arg2 withPriority:(int)arg3 animationFactory:(id)arg4;
- (BOOL)setHomescreenStyle:(int)arg1 forBundleIdentifier:(id)arg2 withPriority:(int)arg3 animationFactory:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

