//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBWallpaperStyleTransitionStateWrapper : NSObject
{
    CDStruct_04b3617e _state;
}

+ (id)wrapperWithState:(CDStruct_04b3617e)arg1;
@property(nonatomic) CDStruct_04b3617e state; // @synthesize state=_state;
- (id)description;

@end

