//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>, NSRecursiveLock, NSString, NWSystemPathMonitor;

@interface SBWiFiManager : NSObject
{
    NSRecursiveLock *_lock;
    struct __CFRunLoop *_callbackRunLoop;
    struct __WiFiManagerClient *_manager;
    struct __WiFiDeviceClient *_device;
    NSString *_deviceInterfaceName;
    BOOL _mainThread_devicePresent;
    struct __WiFiNetwork *_currentNetwork;
    struct __WiFiNetwork *_previousNetwork;
    BOOL _currentNetworkHasBeenSet;
    BOOL _currentNetworkIsIOSHotspot;
    BOOL _currentNetworkIsIOSHotspotHasBeenSet;
    BOOL _powered;
    BOOL _poweredHasBeenSet;
    int _mainThread_signalStrengthBars;
    int _mainThread_signalStrengthRSSI;
    BOOL _mainThread_signalStrengthHasBeenSet;
    NWSystemPathMonitor *_systemPathMonitor;
    NSObject<OS_dispatch_source> *_primaryInterfaceUpdateTimeoutSource;
    struct __WiFiNetwork *_primaryInterface;
    BOOL _primaryInterfaceHasBeenSet;
    BOOL _isPrimaryInterface;
    BOOL _isPrimaryInterfaceChanging;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_updateWiFiDevice;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_primaryInterfaceChanged:(BOOL)arg1;
- (id)_wifiInterface;
- (struct __CFRunLoop *)wifiRunLoopRef;
- (BOOL)isPrimaryInterface;
- (void)resetSettings;
- (id)knownNetworks;
- (void)updateSignalStrength;
- (void)updateSignalStrengthFromRawRSSI:(int)arg1 andScaledRSSI:(float)arg2;
- (int)signalStrengthRSSI;
- (int)signalStrengthBars;
- (void)setWiFiEnabled:(BOOL)arg1;
- (BOOL)wiFiEnabled;
- (void)setPowered:(BOOL)arg1;
- (BOOL)isPowered;
- (id)currentNetworkName;
- (void)clearWiFiPickerPreferences;
- (BOOL)_cachedIsAssociated;
- (BOOL)isAssociatedToIOSHotspot;
- (BOOL)isAssociated;
- (void)_updateCurrentNetwork;
- (void)_linkDidChange;
- (void)_powerStateDidChange;
- (void)_updateWiFiState;
- (void)_runManagerCallbackThread;
- (void)_lock_spawnManagerCallbackThread;
- (struct __WiFiManagerClient *)_lock_manager;
- (void)_lock_setWiFiDevice:(struct __WiFiDeviceClient *)arg1;
- (void)updateDevicePresence;
- (BOOL)devicePresent;
- (BOOL)wifiSupported;
- (id)init;

@end

