//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBWorkspaceTransitionContext.h"

@class NSSet, SBWorkspaceApplication, SBWorkspaceEntity;

@interface SBWorkspaceApplicationTransitionContext : SBWorkspaceTransitionContext
{
    CDUnknownBlockType _resultBlock;
    BOOL _background;
    BOOL _fencesAnimations;
    BOOL _alwaysRunsWatchdog;
    BOOL _waitsForSceneUpdates;
    BOOL _sentActivationResult;
    int _interfaceOrientation;
    int _preferredInterfaceOrientation;
}

@property(nonatomic) int preferredInterfaceOrientation; // @synthesize preferredInterfaceOrientation=_preferredInterfaceOrientation;
@property(nonatomic) int interfaceOrientation; // @synthesize interfaceOrientation=_interfaceOrientation;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
@property(nonatomic) BOOL waitsForSceneUpdates; // @synthesize waitsForSceneUpdates=_waitsForSceneUpdates;
@property(nonatomic) BOOL alwaysRunsWatchdog; // @synthesize alwaysRunsWatchdog=_alwaysRunsWatchdog;
@property(nonatomic) BOOL fencesAnimations; // @synthesize fencesAnimations=_fencesAnimations;
@property(nonatomic, getter=isBackground) BOOL background; // @synthesize background=_background;
- (void).cxx_destruct;
- (double)_watchdogScaleFactorForApplication:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)_realActivatingEntity;
- (id)_display;
- (id)executionContextForApplication:(id)arg1;
- (id)sceneClientSettingsForApplication:(id)arg1 withSceneSettings:(id)arg2;
- (id)sceneTransitionContextForApplication:(id)arg1;
- (id)sceneSettingsForApplication:(id)arg1;
- (id)sceneIdentifierForApplication:(id)arg1;
- (void)finalize;
- (id)previousApplicationForBundleID:(id)arg1;
- (id)previousApplicationForLayoutRole:(int)arg1;
@property(readonly, copy, nonatomic) NSSet *previousApplications;
- (id)applicationForBundleID:(id)arg1;
- (id)previousEntityForLayoutRole:(int)arg1;
- (void)setPreviousEntity:(id)arg1 forLayoutRole:(int)arg2;
- (id)entityForLayoutRole:(int)arg1;
- (void)setEntity:(id)arg1 forLayoutRole:(int)arg2;
- (id)applicationForLayoutRole:(int)arg1;
- (void)setApplication:(id)arg1 forLayoutRole:(int)arg2;
@property(retain, nonatomic) SBWorkspaceApplication *activatingApplication; // @dynamic activatingApplication;
@property(retain, nonatomic) SBWorkspaceEntity *activatingEntity; // @dynamic activatingEntity;
@property(readonly, copy, nonatomic) NSSet *applications;
- (void)sendActivationResultErrorCode:(int)arg1 reason:(id)arg2;
- (BOOL)hasSentActivationResult;
- (void)dealloc;
- (id)init;

@end

