//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BSUIAnimationFactory;

@interface SBZoomableCrossfadeView : UIView
{
    BSUIAnimationFactory *_animationFactory;
    UIView *_startView;
    UIView *_endView;
    BOOL _translucent;
    BOOL _crossfaded;
    BOOL _allowsGroupOpacityDuringCrossfade;
    BOOL _adaptsAnimationFactoryTimingFunction;
}

+ (id)crossfadeViewWithStartView:(id)arg1 endView:(id)arg2 translucent:(BOOL)arg3;
@property(nonatomic) BOOL adaptsAnimationFactoryTimingFunction; // @synthesize adaptsAnimationFactoryTimingFunction=_adaptsAnimationFactoryTimingFunction;
@property(nonatomic) BOOL allowsGroupOpacityDuringCrossfade; // @synthesize allowsGroupOpacityDuringCrossfade=_allowsGroupOpacityDuringCrossfade;
@property(retain, nonatomic) BSUIAnimationFactory *animationFactory; // @synthesize animationFactory=_animationFactory;
- (void).cxx_destruct;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)crossfadeWithCompletion:(CDUnknownBlockType)arg1;
- (void)layoutSubviews;
- (id)_initWithStartView:(id)arg1 endView:(id)arg2 translucent:(BOOL)arg3;

@end

